// ————— Account and settings —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// Sign-in exists for one reason: progress currently lives in one browser on one
// device, and a learner who clears their browser loses everything. Save/Restore
// was the cheap insurance; this is the real one.
//
// ⚠️ THE WHOLE DESIGN IS SHAPED BY WHAT MUST NOT HAPPEN. Introducing accounts is
// the single most likely way to reproduce the twelve days of silent grammar-loss
// this app already shipped, at a larger scale — a sign-in that quietly replaces
// this device's progress with an empty account looks exactly like success. So:
//
//   · nothing local is written until the merge has been settled
//   · a genuine disagreement is a QUESTION, with no default and no timer
//   · the account's copy of a losing side is preserved automatically, by the
//     database's archive trigger. The DEVICE's copy is not — saving it is a
//     button the learner presses, offered beside the choice that would
//     overwrite it (Session 23: nothing downloads without being asked for)
//
// ⚠️ THE SECOND BULLET NOW DESCRIBES THE FIRST SIGN-IN ON A DEVICE AND NOTHING
// ELSE (2026-09-16). Once this browser has joined the account, a load pulls the
// account's copy down and applies it without asking. That reversal is only safe
// because lib/autosave.js now keeps the account continuously current, and the
// reasoning — including why the old rule was right for the app it was written
// for — is set out in full at the top of sync.js. Read it before changing
// runSync below; the two halves are one change and neither stands alone.
//
// WHY THE QUESTION HAD TO GO. runSync runs once per session restore, so on
// every page load. `tsumiki-module-recency-v1` moves when you merely OPEN a
// section. So any use of the app guaranteed a difference at the next load, and
// the learner was asked to choose between their own progress and their own
// progress, on an ordinary refresh. The merge was working; the cadence around
// it was not.
//
// The rule itself lives in sync.js and is tested by test-progress-sync.py.
// Everything here is presentation of that rule, plus the two settings.
//
// ⚠️ AND THE READ-MERGE-WRITE ITSELF NOW LIVES IN sync.js TOO, as `reconcile`
// (2026-09-29). It used to be the body of runSync, which meant the ORDER of its
// steps — local written before the push, autosave armed before the push, the
// account's copy preferred only when the read can be trusted — was tangled up
// with useState and a live Supabase client and could not be tested at all. What
// is left here is what belongs here: who we are, what to put on screen, and the
// two things a browser can do that a merge core cannot — hold a cross-tab lock,
// and wait for a person to answer a question.
//
// WHAT IS NO LONGER HERE (Session 24): progress, counts and the reset moved to
// lib/progress.jsx — the drawer's own note says an account is not a place, and
// progress is one.
//
// WHAT IS STILL HERE, AFTER A DETOUR: Save and Restore, together, under BACKUP.
// They came out of the header in the same session, which was right — a pair of
// file buttons above every lesson is a standing hint that the app might lose
// your work. They were then briefly split, save at one danger point and restore
// on another screen, which was worse: a backup you can take on one screen and
// put back on another is not a feature, it is two loose ends. One place, both
// halves, named as the thing it is.

import { useState, useEffect, useCallback, useRef } from "react";
import { T } from "./tokens.js";
import { accountsConfigured, getClient, redirectTo } from "./supabase.js";
import {
  readLocal, writeLocal, reconcile,
  fetchRemote, pushRemote, preserveLocalToFile,
} from "./sync.js";
import { autosaveSession, armAutosave, disarmAutosave, flushNow } from "./autosave.js";
import { SECTIONS, SETTINGS } from "./stats.js";
import {
  storage, downloadProgress, importProgress, KEYS,
  joinedAccount, markAccountJoined, clearAccountJoined, accountVersion,
} from "./storage.js";

// Storage keys are not learner-facing language. Names, never counts.
const KEY_LABELS = {
  "tsumiki-hiragana-progress-v2": "Hiragana practice",
  "tsumiki-katakana-progress-v1": "Katakana practice",
  "tsumiki-kanji-progress-v1": "Kanji practice",
  "tsumiki-known-kanji-v1": "Kanji you have met",
  "tsumiki-known-words-v1": "Words you have met",
  "tsumiki-n5-progress-v1": "Grammar lessons",
  "tsumiki-learner-depth-v1": "How deep grammar explanations go",
  "tsumiki-achievement-points-v1": "Koban",
  "tsumiki-engagement-v1": "Daily rhythm and quests",
  "tsumiki-stroke-data-v1": "Handwriting calibration",
  "tsumiki-kanji-mode": "Kanji reading mode",
  "tsumiki-module-recency-v1": "Which section you used last",
};
const label = (k) => KEY_LABELS[k] || k;

// ————— ⚠️ ONE RECONCILE AT A TIME, ACROSS THE WHOLE BROWSER —————
//
// FINDING 1 OF THE SESSION 33 LOG READ. MEASURED, throwaway account, sign-in at
// 13:54:53:
//
//     13:54:55.975 / .977   OPTIONS tsumiki_progress   (two preflights, 2ms apart)
//     13:54:55.996          GET  tsumiki_progress
//     13:54:56.662          GET  tsumiki_progress
//     13:54:56.697          POST tsumiki_progress  200
//     13:54:56.872          POST tsumiki_progress  201
//
// The whole sign-in sync, twice — and only ONE GET /auth/v1/user in the entire
// flow, which is the detail that identifies the cause.
//
// IT IS NOT StrictMode (that is a production build) and NOT a double mount
// (<Account> is mounted once, unconditionally, in App.jsx). The `syncedFor` ref
// below is a sound guard and was working: it simply cannot see across tabs, and
// THE MAGIC-LINK FLOW MAKES TWO TABS BY ITS NATURE — the tab that asked for the
// link, and the tab the email opens.
//
// CONFIRMED IN THE LIBRARY'S OWN SOURCE, @supabase/auth-js 2.115.0,
// dist/module/GoTrueClient.js: the client opens a `BroadcastChannel` named after
// its storage key and posts every auth state change to it (`_notifyAllSubscribers`
// → `broadcastChannel.postMessage({event, session})`), and the receiving tab
// replays it to its own subscribers with `broadcast = false`. SIGNED_IN is
// handled by name there. So the link tab fetches the user — one
// GET /auth/v1/user — and the OTHER tab is handed the finished session with no
// network call at all, fires its onAuthStateChange, and runs its own runSync
// against the same localStorage and the same account row. Two preflights 2ms
// apart is two browsing contexts starting the same request.
//
// ⚠️ WHY IT MATTERS MORE THAN AN EMPTY ACCOUNT SUGGESTS. On a device with
// progress that genuinely conflicts, BOTH tabs reach the conflict question. The
// learner answers in one; the other still holds the old question with the old
// sides, and answering it there — or answering it differently — overwrites the
// first answer. Two open copies of the one question this whole flow exists to
// ask exactly once.
//
// THE FIX IS ORDERING, NOT A HEURISTIC. The second tab waits, then re-evaluates
// from scratch; by then `markAccountJoined` has run, so it takes the JOINED path
// and finds nothing to do. Nothing has to detect anything or guess who is first.
const SYNC_LOCK = "tsumiki-progress-sync";

// ⚠️ THE LOCK IS HELD WHILE THE LEARNER READS THE CONFLICT QUESTION, and that is
// the deliberate half of this design. The alternative — release it and have the
// second tab re-check joined-state before offering its own question — does not
// work: at the moment tab A puts the question on screen it has NOT yet called
// markAccountJoined (it cannot; nothing has been settled), so tab B would look,
// see "not joined", and show the second copy of the question. Cross-tab
// awareness of "a question is currently open" would need another channel and
// another thing to keep in step. Holding the lock says the same thing with the
// mechanism already in hand, and the cost is bounded and safe: tab B sits in
// "Syncing…", its autosave stays unarmed so its writes are REMEMBERED and not
// sent, and the lock is released by the browser if tab A is closed without
// answering.
//
// WHERE navigator.locks IS UNAVAILABLE (older Safari, some embedded webviews)
// THIS RUNS UNLOCKED, and the two-tab race is back exactly as it was. That is a
// worse outcome than a lock and a better one than the alternative: a
// localStorage mutex needs a lease, a timeout and a crash-recovery rule, and a
// lease that gets stuck is a learner who can never sign in again. Do not invent
// one.
function withSyncLock(fn) {
  const locks = typeof navigator !== "undefined" ? navigator.locks : null;
  if (!locks || typeof locks.request !== "function") return fn();
  return locks.request(SYNC_LOCK, fn);
}

const box = {
  background: T.sheet, border: `1px solid ${T.hairline}`, borderRadius: 10,
  padding: "16px 16px 18px", fontFamily: T.uiFont, color: T.ink,
};
const primary = {
  background: T.ink, color: T.paper, border: "none", borderRadius: 8,
  padding: "10px 16px", cursor: "pointer", font: `600 0.875rem ${T.uiFont}`,
};
const ghost = {
  background: "none", color: T.ink, border: `1px solid ${T.hairline}`,
  borderRadius: 8, padding: "10px 16px", cursor: "pointer",
  font: `0.875rem ${T.uiFont}`,
};
const danger = {
  ...primary, background: T.shu,
};
const quiet = { font: `0.75rem/1.6 ${T.uiFont}`, color: T.sub };

// What to say afterwards. Nothing here opens the panel — a load that went well
// is not an event, and the note is only there to explain the screen if the
// learner opens it themselves.
function noteFor(r) {
  if (!r) return null;
  if (r.path === "load") {
    if (r.stale) {
      // Only reachable when the read was provably behind — see THE STALE READ in
      // sync.js. Said in the learner's terms: their work is what survived.
      return "Your account was still catching up with this device, so nothing " +
             "here was replaced. It has been saved again just now.";
    }
    return r.cameBack
      ? `Your account had newer progress on ${r.cameBack === 1 ? "one item" : r.cameBack + " items"} — reload to see it.`
      : null;
  }
  if (r.path === "merged") {
    const back = r.plan.pulled.length;
    return back
      ? `Signed in. ${back === 1 ? "One thing" : back + " things"} came back from your account — reload to see it.`
      : "Signed in. This device's progress is now saved to your account.";
  }
  if (r.path === "settled") {
    return r.side === "remote"
      ? "Your account's version is now on this device."
      : "This device's version is now on your account. The version it replaced is kept in your account's history.";
  }
  return null;
}

export default function Account({ open, setOpen }) {
  const [client, setClient] = useState(null);
  const [session, setSession] = useState(null);
  const [email, setEmail] = useState("");
  const [phase, setPhase] = useState("idle");   // idle | sending | sent | syncing | conflict | done
  const [note, setNote] = useState(null);
  const [error, setError] = useState(null);
  const [plan, setPlan] = useState(null);

  const [settings, setSettings] = useState({});
  const [savedCopy, setSavedCopy] = useState(null);
  const [fileMsg, setFileMsg] = useState(null);

  // ————— an auth callback that came back as an error —————
  // Supabase returns failures in the URL FRAGMENT, not as a status code:
  //   #error=access_denied&error_code=otp_expired&error_description=…
  // Nothing reads that by default, so an expired or already-used link lands the
  // learner on a normal-looking home screen with no session and no explanation —
  // which is indistinguishable from "the email never arrived".
  useEffect(() => {
    if (typeof window === "undefined") return;
    const h = new URLSearchParams(window.location.hash.replace(/^#/, ""));
    const desc = h.get("error_description");
    if (!desc) return;
    setError(desc.replace(/\+/g, " ") +
      ". Sign-in links can only be used once, and they expire — ask for a new one.");
    setOpen(true);
    window.history.replaceState(null, "", window.location.pathname + window.location.search);
  }, [setOpen]);

  // ————— sign-in state —————
  useEffect(() => {
    if (!accountsConfigured()) return undefined;
    let alive = true;
    let sub = null;
    (async () => {
      try {
        const c = await getClient();
        if (!alive || !c) return;
        setClient(c);
        const { data } = await c.auth.getSession();
        if (!alive) return;
        setSession(data.session ?? null);
        sub = c.auth.onAuthStateChange((_evt, s) => setSession(s ?? null)).data.subscription;
      } catch (e) {
        if (alive) setError("Could not reach the account service. " + (e?.message || ""));
      }
    })();
    return () => { alive = false; sub?.unsubscribe(); };
  }, []);

  // ————— the learner's answer to a conflict, as a promise —————
  // `reconcile` awaits this, which is what keeps the cross-tab lock held until
  // the question has actually been answered. Holds { resolve, reject } while a
  // question is on screen and null the rest of the time.
  const conflictGate = useRef(null);

  const releaseGate = useCallback((side) => {
    const g = conflictGate.current;
    conflictGate.current = null;
    if (!g) return false;
    if (side) g.resolve(side);
    else {
      // Nobody is going to answer — the panel is going away. Unwind rather than
      // settle: settling on the learner's behalf is the one thing this file
      // refuses to do, and an unwound reconcile releases the lock so another tab
      // can ask instead.
      const e = new Error("the sign-in question was closed before it was answered");
      e.code = "abandoned";
      g.reject(e);
    }
    return true;
  }, []);

  // A pending question must not outlive the component, or the lock is held for
  // the lifetime of the tab and no other tab can ever reconcile.
  useEffect(() => () => { releaseGate(null); }, [releaseGate]);

  // ————— the load, run once per session restore —————
  //
  // TWO PATHS, and which one runs is a fact about this browser rather than a
  // judgement about the data: has it joined this account before?
  //
  //   NOT JOINED — a new device, or one that signed out and kept studying.
  //     This browser's progress predates the account relationship and was never
  //     pushed, so the two sides are genuinely independent histories. Merge,
  //     and ask if they really disagree. Unchanged from Session 23.
  //
  //   JOINED — every ordinary load. The account is where the work is and this
  //     browser is a cache of it that reports every change (lib/autosave.js), so
  //     a difference means this cache is behind. Take the account's copy for
  //     the keys that differ, keep the keys it does not have, and say nothing —
  //     UNLESS the read can be proved out of date, in which case the same merge
  //     answers its own question with "local" instead. See THE STALE READ in
  //     sync.js.
  //
  // Note what the second path does NOT do: it does not replace the document. It
  // runs the same per-key merge and then answers the merge's question, so a key
  // this device holds and the account does not still survives (rule 1), and the
  // checker log is still UNIONED rather than chosen between. An account that is
  // empty cannot wipe a device, because an empty value is absent and yields.
  //
  // All of that is `reconcile` in sync.js now. What is here is the wiring: the
  // client, the lock, the question, and the sentence at the end.
  const runSync = useCallback(async (c, user) => {
    setPhase("syncing"); setError(null); setNote(null);
    // Who we would save as. NOT permission to save — see the split in
    // autosave.js. From here until armAutosave() inside reconcile, every module
    // write is remembered and nothing is sent, because this device's progress
    // and the account's have not been reconciled yet.
    autosaveSession(c, user.id);
    try {
      const result = await reconcile({
        keys: KEYS,
        joined: () => joinedAccount() === user.id,
        markJoined: () => markAccountJoined(user.id),
        readLocal,
        writeLocal,
        fetchRemote: () => fetchRemote(c, user.id),
        pushRemote: (map) => pushRemote(c, user.id, map),
        arm: armAutosave,
        rememberedVersion: () => accountVersion(user.id),
        sleep: (ms) => new Promise((res) => setTimeout(res, ms)),
        // The two sides are not held in state: the settle happens inside
        // reconcile, which already has them. Keeping a second copy here is how
        // a second settle path gets built by accident.
        onConflict: (p) => new Promise((resolve, reject) => {
          setPlan(p);
          setPhase("conflict");
          setOpen(true);   // a question must not sit behind a closed menu
          conflictGate.current = { resolve, reject };
        }),
        lock: withSyncLock,
      });
      setPhase("done");
      setNote(noteFor(result));
    } catch (e) {
      if (e?.code === "abandoned") { setPhase("idle"); return; }
      // ⚠️ AUTOSAVE IS NOT ARMED ON THE READ-FAILURE PATH, AND THAT IS THE
      // POINT: a device that could not read the account must not write to it.
      // The cost is that this whole session saves to the browser only, so the
      // message says that rather than leaving it to be discovered later.
      //
      // `localWritten` is set by reconcile and is the difference between two
      // promises that are not interchangeable. "Nothing on this device was
      // changed" is a real claim and must not be made on a path that had
      // already written the settled document before the upload failed.
      setPhase("done");
      const why = e?.message || String(e);
      setError(e?.localWritten
        ? "Signed in, and this device was updated, but it could not be saved to " +
          "your account: " + why + ". Your work is still being saved here — but " +
          "it will not reach your account until you reload."
        : "Signed in, but syncing failed: " + why +
          ". Nothing on this device was changed, and your work is still " +
          "being saved here — but it will not reach your account until " +
          "you reload.");
    }
  }, [setOpen]);

  // ⚠️ THE GUARD IS A REF, NOT `phase`. `phase` is state, so two invocations of
  // this effect in the same tick both read "idle" and both start a sync — which
  // is what happened on the first real sign-in, Sep 6 2026, visible in the API
  // log as the whole cycle twice. StrictMode makes it visible; the race is real
  // without it, because setPhase() does not take effect until the next render.
  //
  // IT WAS HARMLESS ONLY BECAUSE THAT ACCOUNT WAS EMPTY. With progress on both
  // sides it corrupts the one rule this file exists to enforce: run A reads an
  // empty remote, merges, and pushes; run B then reads the remote A just wrote,
  // finds it identical to local, and reports "clean" — so a genuine conflict is
  // silently settled instead of asked about.
  //
  // ⚠️ AND IT IS STILL ONLY A GUARD WITHIN ONE TAB. It was read as covering the
  // whole browser, and the Session 33 log read found the sign-in sync running
  // twice anyway, from two tabs — which is what SYNC_LOCK above is for. Keep
  // both: this ref stops the same tab starting twice without a round trip, and
  // the lock stops two tabs overlapping. Neither does the other's job.
  const syncedFor = useRef(null);

  useEffect(() => {
    if (!client || !session?.user) return;
    if (syncedFor.current === session.user.id) return;
    syncedFor.current = session.user.id;
    runSync(client, session.user);
  }, [client, session, runSync]);

  // ————— settings: refreshed whenever the panel opens —————
  const refresh = useCallback(async () => {
    const cur = {};
    for (const st of SETTINGS) {
      const r = await storage.get(st.key);
      cur[st.key] = r?.value ?? st.fallback;
    }
    setSettings(cur);
  }, []);

  useEffect(() => { if (open) refresh(); }, [open, refresh]);

  const changeSetting = async (key, value) => {
    setSettings((s) => ({ ...s, [key]: value }));
    try { await storage.set(key, value); } catch (e) { console.error(e); }
  };

  // ————— settling a conflict —————
  // The writes live in `reconcile`, which is still holding the cross-tab lock
  // and waiting for exactly this. All that happens here is that the learner's
  // answer is handed back — so there is one implementation of "settle a
  // conflict" rather than two that have to agree, and the lock is released by
  // the same code path that took it.
  const choose = (side) => {
    setPhase("syncing");
    setError(null);
    releaseGate(side);
  };

  const sendLink = async (e) => {
    e.preventDefault();
    if (!client || !email.trim()) return;
    setPhase("sending"); setError(null);
    const { error: err } = await client.auth.signInWithOtp({
      email: email.trim(),
      options: { emailRedirectTo: redirectTo() },
    });
    if (err) { setPhase("idle"); setError(err.message); return; }
    setPhase("sent");
  };

  const signOut = async () => {
    // Sign-out does NOT clear local progress. The learner keeps studying on this
    // device exactly as before; the next sign-in merges rather than replaces.
    //
    // An unanswered conflict question goes with the session, and unwinding it
    // first releases the cross-tab lock — otherwise signing out while a question
    // is open would leave every other tab waiting on a reconcile that is never
    // going to finish.
    releaseGate(null);
    //
    // ⚠️ THE ORDER HERE IS THE WHOLE POINT. Anything written since the last
    // idle save is still only in this browser, and the token that could upload
    // it is about to be thrown away — so flush FIRST, while there is still a
    // session, then stop autosaving, then sign out.
    await flushNow("sign-out");
    disarmAutosave();
    // And forget that this browser ever joined, so the next sign-in is a
    // genuine merge again. The learner is about to keep studying signed out,
    // which makes this device an independent history for the second time —
    // see the note beside clearAccountJoined in storage.js.
    //
    // The version watermark is NOT cleared: it stays a true statement about that
    // account row whoever is signed in, and discarding it would throw away a
    // real protection. It is keyed by user id, so a second learner on this
    // browser inherits nothing from it.
    clearAccountJoined();
    await client?.auth.signOut();
    syncedFor.current = null;
    setSession(null); setPhase("idle"); setNote(null); setPlan(null);
  };

  const restore = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const r = new FileReader();
    r.onload = () => {
      setFileMsg(importProgress(String(r.result)).message);
      refresh();
      // ⚠️ A RESTORE MUST REACH THE ACCOUNT, OR THE NEXT LOAD UNDOES IT.
      // importProgress announces each restored key, so a save was already
      // scheduled; this only stops the learner from closing the tab inside the
      // debounce window. A no-op when signed out.
      flushNow("restore");
    };
    r.readAsText(file);
    e.target.value = "";
  };

  // The reset moved to Progress (Session 24) and goes through
  // resetEverywhere() in stats.js, so the "clear the account too or it undoes
  // itself" rule has exactly one implementation.

  if (!open) return null;

  const close = () => { if (phase !== "conflict") setOpen(false); };

  return (
    <>
      <div onClick={close} aria-hidden="true" style={{
        position: "fixed", inset: 0, zIndex: 30, background: "rgba(34,37,43,0.44)",
      }} />
      <div role="dialog" aria-modal="true" aria-label="Account" style={{
        position: "fixed", zIndex: 31, left: "50%", top: "50%",
        transform: "translate(-50%,-50%)", width: "min(92vw, 460px)",
        maxHeight: "86vh", overflowY: "auto", ...box,
      }}>
        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
          <h2 style={{ font: `600 1.0625rem ${T.uiFont}`, margin: 0 }}>Account</h2>
          {phase !== "conflict" && (
            <button onClick={close} aria-label="Close" style={{
              background: "none", border: "none", cursor: "pointer",
              padding: 8, font: `1rem ${T.uiFont}`, color: T.sub,
            }}>✕</button>
          )}
        </div>

        {/* A conflict takes the whole panel. It is the only thing in this file
            that must be answered before anything else can be done.

            ⚠️ AND IT IS NOW REACHED ONLY ON THE FIRST SIGN-IN ON A DEVICE.
            Every later load takes the account's copy silently, so this panel is
            no longer something a learner meets on a refresh — which is what it
            had become, and why it was worth reversing. The copy below says
            "first time" out loud for that reason: a question that turns up once
            in the life of a device deserves to explain why it is here. */}
        {phase === "conflict" && plan ? (
          <>
            <p style={{ font: `0.875rem/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
              This is the first time you have signed in on this device, and it
              already has progress of its own that does not match your account.
              Nothing has been changed yet.
            </p>
            <ul style={{ font: `0.875rem/1.7 ${T.uiFont}`, color: T.ink, paddingLeft: 20, margin: "10px 0" }}>
              {plan.conflicts.map((k) => <li key={k}>{label(k)}</li>)}
            </ul>
            {(plan.pushed.length > 0 || plan.pulled.length > 0) && (
              <p style={{ font: `0.8125rem/1.6 ${T.uiFont}`, color: T.sub }}>
                Everything else is kept from both sides either way — only the
                items above have to be decided.
              </p>
            )}
            <div style={{ display: "flex", flexDirection: "column", gap: 8, marginTop: 14 }}>
              <button onClick={() => choose("local")} style={primary}>
                Keep what is on this device
              </button>
              <button onClick={() => choose("remote")} style={ghost}>
                Keep what is in my account
              </button>
              {/* Offered BEFORE the choice, not fired after it. The asymmetry
                  below is real and is stated rather than papered over. */}
              <button onClick={() => {
                const ok = preserveLocalToFile();
                setSavedCopy(ok ? "Saved. The file is in your downloads." :
                                  "The browser would not save the file.");
              }} style={{ ...ghost, borderStyle: "dashed" }}>
                Save this device's version to a file first
              </button>
            </div>
            {savedCopy && (
              <p role="status" style={{ ...quiet, color: T.ok, marginTop: 8 }}>{savedCopy}</p>
            )}
            <p style={{ ...quiet, marginTop: 12 }}>
              Your account keeps its own history either way, so choosing this
              device is always reversible. Choosing your account replaces what is
              here — save a copy first if you are not sure.
            </p>
            <p style={{ ...quiet, marginTop: 8 }}>
              After this, your progress saves to your account as you work, and
              this device follows it. You will not be asked again.
            </p>
          </>
        ) : (
          <>
            {/* Session 24: the Progress tab moved out to its own destination
                (lib/progress.jsx). What is left is one thing — who you are, the
                two settings, and Save/Restore — so there is nothing to tab
                between. */}
            {true && (
              <>
                {!accountsConfigured() && (
                  <p style={{ font: `0.875rem/1.6 ${T.uiFont}`, color: T.sub }}>
                    Accounts are not switched on in this build. Your progress is
                    saved in this browser, and Save still writes it to a file you
                    can keep.
                  </p>
                )}

                {accountsConfigured() && !session && phase !== "sent" && (
                  <>
                    <p style={{ font: `0.875rem/1.6 ${T.uiFont}`, color: T.sub, marginTop: 0 }}>
                      Sign in and your progress follows you to any device. Right
                      now it lives only in this browser — clearing it would clear
                      your work.
                    </p>
                    <form onSubmit={sendLink} style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}>
                      <input
                        type="email" required value={email} autoComplete="email"
                        onChange={(ev) => setEmail(ev.target.value)}
                        placeholder="you@example.com"
                        style={{
                          flex: "1 1 200px", minWidth: 0, padding: "10px 12px",
                          border: `1px solid ${T.hairline}`, borderRadius: 8,
                          font: `0.875rem ${T.uiFont}`, color: T.ink, background: T.paper,
                        }}
                      />
                      <button type="submit" disabled={phase === "sending"} style={primary}>
                        {phase === "sending" ? "Sending…" : "Email me a link"}
                      </button>
                    </form>
                    <p style={{ ...quiet, marginTop: 10 }}>
                      No password. We email a link that signs you in on this device.
                    </p>
                  </>
                )}

                {phase === "sent" && !session && (
                  <p style={{ font: `0.875rem/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
                    Check <strong>{email}</strong>. The link signs you in on this
                    device — open it in this browser rather than another one.
                  </p>
                )}

                {session && (
                  <dl style={{ margin: "0 0 14px", font: `0.875rem/1.7 ${T.uiFont}` }}>
                    <div style={{ display: "flex", gap: 10 }}>
                      <dt style={{ color: T.sub, minWidth: 96 }}>Signed in as</dt>
                      <dd style={{ margin: 0, wordBreak: "break-all" }}>{session.user.email}</dd>
                    </div>
                    <div style={{ display: "flex", gap: 10, marginTop: 4 }}>
                      <dt style={{ color: T.sub, minWidth: 96 }}>Progress</dt>
                      <dd style={{ margin: 0, color: phase === "syncing" ? T.sub : T.ok }}>
                        {phase === "syncing" ? "Syncing…" : "Saving as you work"}
                      </dd>
                    </div>
                  </dl>
                )}

                {note && (
                  <p role="status" style={{
                    font: `0.8125rem/1.6 ${T.uiFont}`, color: T.note,
                    background: T.noteBg, borderRadius: 8, padding: "10px 12px",
                  }}>{note}</p>
                )}

                {/* ————— Settings ————— */}
                {/* Both of these were only reachable from inside the grammar
                    module, which is a strange place for a preference to live. */}
                <h3 style={{ font: `600 0.8125rem ${T.uiFont}`, letterSpacing: ".4px",
                             color: T.sub, margin: "18px 0 8px" }}>SETTINGS</h3>
                {SETTINGS.map((s) => (
                  <div key={s.key} style={{ marginBottom: 12 }}>
                    <label htmlFor={`set-${s.key}`}
                           style={{ display: "block", font: `0.875rem ${T.uiFont}`, marginBottom: 5 }}>
                      {s.label}
                    </label>
                    <select id={`set-${s.key}`} value={settings[s.key] ?? s.fallback}
                            onChange={(e) => changeSetting(s.key, e.target.value)}
                            style={{
                              width: "100%", padding: "9px 10px", borderRadius: 8,
                              border: `1px solid ${T.hairline}`, background: T.paper,
                              font: `0.875rem ${T.uiFont}`, color: T.ink,
                            }}>
                      {s.options.map((o) => (
                        <option key={o.value} value={o.value}>{o.label}</option>
                      ))}
                    </select>
                  </div>
                ))}
                <p style={quiet}>
                  A change here applies the next time you open that section.
                </p>

                {/* ————— BACKUP —————
                    Save and Restore live HERE, together, as one thing a person
                    can name: a backup you take and a backup you put back.
                    They came out of the header in Session 24 (a pair of file
                    buttons above every lesson is a standing hint that the app
                    might lose your work) and were briefly split across two
                    screens, which was worse — a save on one screen and a
                    restore on another is not a feature, it is two loose ends.

                    NOT GATED ON BEING SIGNED IN, deliberately. A learner with
                    no account is exactly the one whose progress lives in a
                    single browser, and the file is the only thing standing
                    between them and a cleared cache.

                    The two Save buttons elsewhere — beside the sign-in conflict
                    choice below, and beside the reset confirm in Progress — are
                    shortcuts to this same download, offered at the two moments
                    something is about to be overwritten. This is where the way
                    BACK lives, for all three of them. */}
                <h3 style={{ font: `600 0.8125rem ${T.uiFont}`, letterSpacing: ".4px",
                             color: T.sub, margin: "18px 0 8px" }}>BACKUP</h3>
                <p style={{ ...quiet, marginTop: 0 }}>
                  {session
                    ? "Your account already keeps your progress across devices. A file is the extra copy you hold yourself."
                    : "Without an account your progress lives only in this browser. A file is the only copy that survives clearing it."}
                </p>
                <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>
                  <button onClick={downloadProgress} style={ghost}>Save to a file</button>
                  <label style={{ ...ghost, display: "inline-block" }}>
                    Restore from a file
                    <input type="file" accept="application/json" onChange={restore}
                           style={{ display: "none" }} />
                  </label>
                </div>
                {fileMsg && (
                  <p role="status" style={{
                    font: `0.8125rem/1.6 ${T.uiFont}`, color: T.note, background: T.noteBg,
                    borderRadius: 8, padding: "10px 12px", marginTop: 10,
                  }}>{fileMsg}</p>
                )}

                {session && (
                  <>
                    <h3 style={{ font: `600 0.8125rem ${T.uiFont}`, letterSpacing: ".4px",
                                 color: T.sub, margin: "18px 0 8px" }}>THIS DEVICE</h3>
                    <button onClick={signOut} style={ghost}>Sign out</button>
                  </>
                )}
                {session && (
                  <p style={{ ...quiet, marginTop: 10 }}>
                    Signing out leaves this device's progress exactly where it is.
                  </p>
                )}
              </>
            )}

          </>
        )}

        {error && (
          <p role="alert" style={{
            font: `0.8125rem/1.6 ${T.uiFont}`, color: T.shu, marginTop: 12,
          }}>{error}</p>
        )}
      </div>
    </>
  );
}
