// ————— Account and settings —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// Sign-in exists for one reason: progress currently lives in one browser on one
// device, and a learner who clears their browser loses everything. Save/Restore
// was the cheap insurance; this is the real one.
//
// ⚠️ THE WHOLE DESIGN IS SHAPED BY WHAT MUST NOT HAPPEN. Introducing accounts is
// the single most likely way to reproduce the twelve days of silent grammar-loss
// this app already shipped, at a larger scale — a sign-in that quietly replaces
// this device's progress with an empty account looks exactly like success. So:
//
//   · nothing local is written until the merge has been settled
//   · a genuine disagreement is a QUESTION, with no default and no timer
//   · the account's copy of a losing side is preserved automatically, by the
//     database's archive trigger. The DEVICE's copy is not — saving it is a
//     button the learner presses, offered beside the choice that would
//     overwrite it (Session 23: nothing downloads without being asked for)
//
// The rule itself lives in sync.js and is tested by test-progress-sync.py.
// Everything here is presentation of that rule, plus the two settings.
//
// WHAT IS NO LONGER HERE (Session 24): progress, counts and the reset moved to
// lib/progress.jsx — the drawer's own note says an account is not a place, and
// progress is one.
//
// WHAT IS STILL HERE, AFTER A DETOUR: Save and Restore, together, under BACKUP.
// They came out of the header in the same session, which was right — a pair of
// file buttons above every lesson is a standing hint that the app might lose
// your work. They were then briefly split, save at one danger point and restore
// on another screen, which was worse: a backup you can take on one screen and
// put back on another is not a feature, it is two loose ends. One place, both
// halves, named as the thing it is.

import { useState, useEffect, useCallback, useRef } from "react";
import { T } from "./tokens.js";
import { accountsConfigured, getClient, redirectTo } from "./supabase.js";
import {
  readLocal, writeLocal, mergeProgress, resolveConflicts,
  fetchRemote, pushRemote, preserveLocalToFile,
} from "./sync.js";
import { SECTIONS, SETTINGS } from "./stats.js";
import { storage, downloadProgress, importProgress } from "./storage.js";

// Storage keys are not learner-facing language. Names, never counts.
const KEY_LABELS = {
  "tsumiki-hiragana-progress-v2": "Hiragana practice",
  "tsumiki-katakana-progress-v1": "Katakana practice",
  "tsumiki-kanji-progress-v1": "Kanji practice",
  "tsumiki-known-kanji-v1": "Kanji you have met",
  "tsumiki-known-words-v1": "Words you have met",
  "tsumiki-n5-progress-v1": "Grammar lessons",
  "tsumiki-learner-depth-v1": "How deep grammar explanations go",
  "tsumiki-achievement-points-v1": "Koban",
  "tsumiki-engagement-v1": "Daily rhythm and quests",
  "tsumiki-stroke-data-v1": "Handwriting calibration",
  "tsumiki-kanji-mode": "Kanji reading mode",
  "tsumiki-module-recency-v1": "Which section you used last",
};
const label = (k) => KEY_LABELS[k] || k;

const box = {
  background: T.sheet, border: `1px solid ${T.hairline}`, borderRadius: 10,
  padding: "16px 16px 18px", fontFamily: T.uiFont, color: T.ink,
};
const primary = {
  background: T.ink, color: T.paper, border: "none", borderRadius: 8,
  padding: "10px 16px", cursor: "pointer", font: `600 14px ${T.uiFont}`,
};
const ghost = {
  background: "none", color: T.ink, border: `1px solid ${T.hairline}`,
  borderRadius: 8, padding: "10px 16px", cursor: "pointer",
  font: `14px ${T.uiFont}`,
};
const danger = {
  ...primary, background: T.shu,
};
const quiet = { font: `12px/1.6 ${T.uiFont}`, color: T.sub };

export default function Account({ open, setOpen }) {
  const [client, setClient] = useState(null);
  const [session, setSession] = useState(null);
  const [email, setEmail] = useState("");
  const [phase, setPhase] = useState("idle");   // idle | sending | sent | syncing | conflict | done
  const [note, setNote] = useState(null);
  const [error, setError] = useState(null);
  const [plan, setPlan] = useState(null);
  const [sides, setSides] = useState(null);

  const [settings, setSettings] = useState({});
  const [savedCopy, setSavedCopy] = useState(null);
  const [fileMsg, setFileMsg] = useState(null);

  // ————— an auth callback that came back as an error —————
  // Supabase returns failures in the URL FRAGMENT, not as a status code:
  //   #error=access_denied&error_code=otp_expired&error_description=…
  // Nothing reads that by default, so an expired or already-used link lands the
  // learner on a normal-looking home screen with no session and no explanation —
  // which is indistinguishable from "the email never arrived".
  useEffect(() => {
    if (typeof window === "undefined") return;
    const h = new URLSearchParams(window.location.hash.replace(/^#/, ""));
    const desc = h.get("error_description");
    if (!desc) return;
    setError(desc.replace(/\+/g, " ") +
      ". Sign-in links can only be used once, and they expire — ask for a new one.");
    setOpen(true);
    window.history.replaceState(null, "", window.location.pathname + window.location.search);
  }, [setOpen]);

  // ————— sign-in state —————
  useEffect(() => {
    if (!accountsConfigured()) return undefined;
    let alive = true;
    let sub = null;
    (async () => {
      try {
        const c = await getClient();
        if (!alive || !c) return;
        setClient(c);
        const { data } = await c.auth.getSession();
        if (!alive) return;
        setSession(data.session ?? null);
        sub = c.auth.onAuthStateChange((_evt, s) => setSession(s ?? null)).data.subscription;
      } catch (e) {
        if (alive) setError("Could not reach the account service. " + (e?.message || ""));
      }
    })();
    return () => { alive = false; sub?.unsubscribe(); };
  }, []);

  // ————— the merge, run once per sign-in —————
  const runSync = useCallback(async (c, user) => {
    setPhase("syncing"); setError(null); setNote(null);
    try {
      const local = readLocal();
      const remoteRow = await fetchRemote(c, user.id);
      const remote = remoteRow.data || {};
      const p = mergeProgress(local, remote);

      if (p.status === "clean") {
        // Writing local first and pushing second means a failed upload leaves
        // the learner with MORE progress than they started with, never less.
        writeLocal(p.merged);
        await pushRemote(c, user.id, p.merged);
        setPhase("done");
        setNote(p.pulled.length
          ? `Signed in. ${p.pulled.length === 1 ? "One thing" : p.pulled.length + " things"} came back from your account — reload to see it.`
          : "Signed in. This device's progress is now saved to your account.");
      } else {
        setPlan(p);
        setSides({ local, remote });
        setPhase("conflict");
        setOpen(true);   // a question must not sit behind a closed menu
      }
    } catch (e) {
      setPhase("done");
      setError("Signed in, but syncing failed: " + (e?.message || String(e)) +
               ". Nothing on this device was changed.");
    }
  }, [setOpen]);

  // ⚠️ THE GUARD IS A REF, NOT `phase`. `phase` is state, so two invocations of
  // this effect in the same tick both read "idle" and both start a sync — which
  // is what happened on the first real sign-in, Sep 6 2026, visible in the API
  // log as the whole cycle twice. StrictMode makes it visible; the race is real
  // without it, because setPhase() does not take effect until the next render.
  //
  // IT WAS HARMLESS ONLY BECAUSE THAT ACCOUNT WAS EMPTY. With progress on both
  // sides it corrupts the one rule this file exists to enforce: run A reads an
  // empty remote, merges, and pushes; run B then reads the remote A just wrote,
  // finds it identical to local, and reports "clean" — so a genuine conflict is
  // silently settled instead of asked about.
  const syncedFor = useRef(null);

  useEffect(() => {
    if (!client || !session?.user) return;
    if (syncedFor.current === session.user.id) return;
    syncedFor.current = session.user.id;
    runSync(client, session.user);
  }, [client, session, runSync]);

  // ————— settings: refreshed whenever the panel opens —————
  const refresh = useCallback(async () => {
    const cur = {};
    for (const st of SETTINGS) {
      const r = await storage.get(st.key);
      cur[st.key] = r?.value ?? st.fallback;
    }
    setSettings(cur);
  }, []);

  useEffect(() => { if (open) refresh(); }, [open, refresh]);

  const changeSetting = async (key, value) => {
    setSettings((s) => ({ ...s, [key]: value }));
    try { await storage.set(key, value); } catch (e) { console.error(e); }
  };

  // ————— settling a conflict —————
  const choose = async (side) => {
    setPhase("syncing");
    try {
      // The account's copy is preserved by the archive trigger either way. The
      // DEVICE's copy has no such net, so it gets one before being overwritten.
      const settled = resolveConflicts(plan, sides.local, sides.remote, side);
      writeLocal(settled);
      await pushRemote(client, session.user.id, settled);
      setPhase("done");
      setNote(side === "remote"
        ? "Your account's version is now on this device."
        : "This device's version is now on your account. The version it replaced is kept in your account's history.");
    } catch (e) {
      setPhase("done");
      setError("That did not go through: " + (e?.message || String(e)) +
               ". Nothing was overwritten.");
    }
  };

  const sendLink = async (e) => {
    e.preventDefault();
    if (!client || !email.trim()) return;
    setPhase("sending"); setError(null);
    const { error: err } = await client.auth.signInWithOtp({
      email: email.trim(),
      options: { emailRedirectTo: redirectTo() },
    });
    if (err) { setPhase("idle"); setError(err.message); return; }
    setPhase("sent");
  };

  const signOut = async () => {
    // Sign-out does NOT clear local progress. The learner keeps studying on this
    // device exactly as before; the next sign-in merges rather than replaces.
    await client?.auth.signOut();
    syncedFor.current = null;
    setSession(null); setPhase("idle"); setNote(null); setPlan(null); setSides(null);
  };

  const restore = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const r = new FileReader();
    r.onload = () => { setFileMsg(importProgress(String(r.result)).message); refresh(); };
    r.readAsText(file);
    e.target.value = "";
  };

  // The reset moved to Progress (Session 24) and goes through
  // resetEverywhere() in stats.js, so the "clear the account too or it undoes
  // itself" rule has exactly one implementation.

  if (!open) return null;

  const close = () => { if (phase !== "conflict") setOpen(false); };

  return (
    <>
      <div onClick={close} aria-hidden="true" style={{
        position: "fixed", inset: 0, zIndex: 30, background: "rgba(34,37,43,0.44)",
      }} />
      <div role="dialog" aria-modal="true" aria-label="Account" style={{
        position: "fixed", zIndex: 31, left: "50%", top: "50%",
        transform: "translate(-50%,-50%)", width: "min(92vw, 460px)",
        maxHeight: "86vh", overflowY: "auto", ...box,
      }}>
        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
          <h2 style={{ font: `600 17px ${T.uiFont}`, margin: 0 }}>Account</h2>
          {phase !== "conflict" && (
            <button onClick={close} aria-label="Close" style={{
              background: "none", border: "none", cursor: "pointer",
              padding: 8, font: `16px ${T.uiFont}`, color: T.sub,
            }}>✕</button>
          )}
        </div>

        {/* A conflict takes the whole panel. It is the only thing in this file
            that must be answered before anything else can be done. */}
        {phase === "conflict" && plan ? (
          <>
            <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
              This device and your account both have progress, and they do not
              match. Nothing has been changed yet.
            </p>
            <ul style={{ font: `14px/1.7 ${T.uiFont}`, color: T.ink, paddingLeft: 20, margin: "10px 0" }}>
              {plan.conflicts.map((k) => <li key={k}>{label(k)}</li>)}
            </ul>
            {(plan.pushed.length > 0 || plan.pulled.length > 0) && (
              <p style={{ font: `13px/1.6 ${T.uiFont}`, color: T.sub }}>
                Everything else is kept from both sides either way — only the
                items above have to be decided.
              </p>
            )}
            <div style={{ display: "flex", flexDirection: "column", gap: 8, marginTop: 14 }}>
              <button onClick={() => choose("local")} style={primary}>
                Keep what is on this device
              </button>
              <button onClick={() => choose("remote")} style={ghost}>
                Keep what is in my account
              </button>
              {/* Offered BEFORE the choice, not fired after it. The asymmetry
                  below is real and is stated rather than papered over. */}
              <button onClick={() => {
                const ok = preserveLocalToFile();
                setSavedCopy(ok ? "Saved. The file is in your downloads." :
                                  "The browser would not save the file.");
              }} style={{ ...ghost, borderStyle: "dashed" }}>
                Save this device's version to a file first
              </button>
            </div>
            {savedCopy && (
              <p role="status" style={{ ...quiet, color: T.ok, marginTop: 8 }}>{savedCopy}</p>
            )}
            <p style={{ ...quiet, marginTop: 12 }}>
              Your account keeps its own history either way, so choosing this
              device is always reversible. Choosing your account replaces what is
              here — save a copy first if you are not sure.
            </p>
          </>
        ) : (
          <>
            {/* Session 24: the Progress tab moved out to its own destination
                (lib/progress.jsx). What is left is one thing — who you are, the
                two settings, and Save/Restore — so there is nothing to tab
                between. */}
            {true && (
              <>
                {!accountsConfigured() && (
                  <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.sub }}>
                    Accounts are not switched on in this build. Your progress is
                    saved in this browser, and Save still writes it to a file you
                    can keep.
                  </p>
                )}

                {accountsConfigured() && !session && phase !== "sent" && (
                  <>
                    <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.sub, marginTop: 0 }}>
                      Sign in and your progress follows you to any device. Right
                      now it lives only in this browser — clearing it would clear
                      your work.
                    </p>
                    <form onSubmit={sendLink} style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}>
                      <input
                        type="email" required value={email} autoComplete="email"
                        onChange={(ev) => setEmail(ev.target.value)}
                        placeholder="you@example.com"
                        style={{
                          flex: "1 1 200px", minWidth: 0, padding: "10px 12px",
                          border: `1px solid ${T.hairline}`, borderRadius: 8,
                          font: `14px ${T.uiFont}`, color: T.ink, background: T.paper,
                        }}
                      />
                      <button type="submit" disabled={phase === "sending"} style={primary}>
                        {phase === "sending" ? "Sending…" : "Email me a link"}
                      </button>
                    </form>
                    <p style={{ ...quiet, marginTop: 10 }}>
                      No password. We email a link that signs you in on this device.
                    </p>
                  </>
                )}

                {phase === "sent" && !session && (
                  <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
                    Check <strong>{email}</strong>. The link signs you in on this
                    device — open it in this browser rather than another one.
                  </p>
                )}

                {session && (
                  <dl style={{ margin: "0 0 14px", font: `14px/1.7 ${T.uiFont}` }}>
                    <div style={{ display: "flex", gap: 10 }}>
                      <dt style={{ color: T.sub, minWidth: 96 }}>Signed in as</dt>
                      <dd style={{ margin: 0, wordBreak: "break-all" }}>{session.user.email}</dd>
                    </div>
                    <div style={{ display: "flex", gap: 10, marginTop: 4 }}>
                      <dt style={{ color: T.sub, minWidth: 96 }}>Progress</dt>
                      <dd style={{ margin: 0, color: phase === "syncing" ? T.sub : T.ok }}>
                        {phase === "syncing" ? "Syncing…" : "Saved to your account"}
                      </dd>
                    </div>
                  </dl>
                )}

                {note && (
                  <p role="status" style={{
                    font: `13px/1.6 ${T.uiFont}`, color: T.note,
                    background: T.noteBg, borderRadius: 8, padding: "10px 12px",
                  }}>{note}</p>
                )}

                {/* ————— Settings ————— */}
                {/* Both of these were only reachable from inside the grammar
                    module, which is a strange place for a preference to live. */}
                <h3 style={{ font: `600 13px ${T.uiFont}`, letterSpacing: ".4px",
                             color: T.sub, margin: "18px 0 8px" }}>SETTINGS</h3>
                {SETTINGS.map((s) => (
                  <div key={s.key} style={{ marginBottom: 12 }}>
                    <label htmlFor={`set-${s.key}`}
                           style={{ display: "block", font: `14px ${T.uiFont}`, marginBottom: 5 }}>
                      {s.label}
                    </label>
                    <select id={`set-${s.key}`} value={settings[s.key] ?? s.fallback}
                            onChange={(e) => changeSetting(s.key, e.target.value)}
                            style={{
                              width: "100%", padding: "9px 10px", borderRadius: 8,
                              border: `1px solid ${T.hairline}`, background: T.paper,
                              font: `14px ${T.uiFont}`, color: T.ink,
                            }}>
                      {s.options.map((o) => (
                        <option key={o.value} value={o.value}>{o.label}</option>
                      ))}
                    </select>
                  </div>
                ))}
                <p style={quiet}>
                  A change here applies the next time you open that section.
                </p>

                {/* ————— BACKUP —————
                    Save and Restore live HERE, together, as one thing a person
                    can name: a backup you take and a backup you put back.
                    They came out of the header in Session 24 (a pair of file
                    buttons above every lesson is a standing hint that the app
                    might lose your work) and were briefly split across two
                    screens, which was worse — a save on one screen and a
                    restore on another is not a feature, it is two loose ends.

                    NOT GATED ON BEING SIGNED IN, deliberately. A learner with
                    no account is exactly the one whose progress lives in a
                    single browser, and the file is the only thing standing
                    between them and a cleared cache.

                    The two Save buttons elsewhere — beside the sign-in conflict
                    choice below, and beside the reset confirm in Progress — are
                    shortcuts to this same download, offered at the two moments
                    something is about to be overwritten. This is where the way
                    BACK lives, for all three of them. */}
                <h3 style={{ font: `600 13px ${T.uiFont}`, letterSpacing: ".4px",
                             color: T.sub, margin: "18px 0 8px" }}>BACKUP</h3>
                <p style={{ ...quiet, marginTop: 0 }}>
                  {session
                    ? "Your account already keeps your progress across devices. A file is the extra copy you hold yourself."
                    : "Without an account your progress lives only in this browser. A file is the only copy that survives clearing it."}
                </p>
                <div style={{ display: "flex", gap: 8, flexWrap: "wrap", marginTop: 10 }}>
                  <button onClick={downloadProgress} style={ghost}>Save to a file</button>
                  <label style={{ ...ghost, display: "inline-block" }}>
                    Restore from a file
                    <input type="file" accept="application/json" onChange={restore}
                           style={{ display: "none" }} />
                  </label>
                </div>
                {fileMsg && (
                  <p role="status" style={{
                    font: `13px/1.6 ${T.uiFont}`, color: T.note, background: T.noteBg,
                    borderRadius: 8, padding: "10px 12px", marginTop: 10,
                  }}>{fileMsg}</p>
                )}

                {session && (
                  <>
                    <h3 style={{ font: `600 13px ${T.uiFont}`, letterSpacing: ".4px",
                                 color: T.sub, margin: "18px 0 8px" }}>THIS DEVICE</h3>
                    <button onClick={signOut} style={ghost}>Sign out</button>
                  </>
                )}
                {session && (
                  <p style={{ ...quiet, marginTop: 10 }}>
                    Signing out leaves this device's progress exactly where it is.
                  </p>
                )}
              </>
            )}

          </>
        )}

        {error && (
          <p role="alert" style={{
            font: `13px/1.6 ${T.uiFont}`, color: T.shu, marginTop: 12,
          }}>{error}</p>
        )}
      </div>
    </>
  );
}
