// ————— Autosave —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// ⚠️ THIS FILE IS ONE HALF OF A PAIR AND IS NOT SAFE ALONE. The other half is
// the authoritative load in account.jsx: once a device has joined an account,
// signing in pulls the account's copy down without asking. That is only
// tolerable because THIS file keeps the account continuously current. Ship the
// authoritative load without continuous saving and every load quietly discards
// whatever was done since the last sign-in. Read the header of sync.js before
// changing either.
//
// ————— WHY IT HANGS OFF THE SINGLE SETTER —————
//
// Every module writes progress through `window.storage.set`, which is
// storage.js's `storage.set`. Thirteen keys, one write path. The alternative —
// a save call at each interesting moment inside each module — is exactly how
// `tsumiki-n5-progress-v1` went missing from the export list for twelve days:
// a list of places that has to be kept in step with a codebase, maintained by
// remembering. A write IS the event. Nothing has to remember to announce it.
//
// So there is no list of save points here, and there should never be one. What
// there IS is a small list of keys whose write means a durable milestone just
// happened (a checker submission, a grammar lesson or checkpoint finishing),
// and those shorten the timer rather than adding a second mechanism.
//
// ————— ⚠️ THE GATE, AND WHY IT IS A FLAG AND NOT A SIZE CHECK —————
//
// A push must never run before this device's local state is the account's
// state. On a normal load that is a real window: account.jsx reads local,
// fetches the account, settles the two and writes the result back. A module
// that saves inside that window would push a document that predates the pull —
// thin where the account is full — and the account would take it.
//
// The tempting guard is "refuse a push that is much smaller than the account".
// Do not write it. A heuristic that judges size cannot tell a stale push from a
// learner who reset one section, and a guard that refuses real work gets
// switched off — at which point it is not a guard. `wouldWipeRemote` in sync.js
// says the same thing about itself and is deliberately narrow for the same
// reason.
//
// The honest statement is not about size, it is about ORDER: has the load
// finished? That is a fact this app knows for certain, so it is recorded as a
// fact. `ready` is false until account.jsx calls armAutosave() with a settled
// document, and false again the moment the learner signs out. While it is
// false, writes are remembered (`dirty` stays set) and nothing is sent.

// How long the learner has to stop writing before a save goes out. Short
// enough that a tab closed a few seconds later has already been saved, long
// enough that a burst of writes inside one interaction is one request.
const IDLE_MS = 3000;

// A ceiling, so continuous activity still saves. Without it a module that
// writes every second would reset the idle timer forever and never save at all.
const MAX_MS = 15000;

// Milestone keys (below) still coalesce — a lesson ending writes several keys in
// quick succession and that is one save, not four.
const BOUNDARY_MS = 300;

// ⚠️ NOT a list of save points. Every key saves; these save SOONER, because a
// write to one of them is a thing the learner would be upset to lose — the
// sentence they just had checked, the lesson they just finished. Adding to this
// list changes latency. Removing from it does not lose anything.
const BOUNDARY_KEYS = new Set([
  "tsumiki-checker-history-v1",      // a checker submission
  "tsumiki-n5-progress-v1",          // a grammar lesson or checkpoint finished
  "tsumiki-achievement-points-v1",   // koban awarded — the end of something
]);

let client = null;          // supabase client; null means "cannot push"
let userId = null;
let ready = false;          // THE GATE — see the note above
let dirty = false;          // a KEYS write has happened that no push has covered
let writeSeq = 0;           // bumped per write, so a push knows if it raced one
let lastPushed = null;      // canonical form of the document last sent
let idleAt = 0;             // "learner has stopped writing" — restarted by each write
let soonAt = 0;             // a milestone's earlier claim, which a later write cannot push back
let maxAt = 0;              // the ceiling, so a stream of writes still saves
let timer = null;
let chain = Promise.resolve();
let listening = false;

const now = () => Date.now();
const hidden = () =>
  typeof document !== "undefined" && document.visibilityState === "hidden";

// ————— the modules the push needs, loaded ONCE and early —————
//
// ⚠️ NOT `await import(...)` INSIDE THE FLUSH. Resolving a module is a real
// async operation, and the flush that matters most is the one that starts as
// the page is being discarded — where waiting on the module loader before even
// beginning the request is how the request does not get made. Found by
// test-autosave.py: the hide flush completed several tests later, by which time
// the session it meant to use was gone.
//
// They are still dynamic rather than static imports, because storage.js imports
// THIS file: a static `import "./sync.js"` here would close a cycle
// (storage -> autosave -> sync -> storage) and make module evaluation order
// load-bearing. Warmed at arm time instead, which is the moment we learn a push
// will eventually be wanted.
let modsP = null;
function modules() {
  if (!modsP) {
    modsP = Promise.all([
      import("./sync.js"), import("./storage.js"), import("./supabase.js"),
    ]).then(([sync, storage, sb]) => ({ sync, storage, sb }))
      .catch((e) => { modsP = null; throw e; });
  }
  return modsP;
}

function clearTimer() {
  if (timer !== null) { clearTimeout(timer); timer = null; }
  idleAt = 0; soonAt = 0; maxAt = 0;
}

function retime() {
  const claims = [idleAt, soonAt, maxAt].filter(Boolean);
  if (!claims.length) return;   // nothing has asked for a save; Math.min() of nothing is Infinity
  const at = Math.min(...claims);
  if (timer !== null) clearTimeout(timer);
  timer = setTimeout(() => { timer = null; idleAt = 0; soonAt = 0; maxAt = 0; flush("debounce"); },
                     Math.max(0, at - now()));
}

// ————— the one entry point from the write path —————
// storage.js calls this AFTER a successful set, and only for keys in KEYS —
// a stray key that no module owns can never reach an account, so it must not
// be able to schedule a request either.
export function noteWrite(key) {
  dirty = true;
  writeSeq++;

  // ⚠️ A WRITE WHILE THE PAGE IS HIDDEN GOES NOW, NOT IN THREE SECONDS.
  // This is not an optimisation, it is an ordering fix. App.jsx's own
  // visibilitychange handler (commitIfWorked) writes recency and engagement
  // keys when the page hides, and it registers its listener AFTER this module
  // installs its own — so the flush below would otherwise run first and miss
  // exactly the writes the hide caused.
  if (hidden()) { flush("write-while-hidden"); return; }

  // An ordinary write RESTARTS the idle wait: a burst inside one interaction is
  // one request. A milestone write also claims an earlier deadline, and a later
  // ordinary write cannot push that deadline back — otherwise finishing a
  // lesson and then typing would delay the save of the thing that was finished.
  idleAt = now() + IDLE_MS;
  if (BOUNDARY_KEYS.has(key)) {
    const soon = now() + BOUNDARY_MS;
    soonAt = soonAt ? Math.min(soonAt, soon) : soon;
  }
  if (!maxAt) maxAt = now() + MAX_MS;
  retime();
}

// Told to us by every push in the app, from pushRemote itself, so that the
// "has anything changed since the last push?" question has ONE answer whoever
// did the pushing — the sign-in settle, a conflict choice, a reset, or us.
// Deliberately does NOT clear `dirty`: only a flush that has compared the
// document may decide there is nothing left to send.
export function notePushed(canonical) {
  lastPushed = canonical;
}

// ⚠️ TWO CALLS, AND THE SPLIT IS THE GUARD. Knowing WHO we would push as and
// being ALLOWED to push are different facts, and they become true at different
// moments — the session exists as soon as the page loads, the load settles a
// round trip later. Collapsing them into one call makes the gate a restatement
// of "is there a client", which is not a guard at all: it cannot be removed
// without also removing the ability to push, so nothing can ever test it.
//
// That is not hypothetical. This file's first version DID collapse them, and
// test-autosave.py --self-check caught it: with the gate deleted the assertions
// still passed, because a push with no client throws before it reaches the
// network and an assertion counting requests cannot tell the two apart.
//
// Called at the START of the load: from here we know who we are, and we are
// still not allowed to send anything.
export function autosaveSession(c, uid) {
  client = c || null;
  userId = uid || null;
  install();
  if (client && userId) modules().catch(() => {});   // warm the loader, not the network
}

// Called when — and only when — this device's local state IS the account's
// state: after a clean first-sign-in merge, after a conflict has been settled,
// and after an authoritative load. `settledCanonical` is the canonical form of
// what the account now holds, so the first idle push after arming does not
// re-send a document the server already has.
//
// If the load FAILS this is never called, and this session saves nothing to the
// account — deliberately, because a device that could not read the account has
// no business writing to it. The local write still happened, and account.jsx
// says so in words rather than leaving it to be discovered.
export function armAutosave(settledCanonical) {
  lastPushed = settledCanonical ?? null;
  ready = true;
  install();
  if (client && userId) modules().catch(() => {});
  // Writes that happened during the load window were remembered, not lost.
  if (dirty) { soonAt = now() + BOUNDARY_MS; maxAt = now() + MAX_MS; retime(); }
}

// Sign-out, or accounts not configured. Nothing pending is sent afterwards —
// the caller flushes FIRST if it wants the last state saved (account.jsx does).
export function disarmAutosave() {
  clearTimer();
  client = null; userId = null; ready = false; dirty = false; lastPushed = null;
}

export function autosaveState() {
  return { ready, dirty, armed: Boolean(client && userId), pending: timer !== null };
}

// Test seam, and nothing else uses it: the fixtures need to know when the push
// chain has actually finished, because a flush is fire-and-forget by design.
export function autosaveSettled() { return chain; }

// ————— the push —————
// Returns a short reason string rather than throwing. A failed autosave must
// never reach the learner as an error: they did not ask for it, the local write
// already succeeded, and the next flush retries.
export function flush(reason = "manual") {
  clearTimer();
  chain = chain.then(() => run(reason)).catch(() => {});
  return chain;
}

// Exported under a plainer name for the two places that mean "now, before
// something irreversible": signing out, and restoring from a file.
export const flushNow = flush;

async function run(reason) {
  if (!dirty) return "clean";
  // THE GATE. Note that `dirty` survives: a write made before the load
  // finished is saved by the first flush after arming, not dropped.
  if (!ready || !client || !userId) return "not-ready";

  const seq = writeSeq;
  let m;
  try { m = await modules(); } catch { return "no-module"; }
  const { sync, storage, sb } = m;

  const map = sync.readLocal();
  const canonical = sync.canonDoc(map, storage.KEYS);
  if (canonical === lastPushed) {
    // Nothing has actually changed. Say so and send nothing: a load that
    // changed nothing must cost a GET and no POST.
    if (seq === writeSeq) dirty = false;
    return "unchanged";
  }

  try {
    const urgent = reason === "hide" || reason === "write-while-hidden";
    if (urgent) {
      // A push started as the page goes away needs `keepalive`, or the browser
      // is free to cancel it — see supabase.js. Scoped to this one request.
      sb.beginUrgentWrites();
      try { await sync.pushRemote(client, userId, map); }
      finally { sb.endUrgentWrites(); }
    } else {
      await sync.pushRemote(client, userId, map);
    }
    // pushRemote calls notePushed for us; only the flush may clear `dirty`,
    // and only if no write slipped in while the request was in the air.
    if (seq === writeSeq) dirty = false;
    return "pushed";
  } catch (e) {
    if (e?.code === "would_wipe") {
      // With the gate above this should be unreachable. If it is reached the
      // gate is wrong, and retrying forever would bury the evidence in noise.
      console.warn("autosave refused: " + e.message);
      if (seq === writeSeq) dirty = false;
      return "would-wipe";
    }
    // Offline, expired token, anything else: keep `dirty` and try again at the
    // next write or the next hide. Nothing local was touched.
    console.warn("autosave failed, will retry: " + (e?.message || String(e)));
    return "failed";
  }
}

// ————— losing the page —————
// visibilitychange -> hidden and pagehide are the only signals iOS Safari
// reliably gives before a tab is frozen or discarded; `beforeunload` is not
// fired there at all. Both are registered because they fire in different
// situations (switching apps vs closing the tab) and neither is a superset.
function install() {
  if (listening || typeof document === "undefined" || typeof window === "undefined") return;
  listening = true;
  const onHide = () => { if (hidden()) flush("hide"); };
  document.addEventListener("visibilitychange", onHide);
  window.addEventListener("pagehide", () => flush("hide"));
}
