// ————— Welcome back, and Goals: two screens over the engagement module —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// Three jobs that do not belong in the authoring module:
//   1. carry the scoped stylesheet that stands in for the Tailwind the module
//      is written in (see build-vite-app.py's engagement section for why)
//   2. tell it which modules the learner has actually unlocked
//   3. forward the host app's study signal into reportActivity
//
// ⚠️ IT IS NO LONGER A DIALOG (Lloyd, Oct 7 2026). Session 23 moved the goals
// off Home into a dialog that opened itself once a day; that dialog carried the
// proverb, the weekly rhythm and the quest chain at once, and it was too big
// and too intrusive — and it met brand-new learners on their first day, who
// have no rhythm and nothing to come back to. It is now two screens:
//
//   WelcomeBack — once a day, in place of Home, ONLY for a learner who studied
//                 on an earlier day. The saying, and two buttons: "Check your
//                 goals" and "About this saying", which reveals its meaning in
//                 place. A quiet link goes straight to Home.
//   GoalsScreen — the rhythm and the quests, a destination like Progress,
//                 reached from the welcome-back screen or Home's Goals button.
//
// What Session 23 got right still holds: the saying is meant to be READ, so it
// is shown once a day as an occasion and is never furniture on Home.
//
// Lazy, so a learner who never sees either screen does not pay for the quote
// bank — it is the largest thing Home can pull in by some margin.

import { useState, useEffect, useCallback, lazy, Suspense } from "react";
import { ENGAGEMENT_CSS } from "./engagementStyles.js";
import { onStudy } from "./activity.js";
import { storage } from "./storage.js";
import { T } from "./tokens.js";

const EngagementModule = lazy(() => import("../modules/Engagement.jsx"));

// UI state, not progress: which day this device last showed the welcome-back
// screen. Local date, matching the engagement module's own clock — a personal
// rhythm wants the learner's midnight, not UTC's. The key keeps its old name
// so a learner who saw the old dialog today is not shown the new screen too.
const SEEN_KEY = "tsumiki-goals-seen";
export const localDay = (d = new Date()) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;

// ⚠️ "RETURNING" IS DECIDED BY WORK ON AN EARLIER DAY, not by having started
// something. Session 23's gate was "anything started", which is true minutes
// into a learner's very first session — so the old dialog opened over Home the
// first time they came back from their first lesson. `recency` is
// stats.js's per-section record of when real work happened (written only when
// a module's store changed), so an earlier day in it means they have been here
// before and done something.
export function isReturning(recency, today = localDay()) {
  return Object.values(recency || {}).some((iso) => {
    const d = new Date(iso);
    return !Number.isNaN(d.getTime()) && localDay(d) < today;
  });
}

// Due today? Marks it seen as it answers yes, so a second visit to Home today
// goes straight to Home. A blocked store just means it shows again tomorrow.
export async function claimWelcomeBack(recency) {
  const today = localDay();
  if (!isReturning(recency, today)) return false;
  try {
    const r = await storage.get(SEEN_KEY);
    if (r?.value === today) return false;
    await storage.set(SEEN_KEY, today);
  } catch { return false; }
  return true;
}

const unlockedFrom = (startedMap) => {
  const anyStarted = Object.values(startedMap || {}).some(Boolean);
  return {
    // WHICH DOORS ARE OPEN. The module treats `unlocked` as read-only truth
    // owned by someone else — §5, "one store per concern" — and Home has
    // already read exactly this.
    hiragana: Boolean(startedMap?.hiragana),
    katakana: Boolean(startedMap?.katakana),
    kanji: Boolean(startedMap?.kanji),
    vocab: Boolean(startedMap?.vocabulary),
    grammar: Boolean(startedMap?.grammar),
    // The checker stores no progress of its own kind, so gating it on itself
    // would keep it out of every chain forever; it is the one door with no
    // prerequisite.
    checker: anyStarted,
  };
};

// Whichever screen mounts the module drains the study reports held for it
// (lib/activity.js queues them, through a reload, until something listens).
function useEngagementWiring() {
  const [api, setApi] = useState(null);
  // A stable identity: the module calls this from an effect keyed on it, so a
  // new function every render would loop.
  const onApi = useCallback((a) => setApi(a), []);
  useEffect(() => {
    if (!api?.reportActivity) return undefined;
    return onStudy((moduleId) => api.reportActivity(moduleId));
  }, [api]);
  return onApi;
}

// The module is authored with its own grey ground and padding; on these
// screens it sits on the tatami like everything else.
// Two classes, so it outranks the scoped `.eng-scope .bg-stone-100` / `.p-4` rules.
// And its cards are drawn as washi: the quote card's own gradient starts
// transparent, which on tatami — at dusk especially — washed the saying out.
const GROUND = `.eng-scope.eng-host > div{background:transparent;padding:0}`
  + `\n.eng-scope.eng-host .rounded-xl{background:var(--ts-washi);box-shadow:0 3px 0 var(--ts-washi-lip),0 10px 22px var(--ts-card-shadow),var(--ts-washi-halo)}`;

function Engagement(props) {
  const onApi = useEngagementWiring();
  return (
    <div className="eng-scope eng-host">
      <style>{ENGAGEMENT_CSS + "\n" + GROUND}</style>
      <Suspense fallback={
        <p style={{ padding: "24px 4px", color: "var(--ts-on-tatami)", font: `0.875rem ${T.uiFont}` }}>Loading…</p>
      }>
        <EngagementModule
          // ⚠️ EXPLICIT ZEROES, NOT THE DEFAULT. The module defaults `due` to
          // { kanji: 6, … } — a demo value that makes the chain open with
          // "clear your kanji reviews" whether or not any review is due.
          // Nothing computes real due counts outside the modules that own them
          // yet, so the honest input is zero. Wire real counts here when a
          // module exposes them; do not restore the default by omitting it.
          due={{ kanji: 0, vocab: 0, grammar: 0 }}
          devTools={false}
          onApi={onApi}
          {...props}
        />
      </Suspense>
    </div>
  );
}

const LABEL = { font: `700 0.6875rem ${T.uiFont}`, letterSpacing: ".08em", color: "var(--ts-on-tatami)" };

export function WelcomeBack({ startedMap, openGoals, toHome }) {
  const [about, setAbout] = useState(false);
  return (
    <div style={{ display: "flex", flexDirection: "column", gap: 14, padding: "20px 16px 28px" }}>
      <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
        <span style={LABEL}>WELCOME BACK</span>
        <span lang="ja" style={{ font: `1.125rem ${T.jpFont}`, color: "var(--ts-on-tatami)" }}>おかえり</span>
      </div>

      <Engagement unlocked={unlockedFrom(startedMap)} parts={["quote"]} quoteDetails={about} />

      {/* The one lacquer button is the thing to do next; the saying's meaning
          is a wood button because it is an aside, not a step. */}
      <button className="ts-btn ts-btn-shu" onClick={openGoals}>Check your goals</button>
      <button className="ts-btn ts-btn-wood" onClick={() => setAbout((a) => !a)} aria-expanded={about}>
        {about ? "Hide what it means" : "About this saying"}
      </button>
      <button className="ts-link" style={{ alignSelf: "center" }} onClick={toHome}>Go to Home</button>
    </div>
  );
}

export default function GoalsScreen({ startedMap }) {
  // Session 34 — the other way to keep the week: practice visits on words the
  // learner sent from the dictionary. READ from the two stores that own the
  // facts (the dictionary's list, the vocabulary module's log), never recorded
  // a second time. A visit counts only if it happened AFTER the word was sent,
  // so a bank word someone had already practised does not arrive pre-counted.
  // null (not []) while no word has ever been sent, which hides the line.
  const [ownVisits, setOwnVisits] = useState(null);
  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        const [m, v] = await Promise.all([storage.get("tsumiki-my-words-v1"), storage.get("tsumiki-known-words-v1")]);
        const mine = m ? JSON.parse(m.value) : [];
        const prog = v ? JSON.parse(v.value) : {};
        if (!Array.isArray(mine) || !mine.length) { if (alive) setOwnVisits(null); return; }
        const ts = [];
        for (const w of mine) {
          for (const l of (prog[w.w]?.log || [])) {
            if (l && l.t >= (w.at || 0) && l.via !== "unlearned") ts.push(l.t);
          }
        }
        if (alive) setOwnVisits(ts);
      } catch { if (alive) setOwnVisits(null); }
    })();
    return () => { alive = false; };
  }, []);

  return (
    <div style={{ padding: "20px 16px 28px" }}>
      <Engagement unlocked={unlockedFrom(startedMap)} parts={["rhythm", "quests"]} ownVisits={ownVisits} />
    </div>
  );
}
