// ————— Goals: the daily card, the weekly rhythm, the quest chain —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// Three jobs that do not belong in the authoring module:
//   1. carry the scoped stylesheet that stands in for the Tailwind the module
//      is written in (see build-vite-app.py's engagement section for why)
//   2. tell it which modules the learner has actually unlocked
//   3. forward the host app's study signal into reportActivity
//
// ⚠️ IT IS A DIALOG, NOT A PANEL ON HOME (Lloyd, Session 23). It was inline
// under the hero, which meant a learner scrolled past the proverb every single
// time they opened the app to reach the thing they came for. A card you scroll
// past is a card you stop reading, which is the same failure the v2 "unlock the
// proverb" design had from the other direction: the quote is meant to be READ.
//
// So it shows ONCE A DAY, unbidden, and is reachable any time afterwards from
// the Goals button. Showing it once is what makes it an occasion; showing it
// every time is what made it furniture.
//
// Lazy, so a learner who never opens it does not pay for the quote bank — it is
// the largest thing Home can pull in by some margin.

import { useState, useEffect, useCallback, lazy, Suspense } from "react";
import { ENGAGEMENT_CSS } from "./engagementStyles.js";
import { onStudy } from "./activity.js";
import { storage } from "./storage.js";
import { T } from "./tokens.js";

const EngagementModule = lazy(() => import("../modules/Engagement.jsx"));

// UI state, not progress: which day this device last showed the card. Local
// date, matching the engagement module's own clock — a personal rhythm wants
// the learner's midnight, not UTC's.
const SEEN_KEY = "tsumiki-goals-seen";
const localDay = (d = new Date()) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;

export default function GoalsDialog({ open, setOpen, startedMap }) {
  const [api, setApi] = useState(null);

  // A stable identity: the module calls this from an effect keyed on it, so a
  // new function every render would loop.
  const onApi = useCallback((a) => setApi(a), []);

  useEffect(() => {
    if (!api?.reportActivity) return undefined;
    return onStudy((moduleId) => api.reportActivity(moduleId));
  }, [api]);

  const anyStarted = Object.values(startedMap || {}).some(Boolean);

  // ————— once a day, on the way in —————
  // Deliberately gated on having started something. A learner on their first
  // visit has no rhythm to report and no quests to run; opening a goals dialog
  // over the top of "start with hiragana" would be noise in front of the one
  // instruction that matters.
  useEffect(() => {
    if (!anyStarted) return;
    let alive = true;
    (async () => {
      try {
        const r = await storage.get(SEEN_KEY);
        if (!alive || r?.value === localDay()) return;
        await storage.set(SEEN_KEY, localDay());
        if (alive) setOpen(true);
      } catch { /* a blocked store just means it opens again tomorrow */ }
    })();
    return () => { alive = false; };
  }, [anyStarted, setOpen]);

  if (!open) return null;

  return (
    <>
      <div onClick={() => setOpen(false)} aria-hidden="true" style={{
        position: "fixed", inset: 0, zIndex: 30, background: "rgba(34,37,43,0.44)",
      }} />
      <div role="dialog" aria-modal="true" aria-label="Goals" style={{
        position: "fixed", zIndex: 31, left: "50%", top: "50%",
        transform: "translate(-50%,-50%)", width: "min(94vw, 480px)",
        maxHeight: "88vh", overflowY: "auto",
        background: T.sheet, border: `1px solid ${T.hairline}`, borderRadius: 10,
        padding: "14px 14px 18px", fontFamily: T.uiFont, color: T.ink,
      }}>
        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
          <h2 style={{ font: `600 17px ${T.uiFont}`, margin: 0 }}>Goals</h2>
          <button onClick={() => setOpen(false)} aria-label="Close" style={{
            background: "none", border: "none", cursor: "pointer",
            padding: 8, font: `16px ${T.uiFont}`, color: T.sub,
          }}>✕</button>
        </div>

        <div className="eng-scope">
          <style>{ENGAGEMENT_CSS}</style>
          <Suspense fallback={
            <p style={{ padding: "24px 4px", color: T.sub, font: `14px ${T.uiFont}` }}>Loading…</p>
          }>
            <EngagementModule
              unlocked={{
                // WHICH DOORS ARE OPEN. The module treats `unlocked` as
                // read-only truth owned by someone else — §5, "one store per
                // concern" — and Home has already read exactly this.
                hiragana: Boolean(startedMap?.hiragana),
                katakana: Boolean(startedMap?.katakana),
                kanji: Boolean(startedMap?.kanji),
                vocab: Boolean(startedMap?.vocabulary),
                grammar: Boolean(startedMap?.grammar),
                // The checker stores no progress, so it can never appear in
                // startedMap. Gating it on itself would keep it out of every
                // chain forever; it is the one door with no prerequisite.
                checker: anyStarted,
              }}
              // ⚠️ EXPLICIT ZEROES, NOT THE DEFAULT. The module defaults `due`
              // to { kanji: 6, … } — a demo value that makes the chain open
              // with "clear your kanji reviews" whether or not any review is
              // due. Nothing computes real due counts outside the modules that
              // own them yet, so the honest input is zero. Wire real counts
              // here when a module exposes them; do not restore the default by
              // omitting the prop.
              due={{ kanji: 0, vocab: 0, grammar: 0 }}
              devTools={false}
              onApi={onApi}
            />
          </Suspense>
        </div>
      </div>
    </>
  );
}
