// ————— Error history —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// The record behind the sentence at the top of checker-module.jsx: "your
// particle errors are down forty percent since May" instead of correcting the
// same mistake forever — and, since Lloyd's decision below, the learner's own
// back catalogue of what they wrote and what came back.
//
// Full write-up: error-history-design-v1.md
//
// ⚠️ THIS IS THE FIRST LOG IN THE APP, AND THAT IS THE WHOLE MERGE DESIGN.
// Every other key is STATE — where the learner is. Two devices holding
// different state means one of them is behind, which is why sync.js asks. This
// is a LOG — what the learner did. Two devices holding different logs means
// BOTH ARE TRUE. Asking "which history do you want to keep?" has no right
// answer, and the wrong ones delete writing the learner actually did. So this
// key is UNIONED, never chosen between, and sync.js names it explicitly.
//
// ————— ⭐ WHAT IS STORED, AND THE DECISION THAT REVERSED —————
// v1 stored counts only. It deliberately withheld the learner's sentence and
// even the span, on the grounds that the checker is where someone writes the
// Japanese they are unsure about. LLOYD OVERRULED THAT, and the reasoning is
// better than mine was: a learner looking at "you make particle errors" with no
// examples has been given a label, not a lesson. The examples ARE the teaching.
// Withholding someone's own writing from them protects them from nobody.
//
// So a check is stored whole — the submission, every issue with its span,
// correction and explanation, the natural rewrite, the readings. Enough to
// re-render exactly what they saw, because a truncated record would make Review
// a worse version of the result screen instead of the same one.
//
// WHAT THAT OBLIGES, and none of it is optional:
//   · it syncs to the account, so it is covered by the same RLS as everything
//     else and lands in the archive on every replace
//   · it is in KEYS, so Save-to-file carries it and Restore brings it back
//   · the checker is a SECTION in stats.js, so a learner can DELETE it. That
//     mattered when this was counts; it matters far more now.

import { storage } from "./storage.js";

export const HISTORY_KEY = "tsumiki-checker-history-v1";

// ————— Budgets —————
// Two, because the store now holds two things with very different weights.
//
// The PATTERN LEDGER is a few dozen bytes per entry and is what trends are made
// of, so it is capped by count and kept long.
export const MAX_ENTRIES = 800;
// The CHECKS are the heavy half — a 600-character submission with a dozen
// explained issues runs to several KB. Capped by BYTES rather than by count,
// because the count says nothing about the weight: 300 haiku and 300 essays are
// the same number and a hundredfold apart in what they cost a sign-in.
//
// ⚠️ THE LEDGER OUTLIVES THE CHECKS ON PURPOSE. When an old check is dropped,
// its pattern entries stay, so "you have made this error 40 times since May"
// stays true after the earliest examples are gone. The UI says the sentence is
// no longer kept rather than pretending the error never happened.
//
// Raise these if learners are losing examples they wanted. The cost is paid at
// sign-in (the whole document is fetched and upserted), not on every page load.
export const MAX_CHECK_BYTES = 400_000;
export const MAX_CHECKS = 300;

// `_checks` is not a pattern. The leading underscore is load-bearing:
// countProgress() in stats.js skips keys beginning with "_", so the Progress
// section counts distinct PATTERNS MET and never counts this bucket as one.
export const CHECKS = "_checks";

const today = () => new Date().toISOString().slice(0, 10);

// Created once, on the device where the check happened, and never recomputed.
// NOT a hash of the content: a learner can genuinely make the same error twice
// in one day in one context, and those are two events. A content hash would
// merge them and undercount exactly the learner who most needs the count right.
//
// ⚠️ MUST NOT CONTAIN "#". A pattern entry's id is `<checkId>#<issueIndex>`,
// which is what lets the ledger point at its example without storing the link
// twice. base36 of a random and a timestamp cannot produce one.
function newId() {
  return Math.random().toString(36).slice(2, 10) + Date.now().toString(36).slice(-4);
}

export async function readHistory() {
  try {
    const r = await storage.get(HISTORY_KEY);
    const v = r ? JSON.parse(r.value) : {};
    return v && typeof v === "object" && !Array.isArray(v) ? v : {};
  } catch { return {}; }
}

async function writeHistory(map) {
  try { await storage.set(HISTORY_KEY, JSON.stringify(map)); }
  catch (e) { console.error("error history save failed", e); }
}

// ——— PURE CORE (extracted verbatim at run time by test-error-history.py) ———

// A pattern entry's id encodes the check it came from and which issue it was.
// Storing the link instead of duplicating it keeps the ledger — the half that
// has to survive longest — as light as it was when it held counts alone.
const refOf = (id) => String(id).split("#")[0];
const ixOf = (id) => Number(String(id).split("#")[1]);

// One graded check plus its result, folded into the map. Pure so the test can
// drive it without a browser.
//
// A check with NO issues still writes a _checks entry, and that is not
// bookkeeping. It is the only way a perfect sentence counts as work —
// App.jsx's commitIfWorked() uses "the store changed" as its evidence — and it
// is the DENOMINATOR: "eight particle errors in May, five in September" is not
// improvement if the learner also wrote half as much.
function foldCheck(map, { day, context, checkId, submitted, result }) {
  const out = { ...map };
  const push = (k, entry) => { out[k] = [...(out[k] || []), entry]; };
  const list = Array.isArray(result?.issues) ? result.issues : [];

  // Stored whole, so Review can re-render what the learner saw rather than a
  // summary of it. Field names are short because this is the heavy half; the
  // shape is documented in error-history-design-v1.md §2.
  push(CHECKS, {
    id: checkId,
    d: day,
    c: context,
    text: String(submitted ?? ""),
    verdict: result?.verdict ?? null,
    score: result?.overall?.natural_score ?? null,
    summary: result?.overall?.summary ?? null,
    rewrite: result?.model_rewrite ?? null,
    readings: Array.isArray(result?.readings) ? result.readings : [],
    n: list.length,
    issues: list.map((x) => ({
      t: x?.type || "note",
      p: typeof x?.pattern_name === "string" ? x.pattern_name.trim() : "",
      span: x?.span ?? "",
      corr: x?.correction ?? null,
      exp: x?.explanation ?? "",
      start: Number.isFinite(x?.start) ? x.start : null,
      end: Number.isFinite(x?.end) ? x.end : null,
      loc: !!x?.located,
    })),
  });

  list.forEach((issue, i) => {
    // An issue with no pattern_name is not filed under a made-up one. It is
    // still in the check's own `issues` and still counts toward `n`, so the
    // example survives and the denominator stays honest — only the ledger,
    // which is indexed BY pattern, has nothing to file it under.
    const p = typeof issue?.pattern_name === "string" ? issue.pattern_name.trim() : "";
    if (!p || p.startsWith("_")) return;
    push(p, { d: day, c: context, t: issue.type || "note", id: `${checkId}#${i}` });
  });

  return trim(out);
}

// Union by entry id. THE TWO PROPERTIES THAT MAKE THE SYNC EXEMPTION VALID, and
// that test-error-history.py asserts rather than assumes:
//   union(A, B) deep-equals union(B, A)     — order-independent
//   union(A, A) deep-equals A               — idempotent
// If either fails this is not a union, and the "never ask" exemption in sync.js
// is unearned.
function unionHistory(a, b) {
  const out = {};
  for (const src of [a || {}, b || {}]) {
    if (!src || typeof src !== "object" || Array.isArray(src)) continue;
    for (const [k, list] of Object.entries(src)) {
      if (!Array.isArray(list)) continue;
      const seen = out[k] || (out[k] = new Map());
      for (const e of list) {
        if (e && typeof e === "object" && e.id != null && !seen.has(e.id)) seen.set(e.id, e);
      }
    }
  }
  const merged = {};
  for (const [k, seen] of Object.entries(out)) merged[k] = [...seen.values()];
  return trim(merged);
}

// ⚠️ TRIM RUNS AFTER THE UNION, NEVER BEFORE. Trim each side first and the
// result depends on which device happened to be fuller — the union stops being
// order-independent, and order-independence is the entire reason this key is
// allowed to merge without asking. Sorting by (day, id) rather than by day
// alone is the same requirement: ties must break the same way on both devices,
// and `id` is the only field guaranteed to differ.
function trim(map) {
  const out = {};

  // The heavy half, by bytes. Newest kept. Measured per entry rather than by
  // stringifying the whole array each round, because that is quadratic and this
  // runs on every check.
  const checks = order([...(map[CHECKS] || [])]);
  const kept = [];
  let bytes = 0;
  for (let i = checks.length - 1; i >= 0; i--) {
    const size = JSON.stringify(checks[i]).length;
    if (kept.length >= MAX_CHECKS || bytes + size > MAX_CHECK_BYTES) break;
    bytes += size;
    kept.push(checks[i]);
  }
  if (kept.length) out[CHECKS] = kept.reverse();

  // The light half, by count.
  const flat = [];
  for (const [k, list] of Object.entries(map)) {
    if (k === CHECKS || !Array.isArray(list)) continue;
    for (const e of list) flat.push([k, e]);
  }
  const ledger = flat.length <= MAX_ENTRIES
    ? flat
    : flat.sort((x, y) => cmp(x[1], y[1])).slice(flat.length - MAX_ENTRIES);
  const byKey = {};
  for (const [k, e] of ledger) (byKey[k] || (byKey[k] = [])).push(e);

  const sorted = {};
  for (const k of Object.keys(out).concat(Object.keys(byKey)).sort()) {
    sorted[k] = order(k === CHECKS ? out[k] : byKey[k]);
  }
  return sorted;
}

const cmp = (x, y) => String(x.d).localeCompare(String(y.d)) || String(x.id).localeCompare(String(y.id));
const order = (list) => [...(list || [])].sort(cmp);

// ⭐ THE VIEW LLOYD ASKED FOR: grouped by error type, and a sentence with three
// kinds of error appears under all three. That repetition is the point — a
// learner looking for "what do I keep doing with particles" should find their
// own particle sentences there, not be sent to a chronological list to hunt.
//
// Newest first inside a group, most frequent group first. A pattern whose
// examples have aged past the byte budget still appears, with its count intact
// and `missing` saying how many sentences are no longer kept — the alternative
// is a group that silently shrinks and makes the learner think the error
// stopped happening.
function byErrorType(map, { since = null, until = null } = {}) {
  const inRange = (e) => (!since || e.d >= since) && (!until || e.d <= until);
  const checks = new Map((map?.[CHECKS] || []).map((c) => [c.id, c]));
  const groups = [];

  for (const [pattern, list] of Object.entries(map || {})) {
    if (pattern === CHECKS || !Array.isArray(list)) continue;
    const hits = list.filter(inRange);
    if (!hits.length) continue;

    const examples = [];
    let missing = 0;
    for (const e of [...hits].reverse()) {
      const check = checks.get(refOf(e.id));
      if (!check) { missing++; continue; }
      const ix = ixOf(e.id);
      examples.push({
        entry: e, check, ix,
        issue: Number.isFinite(ix) ? check.issues?.[ix] ?? null : null,
      });
    }

    const tiers = {};
    for (const e of hits) tiers[e.t] = (tiers[e.t] || 0) + 1;
    groups.push({
      pattern,
      total: hits.length,
      errors: hits.filter((e) => e.t === "fix" || e.t === "unnatural").length,
      notes: hits.filter((e) => e.t === "note").length,
      // The tier a learner would call this: the one it comes back as most
      // often. Reporting a pattern as a "note" because one of forty was is how
      // a real problem gets a soft label.
      tier: Object.entries(tiers).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))[0][0],
      last: hits.reduce((m, e) => (e.d > m ? e.d : m), ""),
      examples, missing,
    });
  }

  return groups.sort((a, b) => b.total - a.total || a.pattern.localeCompare(b.pattern));
}

// Every check, newest first — the chronological view, for "what did I write
// last week". byErrorType is the default because it answers a question the
// learner actually has; this answers a different one and both are cheap.
function recentChecks(map, limit = 50) {
  return [...(map?.[CHECKS] || [])].reverse().slice(0, limit);
}

// ——— END PURE CORE ———

/**
 * Record one graded check. Called by the checker after a result arrives, and
 * never on an error — a check that failed to reach the backend is not evidence
 * about anyone's Japanese.
 */
export async function recordCheck(context, submitted, result) {
  const next = foldCheck(await readHistory(), {
    day: today(), context: String(context || "polite"),
    checkId: newId(), submitted, result: result || {},
  });
  await writeHistory(next);
  return next;
}

/**
 * Counts per pattern over a window, with the denominator alongside them.
 *
 * ⚠️ THE DENOMINATOR IS NOT OPTIONAL AND IS NOT COSMETIC. "Eight particle
 * errors in May, five in September" is not improvement if the learner also
 * wrote half as much. Any caller that renders `patterns` without `checks` is
 * reporting a trend it has not measured.
 *
 * `notes` is kept apart from `errors` for the same class of reason: a "worth
 * knowing" note is not a mistake, and folding it in would show a learner who is
 * being told more interesting things as a learner who is getting worse.
 */
export function summarise(map, { since = null, until = null } = {}) {
  const inRange = (e) => (!since || e.d >= since) && (!until || e.d <= until);
  const checks = (map?.[CHECKS] || []).filter(inRange);
  const patterns = {};
  for (const [k, list] of Object.entries(map || {})) {
    if (k === CHECKS || !Array.isArray(list)) continue;
    const hits = list.filter(inRange);
    if (!hits.length) continue;
    patterns[k] = {
      total: hits.length,
      errors: hits.filter((e) => e.t === "fix" || e.t === "unnatural").length,
      notes: hits.filter((e) => e.t === "note").length,
      last: hits.reduce((m, e) => (e.d > m ? e.d : m), ""),
    };
  }
  return { checks: checks.length, issues: checks.reduce((n, e) => n + (e.n || 0), 0), patterns };
}

export { foldCheck, unionHistory, trim, byErrorType, recentChecks, refOf, ixOf };
