// ————— How the room/shop keys merge across devices —————
// HAND-MAINTAINED. Not generated by build-vite-app.py. Pure functions, no
// imports, so test-koban-merge.mjs can load this file directly.
//
// Rooms, Garden & Avatar design (Notion, Sep 10 2026) §3 splits the room's
// state into keys by HOW THEY MERGE, not by subject, so that "your whole room"
// is never the thing a learner is asked to choose between:
//
//   koban-ledger-v1  union by event id — never asks
//   room-owned-v1    union             — never asks
//   room-layout-v1   most recent wins  — no dialog
//   character-v1     most recent wins  — no dialog
//   garden-state-v1  most recent wins, growth kept at its highest
//   blocks-v1        union by block id — never asks (the journey's tower)
//
// sync.js registers each of these as a merger. A merger that returns null
// sends the key back to the ordinary ask-on-conflict path, and that is what
// every one of them does with a value it does not recognise: a shape we do not
// own is a question, not something to guess at.

const obj = (x) => x && typeof x === "object" && !Array.isArray(x);
const parse = (s) => { try { return JSON.parse(s); } catch { return undefined; } };
const canonEvent = (e) => JSON.stringify(Object.keys(e).sort().reduce((o, k) => { o[k] = e[k]; return o; }, {}));

// Two copies of one event id should not happen — ids are uuids, or fixed ids
// that mean the same payout everywhere. When they disagree anyway (the opening
// balance, migrated separately on two devices that held different old
// numbers), the larger amount wins: wrong toward keeping the learner's koban,
// which is the direction sync.js is wrong in everywhere else. Ties fall to the
// canonical text so that the choice does not depend on argument order.
function pickEvent(a, b) {
  if (a.d !== b.d) return Math.abs(a.d) >= Math.abs(b.d) ? a : b;
  return canonEvent(a) <= canonEvent(b) ? a : b;
}

export function unionLedger(l, r) {
  const a = parse(l), b = parse(r);
  if (!obj(a) || !obj(b) || !Array.isArray(a.events) || !Array.isArray(b.events)) return null;
  const byId = new Map();
  for (const e of [...a.events, ...b.events]) {
    if (!obj(e) || typeof e.id !== "string" || !Number.isFinite(e.d)) continue;
    byId.set(e.id, byId.has(e.id) ? pickEvent(byId.get(e.id), e) : e);
  }
  const events = [...byId.values()].sort((x, y) => (x.ts - y.ts) || (x.id < y.id ? -1 : x.id > y.id ? 1 : 0));
  return JSON.stringify({ v: 1, events });
}

// Owned items: { v: 1, ids: { itemId: firstOwnedAt } }. Owning is monotonic —
// nothing in the room is ever un-owned — so a union invents nothing and drops
// nothing. The earlier timestamp is kept for an item both sides own.
export function unionOwned(l, r) {
  const a = parse(l), b = parse(r);
  if (!obj(a) || !obj(b) || !obj(a.ids) || !obj(b.ids)) return null;
  const ids = { ...a.ids };
  for (const [k, t] of Object.entries(b.ids)) {
    ids[k] = ids[k] == null ? t : Math.min(Number(ids[k]) || 0, Number(t) || 0);
  }
  const sorted = Object.keys(ids).sort().reduce((o, k) => { o[k] = ids[k]; return o; }, {});
  return JSON.stringify({ v: 1, ids: sorted });
}

// Layout and character: the copy written later wins, by the `t` it carries.
// This is the one place a timestamp decides anything, and the design asks for
// it deliberately: these keys are low-stakes (where a cushion sits, a hair
// colour) and a dialog about them would teach the learner to dismiss dialogs.
// Equal stamps fall to the canonical text, for order independence.
export function newerOf(l, r) {
  const a = parse(l), b = parse(r);
  if (!obj(a) || !obj(b)) return null;
  const ta = Number(a.t) || 0, tb = Number(b.t) || 0;
  if (ta !== tb) return ta > tb ? l : r;
  return canonEvent(a) <= canonEvent(b) ? l : r;
}

// The garden: the newer copy wins for the shape and the sand, but growth is a
// high-water mark — it is counted from study days, and activeDays forgets
// after 120 days, so a newer copy carrying a LOWER count must not win it.
export function mergeGarden(l, r) {
  const base = newerOf(l, r);
  if (base == null) return null;
  const a = parse(l), b = parse(r), w = parse(base);
  const growth = Math.max(Number(a.growth) || 0, Number(b.growth) || 0);
  if ((Number(w.growth) || 0) === growth) return base;
  return JSON.stringify({ ...w, growth });
}

// Effort blocks (lib/blocks.js): { v, blocks:[{id, ts, ...}], built:{id: ts}, seeded:{source: ts} }.
// A LOG in the same sense as the koban ledger — every block has its own id, and
// a block is never removed, so two devices' copies are both true and union.
// Built structures and seeded sources are monotonic too; the earlier stamp wins.
// For one block id held twice, a CLEARED copy wins first: a Checker reset
// deleted that sentence, and a device that has not heard yet must not hand it
// back. Then a dated copy beats a backfilled one (it knows more), then the
// earlier stamp, then the canonical text, for order independence.
function pickBlock(a, b) {
  if (!!a.cleared !== !!b.cleared) return a.cleared ? a : b;
  if (!!a.bf !== !!b.bf) return a.bf ? b : a;
  if (a.ts !== b.ts) return a.ts < b.ts ? a : b;
  return canonEvent(a) <= canonEvent(b) ? a : b;
}
function unionStamps(x, y) {
  const out = { ...(obj(x) ? x : {}) };
  for (const [k, t] of Object.entries(obj(y) ? y : {})) {
    out[k] = out[k] == null ? t : Math.min(Number(out[k]) || 0, Number(t) || 0);
  }
  return Object.keys(out).sort().reduce((o, k) => { o[k] = out[k]; return o; }, {});
}
export function unionBlocks(l, r) {
  const a = parse(l), b = parse(r);
  if (!obj(a) || !obj(b) || !Array.isArray(a.blocks) || !Array.isArray(b.blocks)) return null;
  const byId = new Map();
  for (const e of [...a.blocks, ...b.blocks]) {
    if (!obj(e) || typeof e.id !== "string" || !Number.isFinite(e.ts)) continue;
    byId.set(e.id, byId.has(e.id) ? pickBlock(byId.get(e.id), e) : e);
  }
  const blocks = [...byId.values()].sort((x, y) => (x.ts - y.ts) || (x.id < y.id ? -1 : x.id > y.id ? 1 : 0));
  return JSON.stringify({ v: 1, blocks, built: unionStamps(a.built, b.built), seeded: unionStamps(a.seeded, b.seeded) });
}

export const ROOM_MERGERS = {
  "tsumiki-blocks-v1": unionBlocks,
  "tsumiki-koban-ledger-v1": unionLedger,
  "tsumiki-room-owned-v1": unionOwned,
  "tsumiki-room-layout-v1": newerOf,
  "tsumiki-character-v1": newerOf,
  "tsumiki-garden-state-v1": mergeGarden,
};
