// ————— Progress —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// A DESTINATION, not a dialog. This was a tab inside the Account modal until
// Session 24, and Lloyd moved it out. The drawer's own comment gives the reason
// in one line: "the drawer list answers 'where can I go', and an account is not
// a place." Progress IS a place — it is where a learner goes to see what they
// can do and to look back at their own work, and burying that behind a
// sign-in-shaped door made it look like account administration.
//
// ⚠️ THE RESET GOES THROUGH resetEverywhere(), NOT resetSections(). Clearing
// only the browser while signed in undoes itself on the next sign-in, silently
// and with a success message. The whole trap is written out in stats.js; the
// single entry point exists so this file and Account cannot drift on it.

import { useState, useEffect, useCallback } from "react";
import { T } from "./tokens.js";
import {
  SECTIONS, readSectionStats, readWallet, resetEverywhere,
  daysSinceLastWorked, DORMANT_DAYS,
} from "./stats.js";
import { storage, downloadProgress } from "./storage.js";
import { summarise, readHistory } from "./errorHistory.js";

const OPEN_REVIEW = "tsumiki-open-review";

const ghost = {
  background: "none", color: T.ink, border: `1px solid ${T.hairline}`,
  borderRadius: 8, padding: "10px 16px", cursor: "pointer",
  font: `14px ${T.uiFont}`,
};
const danger = {
  background: T.shu, color: T.sheet, border: "none", borderRadius: 8,
  padding: "10px 16px", cursor: "pointer", font: `600 14px ${T.uiFont}`,
};
const quiet = { font: `12px/1.6 ${T.uiFont}`, color: T.sub };
const h3 = {
  font: `600 13px ${T.uiFont}`, letterSpacing: ".4px", color: T.sub, margin: 0,
};

export default function Progress({ go }) {
  const [stats, setStats] = useState([]);
  const [wallet, setWallet] = useState(0);
  const [dormantDays, setDormantDays] = useState(null);
  const [checker, setChecker] = useState(null);
  const [picked, setPicked] = useState([]);
  const [confirming, setConfirming] = useState(false);
  const [resetMsg, setResetMsg] = useState(null);
  const [savedCopy, setSavedCopy] = useState(null);

  const refresh = useCallback(async () => {
    const [s, w, d, h] = await Promise.all([
      readSectionStats(), readWallet(), daysSinceLastWorked(), readHistory(),
    ]);
    setStats(s); setWallet(w); setDormantDays(d); setChecker(summarise(h));
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  // Sets the one-shot flag the checker reads on arrival, then navigates. The
  // flag is cleared by the reader, not by the writer — see the note at its
  // declaration in checker-module.jsx.
  const openReview = async () => {
    try { await storage.set(OPEN_REVIEW, "1"); } catch { /* navigate anyway */ }
    go("checker");
  };

  const doReset = async () => {
    setConfirming(false);
    setSavedCopy(null);
    const res = await resetEverywhere(picked);
    if (!res.ok) { setResetMsg(res.message); return; }
    setPicked([]);
    await refresh();
    setResetMsg(
      `Cleared ${res.sections.join(" and ")}` +
      (res.pushed ? ", on this device and in your account."
        : res.signedIn
          ? ", on this device — but your account could not be updated" +
            (res.error ? " (" + res.error + ")" : "") +
            ". Sign in again to retry, or it will come back."
          : ". You are not signed in, so this cleared this device only — if you " +
            "sign in later, progress saved to your account will come back.") +
      " Reload to see it."
    );
  };

  const started = stats.filter((s) => s.started);

  return (
    <div style={{ padding: "18px 16px 60px", maxWidth: 720, margin: "0 auto" }}>
      <h1 style={{ font: `600 22px ${T.uiFont}`, color: T.ink, margin: "0 0 4px" }}>
        Progress <span style={{ font: `20px ${T.jpFont}`, color: T.sub }}>きろく</span>
      </h1>
      <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.sub, margin: "0 0 22px" }}>
        What you can do so far, and everything you have written and had checked.
      </p>

      {dormantDays != null && dormantDays >= DORMANT_DAYS && (
        <p role="status" style={{
          font: `13px/1.6 ${T.uiFont}`, color: T.note, background: T.noteBg,
          borderRadius: 8, padding: "10px 12px", margin: "0 0 18px",
        }}>
          It has been about {Math.floor(dormantDays / 7)} weeks since you last
          studied. Everything is exactly where you left it — but if you would
          rather begin a section again from the start, you can clear it below.
          Nothing here expires on its own.
        </p>
      )}

      <div style={{ display: "flex", alignItems: "baseline",
                    justifyContent: "space-between", marginBottom: 10 }}>
        <h2 style={h3}>WHAT YOU CAN DO</h2>
        <span style={{ font: `13px ${T.uiFont}`, color: T.note }}>
          <span style={{ fontFamily: T.jpFont }}>小判</span> {wallet}
        </span>
      </div>

      <ul style={{ listStyle: "none", padding: 0, margin: "0 0 26px" }}>
        {stats.map((s) => (
          <li key={s.id} style={{
            display: "flex", alignItems: "baseline", justifyContent: "space-between",
            padding: "9px 0", borderBottom: `1px solid ${T.hairline}`,
          }}>
            <span style={{ font: `14px ${T.uiFont}` }}>
              {s.label}{" "}
              <span style={{ font: `13px ${T.jpFont}`, color: T.sub }}>{s.jp}</span>
            </span>
            <span style={{ font: `13px ${T.uiFont}`, color: s.started ? T.ink : T.sub }}>
              {s.started ? s.unit(s.count) : "not started"}
            </span>
          </li>
        ))}
      </ul>

      {/* ⭐ THE CONNECTION LLOYD ASKED FOR. A progress screen that reports
          "you have met 12 patterns" and offers no way to SEE them has given the
          learner a label instead of a lesson. The counts here are the door, and
          the door is next to the numbers rather than somewhere else. */}
      <h2 style={{ ...h3, marginBottom: 8 }}>WHAT YOU HAVE WRITTEN</h2>
      {checker && checker.checks > 0 ? (
        <div style={{
          border: `1px solid ${T.hairline}`, borderRadius: 10, background: T.sheet,
          padding: "14px 16px", marginBottom: 26,
        }}>
          <p style={{ font: `15px/1.7 ${T.uiFont}`, color: T.ink, margin: "0 0 4px" }}>
            {checker.checks} {checker.checks === 1 ? "sentence" : "sentences"} checked
            {Object.keys(checker.patterns).length > 0 && <>
              {" "}· {Object.keys(checker.patterns).length}{" "}
              {Object.keys(checker.patterns).length === 1 ? "kind" : "kinds"} of thing
              came up
            </>}
          </p>
          {/* The denominator, stated rather than implied. A count of issues on
              its own is not a trend and reads as a scoreboard; alongside the
              number of checks it is just what happened. */}
          <p style={{ ...quiet, margin: "0 0 12px" }}>
            {checker.issues === 0
              ? "Nothing has been flagged so far."
              : `${checker.issues} ${checker.issues === 1 ? "note" : "notes"} across them.`}
          </p>
          <button onClick={openReview} style={ghost}>
            Look back at your sentences
          </button>
        </div>
      ) : (
        <p style={{ font: `14px/1.7 ${T.uiFont}`, color: T.sub, margin: "0 0 26px" }}>
          Nothing checked yet. Anything you write in the{" "}
          <button onClick={() => go("checker")} style={{
            background: "none", border: "none", padding: 0, cursor: "pointer",
            font: `inherit`, color: T.ink, textDecoration: "underline",
          }}>checker</button>{" "}
          is kept here for you to look back at, grouped by the kind of thing it was.
        </p>
      )}

      <h2 style={{ ...h3, marginBottom: 8 }}>START A SECTION AGAIN</h2>
      <p style={{ ...quiet, marginTop: 0 }}>
        Choose what to clear. Nothing is downloaded automatically — if you want
        to be able to undo this, save a copy first.
      </p>
      <div style={{ margin: "10px 0" }}>
        {stats.map((s) => (
          <label key={s.id} style={{
            display: "flex", alignItems: "center", gap: 9, padding: "6px 0",
            font: `14px ${T.uiFont}`, color: s.started ? T.ink : T.sub,
            cursor: s.started ? "pointer" : "default",
          }}>
            <input
              type="checkbox" disabled={!s.started}
              checked={picked.includes(s.id)}
              onChange={(e) => setPicked((p) =>
                e.target.checked ? [...p, s.id] : p.filter((x) => x !== s.id))}
            />
            {s.label}
            {!s.started && <span style={quiet}>— nothing to clear</span>}
          </label>
        ))}
        {!started.length && (
          <p style={{ ...quiet, margin: "4px 0 0" }}>There is nothing to clear yet.</p>
        )}
      </div>

      {!confirming ? (
        <button onClick={() => setConfirming(true)} disabled={!picked.length}
                style={{ ...ghost, opacity: picked.length ? 1 : 0.5,
                         color: picked.length ? T.shu : T.sub,
                         borderColor: picked.length ? T.shu : T.hairline }}>
          Clear selected…
        </button>
      ) : (
        <div style={{ border: `1px solid ${T.shu}55`, borderRadius: 8, padding: 12 }}>
          <p style={{ font: `14px/1.6 ${T.uiFont}`, margin: "0 0 10px" }}>
            Clear <strong>{stats.filter((s) => picked.includes(s.id))
              .map((s) => s.label).join(" and ")}</strong>? This cannot be undone
            unless you save a copy first.
            {/* Named explicitly, because "Checker" does not obviously mean
                "every sentence you have written". Deleting your own writing
                should never be something you discover you did. */}
            {picked.includes("checker") &&
              " That includes every sentence you have had checked, and what came back."}
          </p>
          <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
            <button onClick={() => {
              try { downloadProgress(); setSavedCopy("Saved. The file is in your downloads."); }
              catch { setSavedCopy("The browser would not save the file."); }
            }} style={{ ...ghost, borderStyle: "dashed" }}>
              Save a copy first
            </button>
            <button onClick={doReset} style={danger}>Yes, clear it</button>
            <button onClick={() => setConfirming(false)} style={ghost}>Cancel</button>
          </div>
          {savedCopy && (
            <p role="status" style={{ ...quiet, color: T.ok, marginTop: 8 }}>{savedCopy}</p>
          )}
        </div>
      )}

      {resetMsg && (
        <p role="status" style={{
          font: `13px/1.6 ${T.uiFont}`, color: T.note, background: T.noteBg,
          borderRadius: 8, padding: "10px 12px", marginTop: 12,
        }}>{resetMsg}</p>
      )}

      {/* The way BACK from a saved file is in Account, under BACKUP, next to
          the Save it belongs with. A restore button here on its own was the
          worse half of a split feature: the reset's "Save a copy first" below
          is a shortcut to that same download, and a person looking for how to
          put it back should find both halves in one place rather than
          discovering them on separate screens. */}
    </div>
  );
}
