// GENERATED by build-vite-app.py — do not hand-edit.
// ShellSlot: render children into the shell slot of that name (#ts-slot-<name>
// in App.jsx) — the header toggle, the index tabs. Found in a layout effect so
// there is no frame drawn in the wrong place; if the slot is not there (a test
// harness, a module rendered on its own) the children render in place.
import { useLayoutEffect, useState } from "react";
import { createPortal } from "react-dom";

export function ShellSlot({ name, children }) {
  const [el, setEl] = useState(undefined);
  useLayoutEffect(() => {
    setEl(typeof document === "undefined" ? null : document.getElementById("ts-slot-" + name));
  }, [name]);
  if (el === undefined) return null;
  return el ? createPortal(children, el) : <>{children}</>;
}
