// GENERATED by build-vite-app.py from kanji-module.jsx — ONE implementation.
// Previously hand-copied into four modules. Calibration is shared through
// stroke-data-v1, so two scoring implementations would end up calibrating
// against each other's mistakes. Hoisting removes that class of bug rather
// than merely watching for it.
// KanjiVG (Ulrich Apel), CC BY-SA 3.0 — http://kanjivg.tagaini.net
import { useEffect, useMemo, useRef, useState } from "react";
import { T } from "./tokens.js";
import { STROKES } from "./strokeData.js";

const CAL_MIN = 8, CAL_KEEP = 60, LOG_KEEP = 400, LOG_PTS = 48;
const SD_KEY = "tsumiki-stroke-data-v1";
const STROKE_BOX = 109;
const TOL = { good: 7, ok: 12, loose: 20 };
const TRACE_N = 24;
const TRACE_STAGES = [
  { id: "trace",  label: "Trace",  blurb: "Follow the grey stroke. This is about the movement, not accuracy." },
  { id: "guided", label: "Guided", blurb: "Earlier strokes stay. Draw the next one from memory." },
  { id: "blank",  label: "Blank",  blurb: "Nothing shown. Order is yours to get right now." },
];
const meanDist = (a, b) => {
  let s = 0;
  for (let i = 0; i < a.length; i++) s += Math.hypot(a[i][0]-b[i][0], a[i][1]-b[i][1]);
  return s / a.length;
};
const median = (a) => {
  if (!a.length) return null;
  const b = [...a].sort((x, y) => x - y), m = b.length >> 1;
  return b.length % 2 ? b[m] : (b[m-1] + b[m]) / 2;
};

function strokeStart(d) {
  const m = /^M\s*(-?[\d.]+)[,\s]+(-?[\d.]+)/i.exec(d);
  return m ? [parseFloat(m[1]), parseFloat(m[2])] : null;
}

function StrokeView({ ch, size = 132, numbers, auto }) {
  const paths = STROKES[ch] || [];
  const refs = useRef([]);
  const [lens, setLens] = useState([]);
  const [step, setStep] = useState(-1);
  const timer = useRef(null);
  const reduced = typeof window !== "undefined" && window.matchMedia
    ? window.matchMedia("(prefers-reduced-motion: reduce)").matches : false;

  useEffect(() => {
    const measured = paths.map((_, i) => {
      const el = refs.current[i];
      try { return el && el.getTotalLength ? el.getTotalLength() : 120; } catch { return 120; }
    });
    setLens(measured);
    setStep(reduced ? paths.length : -1);
    if (auto && !reduced) {
      const t = setTimeout(() => setStep(0), 120);
      return () => clearTimeout(t);
    }
  }, [ch]);

  useEffect(() => {
    if (reduced || step < 0 || step >= paths.length) return;
    const dur = Math.max(240, (lens[step] || 120) * 5.5);
    timer.current = setTimeout(() => setStep((s) => s + 1), dur + 110);
    return () => clearTimeout(timer.current);
  }, [step, lens, paths.length]);

  const play = () => { clearTimeout(timer.current); setStep(reduced ? paths.length : 0); };
  const idle = step < 0;

  return (
    <div style={{ display: "inline-block", textAlign: "center" }}>
      <svg width={size} height={size} viewBox={`0 0 ${STROKE_BOX} ${STROKE_BOX}`}
        role="img" aria-label={`${ch}, stroke order`}
        style={{ background: T.sheet, border: `1px solid ${T.hairline}`, borderRadius: 3, cursor: "pointer" }}
        onClick={play}>
        <line x1={STROKE_BOX/2} y1="0" x2={STROKE_BOX/2} y2={STROKE_BOX} stroke={T.hairline} strokeWidth="0.6" strokeDasharray="3 3" />
        <line x1="0" y1={STROKE_BOX/2} x2={STROKE_BOX} y2={STROKE_BOX/2} stroke={T.hairline} strokeWidth="0.6" strokeDasharray="3 3" />
        {paths.map((d, i) => (
          <path key={"g" + i} d={d} fill="none" stroke="#EAE8E1" strokeWidth="5.5"
            strokeLinecap="round" strokeLinejoin="round" />
        ))}
        {paths.map((d, i) => {
          const len = lens[i] || 120;
          const drawn = step > i, active = step === i;
          return (
            <path key={"s" + i} ref={(el) => (refs.current[i] = el)} d={d} fill="none"
              stroke={active ? T.shu : T.ink} strokeWidth="5" strokeLinecap="round" strokeLinejoin="round"
              style={{
                strokeDasharray: len,
                strokeDashoffset: drawn || active ? 0 : len,
                transition: active ? `stroke-dashoffset ${Math.max(240, len * 5.5)}ms linear` : "none",
              }} />
          );
        })}
        {numbers && paths.map((d, i) => {
          const pt = strokeStart(d);
          if (!pt) return null;
          return (
            <g key={"n" + i}>
              <circle cx={pt[0]} cy={pt[1]} r="7.5" fill={T.sheet} stroke={T.ai} strokeWidth="1" opacity="0.92" />
              <text x={pt[0]} y={pt[1] + 3.2} textAnchor="middle" fontSize="9" fill={T.ai} fontFamily="sans-serif">{i + 1}</text>
            </g>
          );
        })}
      </svg>
      <div style={{ fontSize: "0.6875rem", color: T.sub, marginTop: 4 }}>
        {idle ? "tap to write" : `${paths.length} stroke${paths.length === 1 ? "" : "s"}`}
      </div>
    </div>
  );
}

function resample(pts, n) {
  if (!pts.length) return [];
  if (pts.length === 1) return Array.from({ length: n }, () => pts[0]);
  const acc = [0];
  for (let i = 1; i < pts.length; i++) acc.push(acc[i-1] + Math.hypot(pts[i][0]-pts[i-1][0], pts[i][1]-pts[i-1][1]));
  const total = acc[acc.length - 1];
  if (total === 0) return Array.from({ length: n }, () => pts[0]);
  const out = []; let j = 0;
  for (let k = 0; k < n; k++) {
    const target = (total * k) / (n - 1);
    while (j < acc.length - 2 && acc[j+1] < target) j++;
    const seg = acc[j+1] - acc[j];
    const t = seg > 0 ? (target - acc[j]) / seg : 0;
    out.push([pts[j][0] + (pts[j+1][0]-pts[j][0])*t, pts[j][1] + (pts[j+1][1]-pts[j][1])*t]);
  }
  return out;
}

function samplePath(d, n) {
  if (typeof document === "undefined") return [];
  const NS = "http://www.w3.org/2000/svg";
  const svg = document.createElementNS(NS, "svg");
  svg.setAttribute("style", "position:absolute;width:0;height:0;overflow:hidden;pointer-events:none");
  const p = document.createElementNS(NS, "path");
  p.setAttribute("d", d);
  svg.appendChild(p);
  document.body.appendChild(svg);
  let out = [];
  try {
    const len = p.getTotalLength();
    for (let i = 0; i < n; i++) { const pt = p.getPointAtLength((len * i) / (n - 1)); out.push([pt.x, pt.y]); }
  } catch { out = []; }
  document.body.removeChild(svg);
  return out;
}

function scoreStroke(userPts, refPts) {
  const u = resample(userPts, TRACE_N);
  if (u.length !== TRACE_N || refPts.length !== TRACE_N) return { dist: 999, backwards: false };
  const fwd = meanDist(u, refPts);
  const rev = meanDist(u, [...refPts].reverse());
  return { dist: Math.min(fwd, rev), backwards: rev < fwd * 0.9 };
}

function tolerancesFor(floor) {
  if (floor == null) return { ...TOL, calibrated: false };
  const cl = (v, lo, hi) => Math.min(hi, Math.max(lo, v));
  return { good: cl(floor*1.6, 4, 10), ok: cl(floor*2.6, 7, 16), loose: cl(floor*4.0, 12, 26), calibrated: true };
}

function thinPoints(pts, n) {
  if (pts.length <= n) return pts.map(([x, y]) => [Math.round(x*10)/10, Math.round(y*10)/10]);
  const step = (pts.length - 1) / (n - 1);
  return Array.from({ length: n }, (_, i) => {
    const p = pts[Math.round(i * step)];
    return [Math.round(p[0]*10)/10, Math.round(p[1]*10)/10];
  });
}

function useStrokeData() {
  const data = useRef({ cal: [], log: [] });
  const [, bump] = useState(0);
  const dirty = useRef(0);
  const loaded = useRef(false);

  const flush = async () => {
    if (!loaded.current || !dirty.current) return;
    dirty.current = 0;
    try { await window.storage.set(SD_KEY, JSON.stringify(data.current)); }
    catch (e) { console.error("stroke data save failed", e); }
  };

  useEffect(() => {
    (async () => {
      try {
        const r = await window.storage.get(SD_KEY);
        if (r) { const p = JSON.parse(r.value); data.current = { cal: p.cal || [], log: p.log || [] }; }
      } catch { /* first run */ }
      loaded.current = true;
      bump((v) => v + 1);
    })();
    return () => { flush(); };
  }, []);

  const record = (entry, calSample) => {
    data.current.log = [...data.current.log, entry].slice(-LOG_KEEP);
    if (calSample != null) data.current.cal = [...data.current.cal, calSample].slice(-CAL_KEEP);
    dirty.current++;
    bump((v) => v + 1);
    if (dirty.current >= 5) flush();
  };

  const cal = data.current.cal;
  return { cal, floor: cal.length >= CAL_MIN ? median(cal) : null, record };
}

function StrokePractice({ chars, modId, progress, onProgress, startCh }) {
  const [ch, setCh] = useState(startCh || chars[0] || null);
  // Arriving from a character panel should land on THAT character, not reset to
  // the first one in the lesson.
  useEffect(() => { if (startCh) setCh(startCh); }, [startCh]);
  const [stageIdx, setStageIdx] = useState(0);
  const [strokeIdx, setStrokeIdx] = useState(0);
  const [drawn, setDrawn] = useState([]);
  const [feedback, setFeedback] = useState(null);
  const [hint, setHint] = useState(false);   // one stroke, cleared once it lands
  const canvasRef = useRef(null);
  const drawing = useRef(false);
  const currentRef = useRef([]);
  const pointerType = useRef("unknown");
  const { floor, record } = useStrokeData();
  const tol = tolerancesFor(floor);

  const paths = (ch && STROKES[ch]) || [];
  const refs = useMemo(() => paths.map((d) => samplePath(d, TRACE_N)), [ch]);
  const stage = TRACE_STAGES[stageIdx];
  const SIZE = 260;
  const SC = SIZE / STROKE_BOX;

  useEffect(() => { setStrokeIdx(0); setDrawn([]); setFeedback(null); setHint(false); }, [ch, stageIdx]);

  const redraw = () => {
    const cv = canvasRef.current;
    if (!cv) return;
    const g = cv.getContext("2d");
    const dpr = window.devicePixelRatio || 1;
    if (cv.width !== SIZE * dpr) { cv.width = SIZE * dpr; cv.height = SIZE * dpr; }
    g.setTransform(dpr, 0, 0, dpr, 0, 0);
    g.clearRect(0, 0, SIZE, SIZE);
    g.fillStyle = T.sheet; g.fillRect(0, 0, SIZE, SIZE);
    g.strokeStyle = T.hairline; g.lineWidth = 1;
    g.setLineDash([4, 4]);
    g.beginPath(); g.moveTo(SIZE/2, 0); g.lineTo(SIZE/2, SIZE);
    g.moveTo(0, SIZE/2); g.lineTo(SIZE, SIZE/2); g.stroke();
    g.setLineDash([]);
    g.strokeRect(0.5, 0.5, SIZE-1, SIZE-1);

    const poly = (pts, colour, w) => {
      if (pts.length < 2) return;
      g.strokeStyle = colour; g.lineWidth = w; g.lineCap = "round"; g.lineJoin = "round";
      g.beginPath(); g.moveTo(pts[0][0]*SC, pts[0][1]*SC);
      for (let i = 1; i < pts.length; i++) g.lineTo(pts[i][0]*SC, pts[i][1]*SC);
      g.stroke();
    };

    // Ghost of the current stroke: always on Trace, on request everywhere else.
    if ((stage.id === "trace" || hint) && refs[strokeIdx]) poly(refs[strokeIdx], "#DEDCD4", 13);
    if (stage.id !== "blank") for (let i = 0; i < strokeIdx; i++) if (refs[i]) poly(refs[i], "#C9C7BF", 11);
    drawn.forEach((s) => poly(s, T.ink, 11));
    if (currentRef.current.length) poly(currentRef.current, T.shu, 11);
  };

  useEffect(redraw, [ch, stageIdx, strokeIdx, drawn, refs, hint]);

  const toBox = (e) => {
    const r = canvasRef.current.getBoundingClientRect();
    return [((e.clientX - r.left) / r.width) * STROKE_BOX, ((e.clientY - r.top) / r.height) * STROKE_BOX];
  };

  const down = (e) => {
    if (!paths.length || strokeIdx >= paths.length) return;
    e.currentTarget.setPointerCapture?.(e.pointerId);
    drawing.current = true;
    pointerType.current = e.pointerType || "unknown";
    currentRef.current = [toBox(e)];
    setFeedback(null);
    redraw();
  };
  const move = (e) => { if (!drawing.current) return; currentRef.current.push(toBox(e)); redraw(); };
  const up = () => {
    if (!drawing.current) return;
    drawing.current = false;
    const pts = currentRef.current;
    currentRef.current = [];
    if (pts.length < 3) { redraw(); return; }

    let result;
    if (stage.id === "blank") {
      let best = { i: strokeIdx, ...scoreStroke(pts, refs[strokeIdx] || []) };
      refs.forEach((r, i) => {
        if (i < strokeIdx) return;
        const sc = scoreStroke(pts, r);
        if (sc.dist < best.dist) best = { i, ...sc };
      });
      result = { ...best, outOfOrder: best.i !== strokeIdx && best.dist < TOL.ok };
    } else {
      result = { i: strokeIdx, ...scoreStroke(pts, refs[strokeIdx] || []) };
    }

    const bar = stage.id === "trace" ? tol.loose : stage.id === "guided" ? (tol.ok + tol.loose)/2 : tol.ok;
    let tier, msg;
    if (result.outOfOrder) {
      tier = "unnatural";
      msg = `That's stroke ${result.i + 1}, drawn well — but stroke ${strokeIdx + 1} comes first. Order is the thing being tested here.`;
    } else if (result.dist > bar) {
      tier = "fix"; msg = "That doesn't follow the stroke. Watch it once more, then try again.";
    } else if (result.backwards) {
      tier = "unnatural";
      msg = "Right shape, drawn backwards. The direction is what makes handwriting readable — start from the other end.";
    } else if (result.dist <= tol.good) {
      tier = "good"; msg = "Clean.";
    } else {
      tier = "ok"; msg = "Close enough. A little loose, but the movement is right.";
    }

    // Calibration samples ONLY where a reference is actually visible — a stroke
    // drawn over nothing would loosen the floor for every module sharing it.
    const refVisible = stage.id === "trace" && !hint;
    const calSample = refVisible && result.dist < 25 && !result.backwards ? result.dist : null;
    record({
      t: Date.now(), ch, stroke: strokeIdx, stage: stage.id, hinted: hint,
      device: pointerType.current, dist: Math.round(result.dist*100)/100,
      backwards: !!result.backwards, outOfOrder: !!result.outOfOrder, tier,
      pts: thinPoints(pts, LOG_PTS),
    }, calSample);

    setFeedback({ tier, msg });
    if (tier === "good" || tier === "ok") {
      setDrawn([...drawn, pts]);
      setHint(false);                       // one tap buys one stroke
      const done = strokeIdx + 1 >= paths.length;
      setStrokeIdx(strokeIdx + 1);
      if (done) {
        const prev = progress[modId] || {};
        const seen = new Set(prev.traced || []);
        seen.add(ch + ":" + stage.id);
        onProgress({ ...progress, [modId]: { ...prev, traced: [...seen] } });
      }
    } else {
      redraw();
    }
  };

  if (!chars.length) return <p style={{ fontSize: "0.875rem", color: T.sub }}>No characters to practise in this lesson.</p>;
  if (!paths.length) return <p style={{ fontSize: "0.875rem", color: T.sub }}>No stroke data for this character yet.</p>;

  const finished = strokeIdx >= paths.length;
  const tierColour = feedback
    ? feedback.tier === "fix" ? T.shu : feedback.tier === "unnatural" ? T.ai : T.ok
    : T.sub;
  const doneSet = new Set((progress[modId] || {}).traced || []);

  return (
    <div>
      <div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 12 }}>
        {chars.map((c) => (
          <button key={c} onClick={() => setCh(c)} style={{
            fontFamily: T.jpFont, fontSize: "1.375rem", padding: "6px 12px", borderRadius: 4, cursor: "pointer",
            background: ch === c ? T.ink : T.sheet, color: ch === c ? T.paper : T.ink,
            border: `1px solid ${ch === c ? T.ink : T.hairline}`,
          }}>{c}</button>
        ))}
      </div>

      <div style={{ display: "flex", gap: 6, marginBottom: 10, flexWrap: "wrap" }}>
        {TRACE_STAGES.map((s, i) => (
          <button key={s.id} onClick={() => setStageIdx(i)} style={{
            border: `1px solid ${stageIdx === i ? T.ink : T.hairline}`, borderRadius: 999,
            background: stageIdx === i ? T.ink : "none", color: stageIdx === i ? T.paper : T.sub,
            fontSize: "0.75rem", padding: "5px 14px", cursor: "pointer", fontFamily: "inherit",
          }}>
            {s.label}{doneSet.has(ch + ":" + s.id) ? " ✓" : ""}
          </button>
        ))}
      </div>
      <p style={{ fontSize: "0.8125rem", color: T.sub, margin: "0 0 12px" }}>{stage.blurb}</p>

      <div style={{ display: "flex", gap: 20, flexWrap: "wrap", alignItems: "flex-start" }}>
        <div>
          <canvas
            ref={canvasRef}
            onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up}
            style={{
              width: SIZE, height: SIZE, border: `1px solid ${T.hairline}`, borderRadius: 4,
              background: T.sheet, touchAction: "none", cursor: "crosshair", display: "block",
            }}
            aria-label={`Writing box for ${ch}`}
          />
          <div style={{ display: "flex", gap: 8, marginTop: 10, flexWrap: "wrap" }}>
            <button className="btn-ghost" onClick={() => { setStrokeIdx(0); setDrawn([]); setFeedback(null); setHint(false); }}>
              Start over
            </button>
            {!finished && stage.id !== "trace" && (
              <button className="btn-ghost" onClick={() => setHint(true)} disabled={hint}>
                {hint ? "Stroke shown" : "Help me"}
              </button>
            )}
          </div>
        </div>

        <div style={{ flex: 1, minWidth: 190 }}>
          <div style={{ fontSize: "0.8125rem", color: T.sub, marginBottom: 8 }}>
            {finished ? "Finished." : `Stroke ${strokeIdx + 1} of ${paths.length}`}
          </div>
          {feedback && (
            <p style={{ fontSize: "0.875rem", lineHeight: 1.6, color: tierColour, margin: "0 0 12px" }}>
              {feedback.msg}
            </p>
          )}
          {hint && !finished && (
            <p style={{ fontSize: "0.75rem", color: T.sub, margin: "0 0 12px" }}>
              Just this stroke. It clears once you land it.
            </p>
          )}
          <StrokeView ch={ch} size={110} numbers auto={false} />
          {!tol.calibrated && (
            <p style={{ fontSize: "0.6875rem", color: T.sub, marginTop: 10 }}>
              Still learning your handwriting — tolerance loosens or tightens to suit your hand and device.
            </p>
          )}
        </div>
      </div>
    </div>
  );
}

export { strokeStart, StrokeView, resample, samplePath, scoreStroke, tolerancesFor, thinPoints, useStrokeData, StrokePractice, CAL_KEEP, CAL_MIN, LOG_KEEP, LOG_PTS, SD_KEY, STROKE_BOX, TOL, TRACE_N, TRACE_STAGES, meanDist, median };
