// ————— Supabase client —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// The URL and the publishable key come from Netlify build env vars, the same
// shape as VITE_CHECKER_URL:
//
//   VITE_SUPABASE_URL               https://llkazgmhsuonhwrubwjw.supabase.co
//   VITE_SUPABASE_PUBLISHABLE_KEY   sb_publishable_…
//
// NEITHER IS A SECRET. A publishable key is designed to sit in a browser; it
// carries the `anon` role, and every table this app touches denies `anon` at
// both the privilege and the policy layer (see
// supabase/migrations/20260906000000_progress_sync.sql). The secret that must
// never reach a browser is the service-role key, which lives in the Edge
// Function's environment and appears nowhere in this repo.
//
// ⚠️ `import.meta.env?.` WITH THE OPTIONAL CHAIN, not `import.meta.env.`.
// The smoke test bundles with esbuild in iife format, where `import.meta` is
// replaced by `{}` — so `.env` is undefined and any further plain access
// throws at module load, taking every module's render test down with it. The
// Checker uses the same guarded form for the same reason.
const URL_ = import.meta.env?.VITE_SUPABASE_URL || "";
const KEY_ = import.meta.env?.VITE_SUPABASE_PUBLISHABLE_KEY || "";

// Accounts are OPTIONAL. A build without these vars — a local `npm run dev`, the
// static standalone bundle, the smoke test — must still work exactly as it did
// before accounts existed. Everything account-shaped is behind this flag, and
// the UI says so in words rather than failing at the first click.
export function accountsConfigured() {
  return Boolean(URL_ && KEY_);
}

// ————— Writes that start as the page is going away —————
//
// ⚠️ A NORMAL fetch() STARTED ON `pagehide` IS NOT GUARANTEED TO BE SENT. The
// browser is free to cancel it the moment the document is discarded, and on
// iOS Safari — where a tab is frozen rather than closed — that is the common
// case, not the rare one. `keepalive: true` is what makes the request outlive
// the page. It is not the default because keepalive requests are capped at
// 64 KB of body and compete for a small per-origin budget.
//
// So it is a MODE, switched on around exactly one call — lib/autosave.js's
// flush on hide — rather than a second HTTP path. One write path, one set of
// headers, one auth refresh; only the transport hint changes. A separate
// hand-rolled REST call for the hide case is the shape this repo keeps getting
// burned by: two writers that are almost the same.
let urgent = false;
export function beginUrgentWrites() { urgent = true; }
export function endUrgentWrites() { urgent = false; }

// The cap is real and silent if exceeded — an over-size keepalive request
// simply rejects. A learner with a long checker history can push more than
// 64 KB, so the hint is dropped above a conservative threshold and the write
// takes its chances as an ordinary request rather than failing outright.
const KEEPALIVE_MAX = 60000;

function syncFetch(input, init) {
  if (urgent) {
    const body = init && init.body;
    const size = typeof body === "string" ? body.length : 0;
    if (size <= KEEPALIVE_MAX) return fetch(input, { ...init, keepalive: true });
  }
  return fetch(input, init);
}

// Loaded on demand, never at first paint. @supabase/supabase-js is ~120 KB and
// a learner who never signs in should not pay for it — the same reasoning that
// keeps the six modules behind React.lazy.
let clientPromise = null;

export function getClient() {
  if (!accountsConfigured()) return Promise.resolve(null);
  if (!clientPromise) {
    clientPromise = import("@supabase/supabase-js")
      .then(({ createClient }) => createClient(URL_, KEY_, {
        auth: {
          persistSession: true,
          autoRefreshToken: true,
          // The magic link comes back as a URL fragment; this is what turns it
          // into a session. On by default — named here because switching it off
          // is a silent "clicking the link does nothing".
          detectSessionInUrl: true,
        },
        global: { fetch: syncFetch },
      }))
      .catch((e) => { clientPromise = null; throw e; });
  }
  return clientPromise;
}

// Where the emailed link should land. Deliberately this origin and nothing
// hard-coded: the same build serves tsumiki-jp.netlify.app, the branch deploy and a
// local dev server, and a baked-in URL would send a laptop's link to production.
//
// ⚠️ EVERY ORIGIN USED HERE MUST BE LISTED IN SUPABASE'S REDIRECT ALLOW-LIST
// (Authentication -> URL Configuration). An origin that is not on the list does
// not error — the link silently falls back to the project's Site URL, which
// defaults to http://localhost:3000. That failure looks exactly like "the email
// never arrived" from the learner's side.
export function redirectTo() {
  if (typeof window === "undefined") return undefined;
  return window.location.origin + window.location.pathname;
}
