// ————— Progress sync —————
// HAND-MAINTAINED. Not generated by build-vite-app.py — do not add a
// "GENERATED" header and do not expect a rebuild to recreate it.
//
// This file answers one question: when a learner signs in, and this browser and
// their account BOTH hold progress, what happens?
//
// ⚠️ WHY IT IS WRITTEN DOWN RATHER THAN IMPLIED. The app has already shipped
// silent progress loss once — `tsumiki-n5-progress-v1` and `tsumiki-learner-depth-v1` were
// missing from the export list for twelve days, so Restore reported "Restored 7
// saved items" over a restore that had dropped the largest module in the app.
// Introducing accounts is the same bug with a bigger blast radius: a sign-in
// that quietly replaces local state with an empty account, or an empty account
// with local state, looks exactly like success. So the rule below is explicit,
// tested (test-progress-sync.py), and refuses to guess.
//
// ————— THE RULE —————
//
// Progress is compared PER KEY, never as one document. A learner who did kanji
// on their phone and grammar on their laptop has two partial states and no
// conflict at all — merging per key gives them both, and asking them to choose
// would make them destroy one half of their own work.
//
//   1. Key present on one side only        -> take it. Nothing can be lost.
//   2. Key present on both, same content   -> nothing to do.
//   3. Key present on both, different      -> CONFLICT. Do not pick. Ask.
//
// "Same content" is canonical-JSON equality, not string equality: two devices
// can hold identical state serialised in a different key order, and reporting
// that as a conflict would train the learner to dismiss the question.
//
// "Present" means present AND non-empty. A module that has been opened but not
// used writes "{}", and treating that as a rival to real progress would raise a
// conflict over nothing. Note that "0" is NOT empty — a spent koban wallet is a
// real value that a learner earned their way down to.
//
//   4. On a conflict the app asks, with no default and no timer, and names the
//      items that differ.
//
// ⚠️⚠️ ————— RULE 4 NOW APPLIES TO ONE SITUATION, NOT TO EVERY LOAD —————
//
// Changed 2026-09-16, deliberately, reversing the Session 23 decision that every
// disagreement is a question. THE OLD REASONING IS NOT DELETED BELOW, because
// it was not wrong — it was right about the app it was written for, and the app
// changed underneath it. Read this before touching either half.
//
// WHAT THE OLD RULE ASSUMED. Progress uploaded at exactly two moments: the
// sign-in merge, and a conflict being settled. Nothing pushed during use. Under
// that cadence, "this device and the account differ" genuinely could mean two
// real bodies of work that nobody had ever synced, and picking one without
// asking really would have destroyed the other. Rule 3 was the honest answer to
// a question that had no safe default.
//
// WHY IT STOPPED BEING TRUE — and why a learner met it on an ORDINARY REFRESH.
// The merge ran once per session restore, so on every page load. Meanwhile
// `tsumiki-module-recency-v1` moves when you merely OPEN a section. So any use
// of the app after a load guaranteed local != remote at the next load, and the
// merge dutifully reported a conflict. The rule was working exactly as written
// and the result was a question, on every refresh, about nothing — which is the
// failure mode rule 3's own commentary warns about ("a learner taught to
// dismiss the question will dismiss the real one too"), reached from the other
// direction.
//
// WHAT IS TRUE NOW. lib/autosave.js pushes continuously — debounced off the
// single storage setter, flushed when the page is hidden or closed, hurried at
// the end of a lesson or a checker submission. Once a device has joined an
// account, the account is not a rival copy of the learner's work. It is where
// the work IS, and the browser is a cache of it that reports every change.
//
// So a divergence at load time can no longer mean "two real histories". Work
// this device did would already have been pushed; anything it did not manage to
// push is still HERE, and rule 1 hands it straight back, unasked, because the
// account does not have that key. The residual case — both sides real, both
// different — means this browser is holding something older than the account.
// The account wins, silently, and the archive trigger keeps what it replaced.
//
// ⚠️ THIS IS NOT "NEWEST WINS". No timestamps are compared and no clocks are
// trusted; the design doc's rejection of that still stands. The claim is
// structural: after joining, the device has no way to hold newer state that the
// account has not been told about, because telling it is automatic.
//
// ⚠️ AND THE TWO HALVES ARE ONE CHANGE. An authoritative load without
// continuous saving discards everything done since the last sign-in, on every
// load, silently — the exact shape of the bug this whole file exists to
// prevent. If you ever disable autosave, the authoritative load must go with it.
//
// THE ONE SITUATION THAT IS STILL A GENUINE MERGE, question and all: the FIRST
// sign-in on a device. There the premise above does not hold — this browser's
// progress predates the account relationship entirely and was never pushed, so
// the two sides really are independent histories. `mergeProgress`,
// `resolveConflicts`, the conflict panel and the log-union exemption all stay
// for it. Which case applies is recorded per device by `joinedAccount()` in
// storage.js, and signing out clears it, because a learner who keeps studying
// signed out has made this browser independent again.
//
// ————— THE ONE EXEMPTION, AND WHY IT IS NOT A LOOPHOLE —————
//
// Rule 3 is right because every key above is STATE — where the learner is — and
// two different states mean one device is behind. `tsumiki-checker-history-v1` is not
// state, it is a LOG: what the learner did, and when. Two devices with
// different logs means BOTH ARE TRUE and neither is behind, so asking "which
// history do you want to keep?" has no right answer — and every wrong answer
// deletes writing the learner really did, out of a number they will later be
// shown as fact ("your particle errors are down forty percent since May").
// That is rule 3's own failure mode, one level down.
//
// ⚠️ AND THE EXEMPTION MATTERS MORE NOW, NOT LESS. On the authoritative load
// every other key resolves to the account's copy; if the log resolved that way
// too, a device that wrote checks offline would lose them on the next load with
// nothing on screen to show for it. It does not, because the union runs BEFORE
// the resolution and settles the key without ever reaching the conflict list.
//
// So a LOG key is UNIONED instead of chosen between. This is narrower than it
// looks, and safe for a structural reason rather than a hopeful one: entries
// are immutable and carry their own id, so a union invents nothing and drops
// nothing, and `union(A,B) === union(B,A)` is asserted by test-error-history.py
// rather than assumed. If that property ever fails, the exemption is unearned.
//
// A merger that cannot do its job (unparseable value on either side) returns
// null and the key FALLS BACK TO ASKING. Wrong toward asking, never toward
// quietly inventing a merged document.
//
// Registration is explicit and lives just below the core, so the exempt list is
// a thing you can read rather than a behaviour you have to infer.
//
// WHAT HAPPENS TO THE SIDE THAT LOSES — and note the asymmetry, because it is
// the thing to keep in mind before touching this:
//        · the ACCOUNT's version is kept automatically, by the database, which
//          archives every document it replaces (see the archive trigger in
//          supabase/migrations/20260906000000_progress_sync.sql, and the
//          retention rule in 20260916000000_progress_archive_retention.sql —
//          continuous saving files far more versions than sign-in-only saving
//          did, so they are now pruned rather than kept forever).
//          Nothing the client does can skip it.
//        · the DEVICE's version has no such net. It used to be downloaded
//          automatically before an overwrite; Lloyd removed that (Session 23)
//          on the grounds that a file appearing in someone's Downloads without
//          being asked for is intrusive, and he is right that it is. The save
//          is now a button the learner presses, offered right next to the
//          choice that would overwrite it.
//
// ⚠️ SO THE GUARANTEE IS NOW ASYMMETRIC, AND ANY COPY SAYING OTHERWISE IS
// STALE. Choosing "keep my account" without pressing Save first really does
// discard this device's differing keys, and no wording should imply otherwise.
// The UI says so plainly instead of promising a rescue that no longer happens.
//
// Full write-up, including what was considered and rejected:
// auth-progress-sync-design-v1.md
//
// ⚠️ ONE CONSEQUENCE OF THE AUTHORITATIVE LOAD, STATED SO IT IS NOT A SURPRISE:
// on the load path the device's differing keys are replaced without a button
// having been pressed, so no save is offered and none happens. That is the
// price of the reversal and it is paid knowingly — the archive keeps every
// version the ACCOUNT held, which is now the version that survives, and BACKUP
// in the account panel is still there for a copy the learner holds themselves.

// ——— PURE MERGE CORE (extracted verbatim at run time by test-progress-sync.py) ———

// A value is "empty" when a module has written a placeholder rather than
// progress. Deliberately a short, literal list: anything cleverer starts
// discarding real state. "0" is absent from it on purpose.
const EMPTY_VALUES = new Set(["", "{}", "[]", "null", "undefined"]);

// Keys whose values are logs, not state — see THE ONE EXEMPTION above. Empty
// here on purpose: the entries are registered below the core, so the extracted
// slice starts with no exemptions and a test must opt one in deliberately.
const LOG_MERGERS = {};

// fn(localString, remoteString) -> merged string, or null to fall back to
// asking. Never register something that can throw: mergeProgress is the last
// thing standing between a sign-in and someone's progress.
function registerLogMerger(key, fn) { LOG_MERGERS[key] = fn; }

function isEmptyValue(v) {
  if (v === null || v === undefined) return true;
  return EMPTY_VALUES.has(String(v).trim());
}

// Canonical form for COMPARISON ONLY. The value written to storage is always
// the original string — canonicalising on the way in would rewrite module data
// this file has no business understanding.
function canon(v) {
  try {
    const sort = (x) => {
      if (Array.isArray(x)) return x.map(sort);
      if (x && typeof x === "object") {
        return Object.keys(x).sort().reduce((o, k) => { o[k] = sort(x[k]); return o; }, {});
      }
      return x;
    };
    return JSON.stringify(sort(JSON.parse(v)));
  } catch {
    return String(v);
  }
}

// The same idea one level up: a canonical form of a WHOLE document, so that
// "would this push write anything the account does not already have?" has a
// cheap, exact answer. `keys` is passed in rather than imported because this
// core is sliced out and run standalone by the test; pass storage.js's KEYS to
// compare exactly what pushRemote would send.
//
// ⚠️ IT COMPARES canon() PER VALUE, NOT RAW STRINGS. A module that rebuilds its
// own map can serialise identical state in a different key order; treating that
// as a change would file a new archive version every time a learner opened a
// section, which at autosave cadence is the difference between a history and a
// haystack.
function canonDoc(map, keys) {
  const src = map || {};
  const ks = (keys && keys.length ? keys : Object.keys(src)).slice().sort();
  const out = {};
  for (const k of ks) {
    const v = src[k];
    if (v === undefined || v === null) continue;
    out[k] = canon(String(v));
  }
  return JSON.stringify(out);
}

// local, remote: plain maps of key -> string. Returns a plan, not a decision:
// `merged` holds every key that could be settled without asking, and
// `conflicts` lists the keys that could not. A caller that ignores `conflicts`
// and applies `merged` will UNDER-write rather than over-write, which is the
// safe direction to be wrong in.
function mergeProgress(local, remote) {
  const keys = new Set([...Object.keys(local || {}), ...Object.keys(remote || {})]);
  const merged = {};
  const pushed = [];   // this device had it, the account did not
  const pulled = [];   // the account had it, this device did not
  const same = [];
  const unioned = [];  // logs merged without asking — see THE ONE EXEMPTION
  const conflicts = [];

  for (const k of [...keys].sort()) {
    const l = local ? local[k] : undefined;
    const r = remote ? remote[k] : undefined;
    const lEmpty = isEmptyValue(l);
    const rEmpty = isEmptyValue(r);

    if (lEmpty && rEmpty) continue;                        // nothing either side
    if (rEmpty) { merged[k] = l; pushed.push(k); continue; }
    if (lEmpty) { merged[k] = r; pulled.push(k); continue; }
    if (canon(l) === canon(r)) { merged[k] = l; same.push(k); continue; }

    // Both sides real and different. A log unions; everything else asks.
    if (LOG_MERGERS[k]) {
      let u = null;
      try { u = LOG_MERGERS[k](l, r); } catch { u = null; }
      if (u != null) { merged[k] = u; unioned.push(k); continue; }
      // fell through on purpose — see the note about falling back to asking
    }
    conflicts.push(k);
  }

  return {
    merged, pushed, pulled, same, unioned, conflicts,
    status: conflicts.length ? "conflict" : "clean",
  };
}

// Settle the keys mergeProgress refused to settle. `side` is "local" or
// "remote" and must be an explicit choice made by the learner — there is no
// default value for this argument on purpose.
//
// ⚠️ IT NOW HAS A SECOND CALLER THAT IS NOT A LEARNER: the authoritative load
// passes "remote" for it. That is still an explicit choice, made once, in the
// open, in account.jsx — and the argument stays mandatory precisely so that the
// choice cannot be made by omission. The first-sign-in path, where the learner
// really does decide, is unchanged.
function resolveConflicts(plan, local, remote, side) {
  if (side !== "local" && side !== "remote") {
    throw new Error('resolveConflicts: side must be "local" or "remote"');
  }
  const out = { ...plan.merged };
  for (const k of plan.conflicts) out[k] = side === "local" ? local[k] : remote[k];
  return out;
}

// ⚠️ THE GUARD THAT WAS MISSING ON 2026-09-07, and what it is actually for.
//
// mergeProgress above is correct and was never the bug. When the rename moved
// every key into the `tsumiki-` namespace, the device's old keys were orphaned
// — so exportProgress(), which filters through KEYS, returned {} — and the
// account row's stored keys were the OLD names, so pushRemote's own KEYS filter
// emptied them too. mergeProgress was then handed {} and {}, agreed there was
// nothing to settle, and the empty result was pushed over a live account row.
// Version 7, `{}`, 2 bytes. It survived only because the archive trigger had
// version 6, and because Lloyd went and got it by hand.
//
// THE SHAPE TO REMEMBER: a sound guard sitting downstream of a filter that can
// silently empty its own inputs. Nothing in mergeProgress can see that, because
// by the time it runs the evidence is gone. So the check belongs HERE, on the
// way out, where "I am about to replace everything with nothing" is still a
// visible fact.
//
// It is deliberately narrow — empty over non-empty, nothing else. A guard that
// tried to judge whether a SMALLER push was legitimate would start refusing
// real work, and this project would rather ask than invent.
//
// ⚠️ AND IT IS STILL NOT THE ANSWER TO "IS THIS PUSH STALE?". Autosave fires
// hundreds of times where the old code fired twice, so the tempting move is to
// widen this into a size test and let it referee every push. Do not. The
// staleness question is answered by ORDER, not by size — lib/autosave.js does
// not push at all until the load has finished, and says why at length.
function wouldWipeRemote(next, remote) {
  const live = (m) => Object.keys(m || {}).filter((k) => !isEmptyValue(m[k]));
  return live(next).length === 0 && live(remote).length > 0;
}

// ——— END PURE MERGE CORE ———

import { KEYS, exportProgress, importProgress, downloadProgress } from "./storage.js";
import { HISTORY_KEY, unionHistory } from "./errorHistory.js";
import { notePushed } from "./autosave.js";

// THE EXEMPT LIST, in full. One entry. Adding a second is a decision about
// someone's data, not a refactor: the key must be an append-only log of
// immutable, id-carrying entries, or the union silently starts losing things.
registerLogMerger(HISTORY_KEY, (l, r) => {
  try {
    const a = JSON.parse(l), b = JSON.parse(r);
    const obj = (x) => x && typeof x === "object" && !Array.isArray(x);
    if (!obj(a) || !obj(b)) return null;      // not the shape we own -> ask
    return JSON.stringify(unionHistory(a, b));
  } catch { return null; }                    // unreadable -> ask
});

// What this browser holds, in the shape mergeProgress wants. exportProgress()
// already filters to KEYS, so a key no module owns can never reach the server.
export function readLocal() {
  return exportProgress().data;
}

// Write a settled map back to the browser. Routed through importProgress so it
// inherits the same KEYS filter as a Restore-from-file, rather than becoming a
// second, subtly different write path.
//
// `save: false` because what is being written is what the ACCOUNT just gave us.
// Announcing it would schedule a push of the server's own document back at the
// server — harmless, but a request per load for nothing, and it would make the
// "a quiet load costs a GET and no POST" property untrue.
export function writeLocal(map) {
  return importProgress(JSON.stringify({
    format: "tsumiki-progress", version: 1, data: map,
  }), { save: false });
}

// Would pushing `next` write anything the account does not already hold? Used
// by the load path so that opening the app and doing nothing costs one GET.
export function sameAsRemote(next, remote) {
  return canonDoc(next, KEYS) === canonDoc(remote, KEYS);
}

export {
  mergeProgress, resolveConflicts, isEmptyValue, canon, canonDoc,
  registerLogMerger, wouldWipeRemote,
};

// ————— The server side —————
// The row is `data jsonb` holding exactly this map. The server never parses a
// module's value, so it cannot drop a field it does not recognise.

export async function fetchRemote(client, userId) {
  const { data, error } = await client
    .from("tsumiki_progress")
    .select("data, version, updated_at")
    .eq("user_id", userId)
    .maybeSingle();
  if (error) throw error;
  return data || { data: {}, version: 0, updated_at: null };
}

// `allowEmpty` exists because emptiness is sometimes the POINT. resetEverywhere
// in stats.js clears the learner's progress on purpose and then pushes that
// emptiness to the account — that is the feature working, and a guard which
// could not tell it apart from the 2026-09-07 wipe would silently break Reset
// instead. So the two cases are separated by an argument a reader can see,
// rather than by a heuristic that has to guess intent.
export async function pushRemote(client, userId, map, { allowEmpty = false } = {}) {
  // Only keys the app owns. A stray localStorage entry from another tool on the
  // same origin must not be uploaded to a learner's account.
  const clean = {};
  for (const k of KEYS) if (map[k] !== undefined && map[k] !== null) clean[k] = String(map[k]);

  // Only costs a read on the path that is about to write nothing — see
  // wouldWipeRemote in the merge core for why this check lives here.
  if (!allowEmpty && Object.keys(clean).length === 0) {
    const current = await fetchRemote(client, userId);
    if (wouldWipeRemote(clean, current.data)) {
      const err = new Error(
        "this device had nothing to save, and your account does — so nothing was overwritten"
      );
      err.code = "would_wipe";
      throw err;
    }
  }

  const { error } = await client
    .from("tsumiki_progress")
    .upsert({ user_id: userId, data: clean }, { onConflict: "user_id" });
  if (error) throw error;

  // ⚠️ EVERY PUSH IN THE APP REPORTS ITSELF HERE, not just autosave's. The
  // sign-in settle, a conflict choice and resetEverywhere all push through this
  // function, and if any of them did not say so, the next idle flush would
  // re-send a document the server already had — or worse, believe an older
  // document was the last thing sent.
  notePushed(canonDoc(clean, KEYS));
  return clean;
}

// Offered as a button, not fired automatically — see the note at the top of this
// file. Returns false if the browser refused the download, so a caller can say
// so rather than claiming a save that did not happen.
export function preserveLocalToFile() {
  try { downloadProgress(); return true; } catch { return false; }
}
