// GENERATED by build-vite-app.py — the union of every module's design tokens.
// They were identical apart from additions. A key holding two different values
// fails the build rather than silently picking one.
export const T = {
  ai: "#3D5A80",
  hairline: "#E4E2DB",
  ink: "#22252B",
  jpFont: '"Hiragino Mincho ProN","Yu Mincho","Noto Serif JP",serif',
  midori: "#3E7C4F",
  note: "#907119",
  noteBg: "#FAF3E0",
  ok: "#3E7C4F",
  okBg: "#EDF5EE",
  paper: "#F7F6F2",
  sheet: "#FFFFFF",
  shu: "#C7351B",
  sub: "#6E7178",
  uiFont: '-apple-system,BlinkMacSystemFont,"Segoe UI","Hiragino Sans","Noto Sans JP",sans-serif',
};

// Section accents. AUTHORED in build-vite-app.py, not unioned from the modules
// — no module owns a section identity, the shell does.
//
// Section accents, added Aug 24 2026 (Lloyd's request: a colour per section, with
// the kana lighter shades of one family and kanji its darkest).
// 
// THE BINDING CONSTRAINT IS THAT FOUR PALETTE COLOURS ALREADY MEAN SOMETHING.
// The three-tier feedback system spends 朱 #C7351B on FIX, 藍 #3D5A80 on
// UNNATURAL and 金 #907119 on WORTH KNOWING, and 緑 #3E7C4F is ok/correct. A
// section accent reusing any of them would make red-means-error unreliable, and
// that system is the app's most distinctive idea. So accents must come from hues
// the palette has not already committed. Do not "simplify" this later by reaching
// for an existing token.
// 
// THE SCRIPT TRACK IS ONE FAMILY DEEPENING: 藤 #CFC4E6 -> 藤 #A493CE ->
// 江戸紫 #5B4A7D. Hiragana, katakana and kanji are not three subjects; they are
// one writing system getting deeper, which is what the shared hue says and three
// unrelated colours would not. Purple also happens to sit at the top of the
// 冠位十二階 court ranks, which makes kanji-as-darkest read as rank rather than
// as difficulty — the friendlier of the two framings, and consistent with the
// standing rule against anything that reads as workload.
// 
// THE CHECKER IS DELIBERATELY THE QUIETEST (鼠 #C9C6BE) and this is not an
// oversight. It is the one screen where 朱/藍/金 carry meaning, so a saturated
// frame there competes with the feedback it exists to present. The near-neutral
// also separates the tool from the five learning modules, which is a true
// distinction rather than a cosmetic one.
// 
// CONTRAST — READ THE WHOLE PARAGRAPH BEFORE QUOTING IT. These accents are
// DECORATIVE and REDUNDANT, and that is what exempts them: colour carries no
// information here, because every section is also named in text in the header and
// the drawer, immediately beside the rule. WCAG 1.4.11 governs colour that is
// "required to understand the content", so it does not reach them at all. They
// appear in exactly two places, both non-text and both label-adjacent — a 4px
// borderTop on the home card and a 3px borderBottom on the section header.
// 
// DO NOT read this as "they were measured against 3:1 and passed." Three of them
// do not: #CFC4E6 is 1.53, #C9C6BE is 1.58 and #A493CE is 2.54 against both
// T.paper and T.sheet. That is fine while they stay decorative, and it is the
// whole reason the redundancy above is load-bearing rather than a nicety.
// 
// An earlier version of this comment opened by invoking the 3:1 bar as "what
// applies" and only then gave the reason it may not — so a session reading the
// first sentence would have believed these colours cleared a bar they miss by a
// factor of two. Reworded 2026-09-05 on the weekly audit's finding: the palette
// was never the defect, the sentence was.
// 
// THE CONDITION, since the exemption is conditional: the moment an accent goes
// BEHIND TEXT, or becomes the only thing distinguishing two states, the exemption
// lapses and the real bar is 4.5:1 — not 3:1. #CFC4E6 is nowhere near either.
// Darkening hiragana/katakana/checker to roughly #8E7BB8 / #8F8B80 would clear
// 3:1 while staying inside the 藤 and 鼠 families, and is the fix if that day comes;
// it is deliberately NOT applied now, because it would cost the lightest-shade
// reading the script-track argument above depends on.
export const ACCENT = {
  hiragana: "#CFC4E6",
  katakana: "#A493CE",
  grammar: "#2F6F6B",
  kanji: "#5B4A7D",
  vocabulary: "#8A5A3B",
  checker: "#C9C6BE",
};
