#!/usr/bin/env python3
"""Derive verb classes for every ledger word and splice VERB_DATA into
vocabulary-module.jsx.

WHY DERIVED: conjugation class is a dictionary fact. UniDic's cType gives
五段-Х行 / 一段 / サ変 / カ変 directly, and — the part that matters
pedagogically — classifies the fake-ichidan traps 帰る・入る・知る as 五段,
which is the distinction sb-verbtypes teaches. Nothing here is authored.

Emits verb-classes-v1.json (provenance) and splices a VERB_DATA const between
its own markers. Census-guarded like every splicer since the ledger bug.
"""
import json, re, sys
import fugashi

HERE = "/sessions/adoring-upbeat-mayer/mnt/Naoshi - Japanese Learning"
MOD = f"{HERE}/vocabulary-module.jsx"
BEGIN = "// ————— VERB_DATA (VD-BEGIN) —————"
END = "// ————— VD-END —————"

ROW = {"カ": "ku", "ガ": "gu", "サ": "su", "タ": "tsu", "ナ": "nu",
       "バ": "bu", "マ": "mu", "ラ": "ru", "ワア": "u", "ワ": "u", "ア": "u"}

def classify():
    t = fugashi.Tagger()
    ledger = json.load(open(f"{HERE}/word-ledger-v1.json", encoding="utf-8"))
    words = ledger["words"] if isinstance(ledger, dict) and "words" in ledger else ledger
    if isinstance(words, dict):
        words = list(words.keys())
    else:
        words = [w["written"] if isinstance(w, dict) else w for w in words]

    out = {}
    for w in sorted(set(words)):
        toks = list(t(w))
        if not toks:
            continue
        last = toks[-1]
        f = last.feature
        if f.pos1 != "動詞":
            continue
        # Only dictionary-form entries conjugate on a card: the word must END
        # with the verb's own dictionary form (so 雨が降る yes, がんばれ no).
        base = f.orthBase or last.surface
        if not w.endswith(base):
            continue
        ct = f.cType or ""
        if "サ行変格" in ct:
            cls = "suru"
        elif "カ行変格" in ct:
            cls = "kuru"
        elif "一段" in ct:
            cls = "ichidan"
        elif "五段" in ct:
            m = re.search(r"五段-(\w+?)行", ct)
            row = ROW.get(m.group(1)) if m else None
            if not row:
                sys.exit(f"FAIL: unmapped godan row {ct!r} for {w}")
            cls = "godan-" + row
        else:
            continue
        out[w] = {"cls": cls, "base": base}

    # する-compound nouns (勉強する style) conjugate on する; record the stem.
    for w in list(out):
        if out[w]["cls"] == "suru" and w != "する":
            out[w]["stem"] = w[: -len("する")]
    return out

def main():
    data = classify()
    known_traps = [w for w in data if data[w]["cls"] == "godan-ru"
                   and re.search(r"[いえきけしせちてにねひへみめりれぎげじぜびべ]る$", w)]
    print(f"{len(data)} verbs classified; godan-ru traps present: {known_traps}")
    if not any(w.endswith("帰る") for w in data):
        sys.exit("FAIL: 帰る missing — the trap the design depends on")

    json.dump({"source": "UniDic via fugashi (cType) — derived, not authored",
               "count": len(data), "verbs": data},
              open(f"{HERE}/verb-classes-v1.json", "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)

    pairs = ",\n".join(f"  {json.dumps(w, ensure_ascii=False)}: "
                       f"{json.dumps(v, ensure_ascii=False)}"
                       for w, v in data.items())
    block = "\n".join([
        BEGIN,
        "// GENERATED by build-verb-data.py from UniDic — do not hand-edit; re-run.",
        "// cls decides the conjugation rule; the fake-ichidan traps (帰る 入る 知る)",
        "// arrive as godan-ru from the dictionary, not from anyone's judgement.",
        f"const VERB_DATA = {{\n{pairs},\n}};",
        END,
    ])

    s = open(MOD, encoding="utf-8").read()
    if BEGIN in s:
        s = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, s, flags=re.S)
    else:
        anchor = s.find("const T = {")
        s = s[:anchor] + block + "\n\n" + s[anchor:]
    open(MOD, "w", encoding="utf-8").write(s)

    # census
    got = len(re.findall(r"^  \"", s[s.index(BEGIN):s.index(END)], flags=re.M))
    if got != len(data):
        sys.exit(f"FAIL census: spliced {got}, classified {len(data)}")
    print(f"spliced VERB_DATA ({got} verbs), census OK")

if __name__ == "__main__":
    main()
