#!/usr/bin/env python3
"""Splice VOCAB_SCENES from vocab-scenes-v1.json into vocabulary-module.jsx.

Same pattern as build-mca-render.py: marker-delimited const, census-guarded.
Also verifies every scene's word EXISTS in the module's WORDS list — a scene
keyed to a word no card renders is the mca reachability bug again, and this
script refuses to write it.
"""
import json, re, sys
from pathlib import Path

# Audit 2026-08-23 §6.3: this was a hardcoded sandbox path from a session that
# no longer exists, so the script raised FileNotFoundError in every new one.
HERE = Path(__file__).resolve().parent
MOD = HERE / "vocabulary-module.jsx"
BEGIN = "// ————— Word scenes (SC-BEGIN) —————"
END = "// ————— SC-END —————"

d = json.load(open(f"{HERE}/vocab-scenes-v1.json", encoding="utf-8"))
scenes = d["scenes"]
mod = open(MOD, encoding="utf-8").read()
words = set(re.findall(r'\{w:"([^"]+)"', mod))

orphans = [w for w in scenes if w not in words]
if orphans:
    sys.exit(f"FAIL: scenes keyed to words not in WORDS: {orphans} — re-anchor or add the words first.")
newjp = [w for w, s in scenes.items() if s["src"] == "new"]
print(f"{len(scenes)} scenes, {len(newjp)} with NEW Japanese (reviewer): {' '.join(newjp)}")

pairs = ",\n".join(
    f"  {json.dumps(w, ensure_ascii=False)}: {json.dumps({k: s[k] for k in ('scene','jp','en')}, ensure_ascii=False)}"
    for w, s in scenes.items())
block = "\n".join([
    BEGIN,
    "// GENERATED by build-scenes-render.py from vocab-scenes-v1.json — re-run, don't edit.",
    "// Vignettes are fiction (no factual claims). JP lines marked src:'new' in the",
    "// source file are NEW Japanese awaiting reviewer sign-off; the rest are reused",
    "// from grammar examples already in the review queue.",
    f"const VOCAB_SCENES = {{\n{pairs},\n}};",
    END,
])

if BEGIN in mod:
    mod = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, mod, flags=re.S)
else:
    anchor = mod.find("const T = {")
    mod = mod[:anchor] + block + "\n\n" + mod[anchor:]
open(MOD, "w", encoding="utf-8").write(mod)

got = len(re.findall(r"^  \"", mod[mod.index(BEGIN):mod.index(END)], flags=re.M))
if got != len(scenes):
    sys.exit(f"FAIL census: spliced {got}, expected {len(scenes)}")
print(f"spliced VOCAB_SCENES ({got}), census OK")
