#!/usr/bin/env python3
"""Extract the tracing engine from kanji-module.jsx and share it, rather than
duplicating it.

WHY THIS EXISTS. The Trace → Guided → Blank engine, its per-stroke scoring, the
direction and out-of-order detection, and the KanjiVG stroke paths all live in
`kanji-module.jsx`. The vocabulary module needs the same engine. Single-file
artifacts cannot import, so the choice was: duplicate it, or generate it.

Duplicating would give two engines that drift apart, and the handwriting floor
is calibrated once and shared through `tsumiki-stroke-data-v1` — two scoring
implementations would calibrate against each other's mistakes. So: ONE source
of truth (the kanji module), extracted mechanically at build time.

The engine turns out to be cleanly separable — 197 lines depending on exactly
four module-level constants (STROKE_BOX, SD_KEY, CAL_MIN/CAL_KEEP/LOG_*, and
STROKES). Nothing else. That is why this is worth doing rather than a rewrite.

SCOPE. Only stroke data for characters the vocabulary module can actually reach
is emitted — the kanji appearing in taught words. Shipping all 63 would put
~28 KB of unreachable paths into the artifact.

Outputs: shared-stroke-engine.js, and a splice into vocabulary-module.jsx
between its ENGINE markers. Re-run after any change to the kanji module's
engine or stroke data. Does NOT modify kanji-module.jsx.
"""
import json, pathlib, re

HERE = pathlib.Path(__file__).parent
KMOD = (HERE / "kanji-module.jsx").read_text(encoding="utf-8")
VDATA = json.loads((HERE / "vocab-data-v1.json").read_text(encoding="utf-8"))

# ---- which characters does the vocabulary module need? ----
needed = sorted({c for w in VDATA["words"] if w["s"] for c in w["k"]})

# ---- pull the stroke table, filtered ----
m = re.search(r"const STROKES = \{", KMOD)
i, depth = m.end(), 1
while depth:
    if KMOD[i] == "{": depth += 1
    elif KMOD[i] == "}": depth -= 1
    i += 1
strokes_src = KMOD[m.start():i]
paths = dict(re.findall(r'"(.)":\s*(\[[^\]]*\])', strokes_src))
missing = [c for c in needed if c not in paths]
kept = {c: paths[c] for c in needed if c in paths}

# ---- pull the engine ----
start = KMOD.index("function strokeStart")
# Find the brace that opens StrokePractice's BODY, not the one that opens its
# destructured parameter object. Walk the parameter list to its closing paren
# first. (The naive `index("{", j)` grabs `{ chars, modId, ... }` and truncates
# the function to its signature — which is a syntax error, caught by the build
# check rather than by inspection.)
j = KMOD.index("function StrokePractice")
p = KMOD.index("(", j)
depth, q = 1, p + 1
while depth:
    if KMOD[q] == "(": depth += 1
    elif KMOD[q] == ")": depth -= 1
    q += 1
k = KMOD.index("{", q) + 1
depth = 1
while depth:
    if KMOD[k] == "{": depth += 1
    elif KMOD[k] == "}": depth -= 1
    k += 1
engine = KMOD[start:k]
assert engine.count("function ") >= 6, "engine extraction lost functions"
assert "StrokePractice" in engine and engine.rstrip().endswith("}"), "engine truncated"

n_paths = sum(len(re.findall(r'"[Mm]', v)) for v in kept.values())

# Only prepend constants the extracted engine does not already carry. CAL_MIN
# and friends are declared *inside* the extracted range; STROKE_BOX and SD_KEY
# are declared above it. Emitting either twice is a redeclaration error.
prelude = []
for decl in (re.search(r"const STROKE_BOX = [^\n]*\n", KMOD).group(0).rstrip(),
             'const SD_KEY = "tsumiki-stroke-data-v1";',
             re.search(r"const CAL_MIN = [^\n]*\n", KMOD).group(0).rstrip()):
    name = decl.split()[1]
    if not re.search(r"\bconst\s+" + re.escape(name) + r"\b", engine):
        prelude.append(decl)

out = [
    "// ————— Shared stroke engine —————",
    "// GENERATED by build-shared-stroke-engine.py from kanji-module.jsx.",
    "// DO NOT HAND-EDIT. Edit the kanji module and re-run, or the two drift.",
    "//",
    "// The kanji module is the single source of truth for the Trace → Guided →",
    "// Blank engine, per-stroke scoring, direction and out-of-order detection.",
    "// Calibration is shared through `tsumiki-stroke-data-v1`, so the handwriting floor",
    "// a learner sets in one module applies in the other without recalibrating.",
    "//",
    "// KanjiVG (Ulrich Apel), CC BY-SA 3.0 — http://kanjivg.tagaini.net",
    f"// {len(kept)} characters, {n_paths} paths"
    " — only those reachable through taught vocabulary.",
    "",
    *prelude,
    "",
    "const STROKES = {",
]
out += [f'  "{c}": {p},' for c, p in kept.items()]
out += ["};", "", engine]

blob = "\n".join(out) + "\n"
(HERE / "shared-stroke-engine.js").write_text(blob, encoding="utf-8")

# ---- splice into the vocabulary module ----
vm = HERE / "vocabulary-module.jsx"
spliced = False
if vm.exists():
    src = vm.read_text(encoding="utf-8")
    A, B = "// @@ENGINE-START@@", "// @@ENGINE-END@@"
    if A in src and B in src:
        pre, rest = src.split(A, 1)
        _, post = rest.split(B, 1)
        vm.write_text(pre + A + "\n" + blob + B + post, encoding="utf-8")
        spliced = True

# ---- sync the kana modules' engine copies, function by function ----
# The kana modules keep their OWN stroke tables (177 kana paths) and their own
# everything else — only the engine functions are replaced, in place, one at a
# time. A contiguous splice is impossible there because their engine sits in two
# separate regions with ~32 KB of unrelated code between them.
#
# Safe to overwrite because the engine is meant to be identical: calibration is
# shared through `tsumiki-stroke-data-v1` precisely so a floor set in hiragana applies
# in kanji. Two modules sharing a calibration key while scoring differently is
# the bug this prevents.
ENGINE_FNS = ["strokeStart", "resample", "samplePath", "scoreStroke",
              "tolerancesFor", "thinPoints"]

def fn_span(s, name):
    i = s.find("function " + name)
    if i < 0: return None
    j = s.index("{", i); d, k = 1, j + 1
    while d:
        if s[k] == "{": d += 1
        elif s[k] == "}": d -= 1
        k += 1
    return i, k

canon = {}
for fn in ENGINE_FNS:
    sp = fn_span(KMOD, fn)
    if sp: canon[fn] = KMOD[sp[0]:sp[1]]

synced = {}
for target in ("hiragana-module.jsx", "katakana-module.jsx"):
    tp = HERE / target
    if not tp.exists(): continue
    t = tp.read_text(encoding="utf-8")
    changed = []
    for fn, src_body in canon.items():
        sp = fn_span(t, fn)
        if not sp: continue
        cur = t[sp[0]:sp[1]]
        if cur != src_body:
            t = t[:sp[0]] + src_body + t[sp[1]:]
            changed.append(fn)
    if changed:
        tp.write_text(t, encoding="utf-8")
    synced[target] = changed

print(f"characters needed by vocabulary module: {len(needed)}")
print(f"  stroke data found for : {len(kept)}")
if missing:
    print(f"  ⚠ NO STROKE DATA FOR : {'、'.join(missing)}")
    print("    (expected for 言 — promoted to the syllabus but never authored;")
    print("     the vocabulary module hides writing practice for these.)")
print(f"engine: {engine.count(chr(10))} lines")
print(f"wrote shared-stroke-engine.js ({len(blob):,} bytes)")
print("spliced into vocabulary-module.jsx" if spliced else "⚠ markers not found — not spliced")
for m, ch in synced.items():
    print(f"synced {m}: " + (", ".join(ch) if ch else "already identical"))
