#!/usr/bin/env python3
"""Generate the Vite app from the four static modules, with shared code hoisted.

WHY GENERATE RATHER THAN CONVERT. The single-file artifacts must keep working —
the reviewer is grading through the published checker, and the kana modules went
to the voice contributor as standalone HTML. Converting them in place would break
the eval path. So the artifacts stay the source of truth and this derives an
importing version of each. Re-runnable; the artifacts are never modified.

DEDUPLICATION. A first version left every module carrying its own design tokens
and its own copy of the stroke engine, on the grounds that hoisting mechanically
was risky. Lloyd pushed back, correctly: the shared blocks are byte-identical
right now — the drift check proves it — and that is the cheapest moment this will
ever be. Every session that passes risks real divergence. Building a multi-file
project and keeping single-file duplication is the worst of both.

So tokens, the engine, the shared constants and the storage helpers are hoisted
into src/lib/ and imported. Each module keeps its own progress KEY, its own
stroke data, and everything genuinely its own.

THE ONE DESIGN PROBLEM. StrokeView and StrokePractice each read a module-level
STROKES table — once apiece. Merging all three tables into one shared import
would work (kana and kanji key sets are disjoint) but every module would then
download ~100 KB of paths it never draws, undoing the code-splitting that keeps
first load at 49 KB. So src/lib/strokeData.js is a REGISTRY: each module imports
its own data file, that file registers itself on load, and the engine reads the
merged table at render time. Splitting preserved, no call sites changed.

STATIC BY CONSTRUCTION. The API function body is REMOVED, not gated. A first
check that tried to prove the gate held threw two false positives — the tell that
the property was too subtle to assert. "Unreachable because a flag is false" is a
promise about control flow; a static build should make it a promise about the
bundle.
"""
import re, pathlib, sys

HERE = pathlib.Path(__file__).parent
APP = HERE / "naoshi-app"
SRC = APP / "src"
LIB = SRC / "lib"
DATA = SRC / "data"
MODDIR = SRC / "modules"
for d in (LIB, DATA, MODDIR): d.mkdir(parents=True, exist_ok=True)

MODULES = [
    ("hiragana-module.jsx",   "Hiragana.jsx",   "HiraganaModule",   "Hiragana",   "ひらがな"),
    ("katakana-module.jsx",   "Katakana.jsx",   "KatakanaModule",   "Katakana",   "カタカナ"),
    ("kanji-module.jsx",      "Kanji.jsx",      "KanjiModule",      "Kanji",      "漢字"),
    ("vocabulary-module.jsx", "Vocabulary.jsx", "VocabularyModule", "Vocabulary", "ことば"),
]
ENGINE_FNS = ["strokeStart", "StrokeView", "resample", "samplePath", "scoreStroke",
              "tolerancesFor", "thinPoints", "useStrokeData", "StrokePractice"]
SHARED_CONSTS = ["TOL", "STROKE_BOX", "SD_KEY", "CAL_MIN", "CAL_KEEP", "LOG_KEEP", "LOG_PTS"]

problems = []
CANON = (HERE / "kanji-module.jsx").read_text(encoding="utf-8")


def brace_span(text, pat):
    m = re.search(pat, text)
    if not m: return None
    i = m.end() - 1
    while text[i] != "{": i += 1
    d, k = 1, i + 1
    while d:
        if text[k] == "{": d += 1
        elif text[k] == "}": d -= 1
        k += 1
    return m.start(), k


def fn_span(text, name):
    i = text.find("function " + name)
    if i < 0: return None
    p = text.index("(", i); d, q = 1, p + 1
    while d:
        if text[q] == "(": d += 1
        elif text[q] == ")": d -= 1
        q += 1
    j = text.index("{", q); d, k = 1, j + 1
    while d:
        if text[k] == "{": d += 1
        elif text[k] == "}": d -= 1
        k += 1
    return i, k


# ── design tokens: union across modules ──────────────────────────────────────
tok = {}
for src_name, *_ in MODULES:
    t = (HERE / src_name).read_text(encoding="utf-8")
    sp = brace_span(t, r"const T = \{")
    if not sp: continue
    for k, v in re.findall(r"(\w+):\s*('[^']*'|\"[^\"]*\")", t[sp[0]:sp[1]]):
        if k in tok and tok[k] != v:
            problems.append(f"design token `{k}` conflicts: {tok[k]} vs {v} ({src_name})")
        tok[k] = v

(LIB / "tokens.js").write_text(
    "// GENERATED by build-vite-app.py — the union of every module's design tokens.\n"
    "// They were identical apart from additions. A key holding two different values\n"
    "// fails the build rather than silently picking one.\n"
    "export const T = {\n"
    + "".join(f"  {k}: {v},\n" for k, v in sorted(tok.items()))
    + "};\n", encoding="utf-8")

# ── stroke data registry ─────────────────────────────────────────────────────
(LIB / "strokeData.js").write_text(
    "// GENERATED by build-vite-app.py.\n"
    "// A REGISTRY rather than one merged table. Merging every stroke path would\n"
    "// work — the kana and kanji key sets are disjoint — but each module would then\n"
    "// download ~100 KB of paths it never draws, undoing the code-splitting that\n"
    "// keeps first load at 49 KB. Each module imports its own data file, that file\n"
    "// registers on load, and the engine reads the merged table at render time.\n"
    "export const STROKES = {};\n"
    "export function registerStrokes(table) { Object.assign(STROKES, table); }\n",
    encoding="utf-8")

# ── the engine, taken once from the canonical module ─────────────────────────
parts = []
for fn in ENGINE_FNS:
    sp = fn_span(CANON, fn)
    if sp: parts.append(CANON[sp[0]:sp[1]])
    else: problems.append(f"engine function {fn} not found in kanji-module.jsx")

consts = []
for pat in [r"const TOL = [^\n]*", r"const STROKE_BOX = [^\n]*",
            r'const SD_KEY = "stroke-data-v1";', r"const CAL_MIN = [^\n]*"]:
    m = re.search(pat, CANON)
    if m: consts.append(m.group(0).split("//")[0].rstrip())

(LIB / "strokeEngine.jsx").write_text(
    "// GENERATED by build-vite-app.py from kanji-module.jsx — ONE implementation.\n"
    "// Previously hand-copied into four modules. Calibration is shared through\n"
    "// stroke-data-v1, so two scoring implementations would end up calibrating\n"
    "// against each other's mistakes. Hoisting removes that class of bug rather\n"
    "// than merely watching for it.\n"
    "// KanjiVG (Ulrich Apel), CC BY-SA 3.0 — http://kanjivg.tagaini.net\n"
    'import { useState, useEffect, useRef } from "react";\n'
    'import { T } from "./tokens.js";\n'
    'import { STROKES } from "./strokeData.js";\n\n'
    + "\n".join(consts) + "\n\n"
    + "\n\n".join(parts) + "\n\n"
    + "export { " + ", ".join(ENGINE_FNS + ["TOL", "STROKE_BOX", "SD_KEY"]) + " };\n",
    encoding="utf-8")

# ── storage helpers, shared ──────────────────────────────────────────────────
(LIB / "json.js").write_text(
    "// GENERATED by build-vite-app.py — the loadJSON/saveJSON pair every module\n"
    "// carried its own identical copy of.\n"
    "export async function loadJSON(key, fallback) {\n"
    "  try { const r = await window.storage.get(key); return r ? JSON.parse(r.value) : fallback; }\n"
    "  catch { return fallback; }\n"
    "}\n"
    "export async function saveJSON(key, v) {\n"
    "  try { await window.storage.set(key, JSON.stringify(v)); }\n"
    "  catch (e) { console.error"'("save failed: " + key, e); }\n'
    "}\n", encoding="utf-8")

# ── per-module transform ─────────────────────────────────────────────────────
stats = []
for src_name, out_name, comp, label, jp in MODULES:
    src = (HERE / src_name).read_text(encoding="utf-8")
    before = len(src)

    # strip the API implementation entirely — see module docstring
    if re.search(r"async function callClaude", src):
        src = re.sub(r"async function callClaude\([^)]*\) \{.*?\n\}",
                     "async function callClaude() {\n"
                     "  // Removed by build-vite-app.py. This build is static: no API key,\n"
                     "  // no network, no cost. Features needing the grader are disabled\n"
                     "  // above rather than failing here.\n"
                     '  throw new Error("grader-unavailable-in-static-build");\n'
                     "}", src, count=1, flags=re.S)

    # extract this module's stroke table into its own data file, then register it
    sp = brace_span(src, r"const STROKES = \{")
    data_import = ""
    if sp:
        table = src[sp[0]:sp[1]]
        stem = out_name.replace(".jsx", "").lower()
        (DATA / f"strokes-{stem}.js").write_text(
            f"// GENERATED by build-vite-app.py from {src_name}.\n"
            "// KanjiVG (Ulrich Apel), CC BY-SA 3.0 — http://kanjivg.tagaini.net\n"
            "// Registers itself so this module ships only the characters it teaches.\n"
            'import { registerStrokes } from "../lib/strokeData.js";\n'
            + table.replace("const STROKES =", "const TABLE =", 1) + ";\n"
            "registerStrokes(TABLE);\n", encoding="utf-8")
        src = src[:sp[0]] + src[sp[1] + 1:]
        data_import = f'import "../data/strokes-{stem}.js";\n'

    # strip hoisted blocks
    sp = brace_span(src, r"const T = \{")
    if sp: src = src[:sp[0]] + src[sp[1] + 1:]
    for fn in ENGINE_FNS:
        sp = fn_span(src, fn)
        if sp: src = src[:sp[0]] + src[sp[1]:]
    for fn in ("loadJSON", "saveJSON"):
        sp = fn_span(src, fn)
        if sp:
            start = sp[0]
            if src[max(0, start - 6):start].strip().endswith("async"):
                start = src.rindex("async", 0, start)
            src = src[:start] + src[sp[1]:]
    for c in SHARED_CONSTS:
        src = re.sub(r"^const " + c + r" = [^\n]*\n", "", src, flags=re.M)

    used_engine = [f for f in ENGINE_FNS if re.search(r"\b" + f + r"\b", src)]
    used_const = [c for c in ("TOL", "STROKE_BOX", "SD_KEY") if re.search(r"\b" + c + r"\b", src)]
    # Modules reference STROKES outside the engine too — e.g. filtering which
    # characters actually have paths before offering writing practice. Stripping
    # the table without importing the registry left a ReferenceError that only a
    # render test catches; the build compiles fine.
    needs_strokes = bool(re.search(r"\bSTROKES\b", src))
    used_json = [f for f in ("loadJSON", "saveJSON") if re.search(r"\b" + f + r"\(", src)]
    needs_T = bool(re.search(r"\bT\.", src))

    for pattern, why in [(r"api\.anthropic\.com", "API endpoint"),
                         (r"ANTHROPIC_API_KEY", "API key reference")]:
        for m in re.finditer(pattern, src):
            problems.append(f"{src_name}:{src[:m.start()].count(chr(10)) + 1} — {why} survived stripping")

    hooks = sorted({h for h in ["useState", "useEffect", "useRef", "useMemo",
                                "useCallback", "useReducer"] if re.search(r"\b" + h + r"\s*\(", src)})
    src = re.sub(r'^import \{[^}]*\} from "react";\s*\n', "", src, count=1, flags=re.M)

    header = [
        f"// GENERATED from {src_name} by build-vite-app.py — do not hand-edit.",
        "// Edit the source module and re-run. The single-file artifact stays the",
        "// source of truth so the reviewer's grading path keeps working.",
        f'import {{ {", ".join(hooks)} }} from "react";' if hooks else "",
        'import { installStorage } from "../lib/storage.js";',
    ]
    if needs_T: header.append('import { T } from "../lib/tokens.js";')
    if used_engine or used_const:
        header.append('import { ' + ", ".join(used_engine + used_const) + ' } from "../lib/strokeEngine.jsx";')
    if used_json:
        header.append('import { ' + ", ".join(used_json) + ' } from "../lib/json.js";')
    if needs_strokes: header.append('import { STROKES } from "../lib/strokeData.js";')
    if data_import: header.append(data_import.rstrip())
    header.append("installStorage();\n")

    out = "\n".join(h for h in header if h) + "\n" + src
    (MODDIR / out_name).write_text(out, encoding="utf-8")
    stats.append((out_name, before, len(out)))

if problems:
    print("REFUSING TO BUILD:")
    for p in problems: print("  " + p)
    sys.exit(1)

# ── app shell ────────────────────────────────────────────────────────────────
nav = ",\n  ".join(f'{{ id: "{c[3].lower()}", label: "{c[3]}", jp: "{c[4]}", Comp: {c[2]} }}'
                   for c in MODULES)
imports = "\n".join(f'const {c[2]} = lazy(() => import("./modules/{c[1]}"));' for c in MODULES)

(SRC / "App.jsx").write_text('''// GENERATED by build-vite-app.py — do not hand-edit.
import { useState, lazy, Suspense } from "react";
import { downloadProgress, importProgress } from "./lib/storage.js";
import { T } from "./lib/tokens.js";
''' + imports + '''

const MODULES = [
  ''' + nav + '''
];

export default function App() {
  // Remember which module they were in. One less thing to re-find each visit.
  const [active, setActive] = useState(
    () => localStorage.getItem("naoshi-last-module") || MODULES[0].id);
  const [msg, setMsg] = useState(null);
  const current = MODULES.find((m) => m.id === active) || MODULES[0];

  const go = (id) => { setActive(id); localStorage.setItem("naoshi-last-module", id); };

  const restore = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const r = new FileReader();
    r.onload = () => setMsg(importProgress(String(r.result)).message);
    r.readAsText(file);
    e.target.value = "";
  };

  const btn = {
    background: "none", border: "none", cursor: "pointer",
    padding: "8px 10px", borderRadius: 8,
  };

  return (
    <div style={{ background: T.paper, minHeight: "100vh", fontFamily: T.uiFont }}>
      <header style={{
        background: T.sheet, borderBottom: `1px solid ${T.hairline}`,
        position: "sticky", top: 0, zIndex: 10,
      }}>
        <div style={{
          maxWidth: 900, margin: "0 auto", padding: "10px 16px",
          display: "flex", alignItems: "center", gap: 4, flexWrap: "wrap",
        }}>
          <span style={{ font: `600 17px ${T.jpFont}`, color: T.ink, marginRight: 14 }}>直</span>
          {MODULES.map((m) => (
            <button key={m.id} onClick={() => go(m.id)} style={{
              ...btn,
              font: `${active === m.id ? 600 : 400} 14px ${T.uiFont}`,
              color: active === m.id ? T.ink : T.sub,
              borderBottom: `2px solid ${active === m.id ? T.ink : "transparent"}`,
            }}>
              {m.label}
              <span style={{ font: `13px ${T.jpFont}`, color: T.sub, marginLeft: 6 }}>{m.jp}</span>
            </button>
          ))}
          <span style={{ flex: 1 }} />
          <button onClick={downloadProgress} title="Save your progress to a file" style={{
            ...btn, border: `1px solid ${T.hairline}`, padding: "6px 12px",
            font: `13px ${T.uiFont}`, color: T.sub,
          }}>Save progress</button>
          <label style={{
            border: `1px solid ${T.hairline}`, borderRadius: 8, padding: "6px 12px",
            cursor: "pointer", font: `13px ${T.uiFont}`, color: T.sub,
          }}>
            Restore
            <input type="file" accept="application/json" onChange={restore}
                   style={{ display: "none" }} />
          </label>
        </div>
        {msg && (
          <div role="status" style={{
            maxWidth: 900, margin: "0 auto", padding: "0 16px 10px",
            font: `13px ${T.uiFont}`, color: T.note,
          }}>{msg}</div>
        )}
      </header>

      <main style={{ maxWidth: 900, margin: "0 auto" }}>
        <Suspense fallback={
          <p style={{ padding: "40px 18px", color: T.sub, font: `14px ${T.uiFont}` }}>Loading…</p>
        }>
          <current.Comp />
        </Suspense>
      </main>
    </div>
  );
}
''', encoding="utf-8")

(SRC / "main.jsx").write_text('''// GENERATED by build-vite-app.py — do not hand-edit.
import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { installStorage } from "./lib/storage.js";
import App from "./App.jsx";

installStorage();
createRoot(document.getElementById("root")).render(<StrictMode><App /></StrictMode>);
''', encoding="utf-8")

saved = sum(b - a for _, b, a in stats)
print(f"lib: tokens ({len(tok)} keys), engine ({len(parts)} functions), registry, json helpers")
for name, b, a in stats:
    print(f"  {name:18s} {b:>8,} → {a:>8,}  ({b - a:+,})")
print(f"\nduplication removed from modules: {saved:,} bytes")
print("verified: no API endpoint or key reference in any generated file")
