#!/usr/bin/env python3
"""Splice the micro-anecdote texts into the two modules that render them.

Reads micro-anecdotes-v1.json and writes a MICRO_ANECDOTES const into
grammar-module.jsx and vocabulary-module.jsx, between its own markers.

WHY A LOOKUP KEYED ON THE WORD, NOT ON (step, word).
Every anecdote anchors to a word in a named step's bank, and check-mca.py
verifies that anchor against the real bank. But the ANCHOR is an authoring
constraint — it decides where an item may be written and enforces the density
cap — while the RENDER question is different: the learner has tapped a word and
wants to know about it. All 33 anchor words are distinct, so the two keyings
can only differ in one way: keying on the word also shows the anecdote when the
same word is tapped in a LATER step, or in the mixed Review Challenge, where no
single step is in context at all. That is the better behaviour and it is the
same text either way. The uniqueness is asserted below, so if a future wave
ever anchors one word twice this script fails instead of silently dropping one.

Idempotent. Re-run after editing micro-anecdotes-v1.json, then re-run
build-vite-app.py to mirror both modules into naoshi-app/.
"""

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE / "micro-anecdotes-v1.json"
TARGETS = [HERE / "grammar-module.jsx", HERE / "vocabulary-module.jsx"]

BEGIN = "// ————— Micro cultural anecdotes (MCA-BEGIN) —————"
END = "// ————— MCA-END —————"

WORD_CAP = 110  # the design's hard cap; check-mca.py owns the 45–90 target range


def build_block(items):
    words = [it["anchor"]["word"] for it in items]
    if len(set(words)) != len(words):
        dupes = sorted({w for w in words if words.count(w) > 1})
        sys.exit(
            f"FAIL: anchor words are not unique ({', '.join(dupes)}). The render "
            "keys on the word alone — see this script's docstring. Either give the "
            "duplicated word one anecdote, or change the key to (step, word) in "
            "BOTH modules before re-running."
        )

    over = [
        (it["id"], len(it["text"].split()))
        for it in items
        if len(it["text"].split()) > WORD_CAP
    ]
    if over:
        sys.exit(f"FAIL: over the {WORD_CAP}-word hard cap: {over}")

    pairs = ",\n".join(
        f"  {json.dumps(it['anchor']['word'], ensure_ascii=False)}: "
        f"{json.dumps(it['text'], ensure_ascii=False)}"
        for it in sorted(items, key=lambda i: i["id"])
    )
    return "\n".join([
        BEGIN,
        "// GENERATED by build-mca-render.py from micro-anecdotes-v1.json — do not",
        "// hand-edit; re-run instead. Keyed on the anchor word (see that script).",
        "//",
        "// ⚠️ AI-AUTHORED AND NOT REVIEWER-VERIFIED. These are claims about Japan,",
        "// which is the one content class in this repo that NO automated check can",
        "// validate — check-mca.py verifies anchors, caps and romaji, never truth.",
        "// Reviewer batch J. Until that comes back, this text is unverified.",
        "//",
        "// No read-state, no dismiss control, no counts — by design (mca-design-v1.md).",
        f"const MICRO_ANECDOTES = {{\n{pairs},\n}};",
        END,
    ])


def splice(path, block):
    text = path.read_text(encoding="utf-8")
    if BEGIN in text:
        if END not in text:
            sys.exit(f"FAIL: {path.name} has an opening MCA marker and no closing one.")
        new = re.sub(
            re.escape(BEGIN) + r".*?" + re.escape(END),
            lambda _: block,
            text,
            flags=re.S,
        )
    else:
        # First install: sit the block directly above the theme-token const so it
        # is defined before any component that reads it.
        anchor = re.search(r"^const T = \{", text, flags=re.M)
        if not anchor:
            sys.exit(f"FAIL: no `const T = {{` in {path.name} to anchor the block above.")
        new = text[: anchor.start()] + block + "\n\n" + text[anchor.start():]

    if new == text:
        print(f"  {path.name}: unchanged")
        return False
    path.write_text(new, encoding="utf-8")
    print(f"  {path.name}: block written ({len(block)} chars)")
    return True


def main():
    items = json.load(SRC.open(encoding="utf-8"))["items"]
    block = build_block(items)
    print(f"{len(items)} anecdotes, {len(block)} chars of block")
    for t in TARGETS:
        splice(t, block)

    # Census, the guard the word ledger learned the hard way: a splice that
    # writes nothing must not be able to look like a splice with nothing to say.
    for t in TARGETS:
        text = t.read_text(encoding="utf-8")
        found = len(re.findall(r"^  \"", text[text.index(BEGIN): text.index(END)], flags=re.M))
        if found != len(items):
            sys.exit(f"FAIL: {t.name} carries {found} anecdotes, expected {len(items)}.")
        print(f"  {t.name}: census OK ({found})")

    print("\nNext: re-run build-vite-app.py to mirror both modules into naoshi-app/.")


if __name__ == "__main__":
    main()
