#!/usr/bin/env python3
"""Generate the checker endpoint's server-side prompt module.

WHY A GENERATOR. The system prompt has exactly one home: naoshi-prototype.jsx.
bakeoff-harness.py already reads it from there rather than keeping a copy, and
for the same reason — the bake-off's verdict is only about the prompt that is
actually in the file. An endpoint carrying its own transcribed copy would drift
from the measured prompt within a session, and nothing would say so.

So this writes supabase/functions/check/_prompt.ts and nothing else. The
handler in index.ts is ordinary hand-maintained code that imports from it.

WHY THE PROMPT IS NOT IN THE BROWSER BUNDLE. It is the product. Session 12's
purity check caught kanji's SENTENCE_SYSTEM shipping to the client, and the
same rule applies here with more at stake: the prompt lives server-side, in a
file the Vite build never sees. build-vite-app.py's own key/endpoint check
covers the app; this file is outside naoshi-app/ entirely.

Run after ANY edit to SYSTEM_PROMPT or SCHEMA_VERSION:
    python3 build-checker-endpoint.py
"""
import json, pathlib, re, sys

HERE = pathlib.Path(__file__).parent
SRC = HERE / "naoshi-prototype.jsx"
OUT = HERE / "supabase" / "functions" / "check" / "_prompt.ts"

src = SRC.read_text(encoding="utf-8")

m_schema = re.search(r'SCHEMA_VERSION = "([^"]+)"', src)
m_prompt = re.search(r"const SYSTEM_PROMPT = `(.*?)`;", src, re.S)
if not m_schema or not m_prompt:
    sys.exit("Could not extract SYSTEM_PROMPT / SCHEMA_VERSION from naoshi-prototype.jsx")

schema = m_schema.group(1)
prompt = m_prompt.group(1)

# The prototype's prompt is a JS template literal, so it may legitimately
# contain backticks or ${...}. Emitting it as a JSON string sidesteps every
# escaping question — JSON.stringify's output is valid TypeScript, and a
# template literal's would not reliably be.
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(
    "// GENERATED by build-checker-endpoint.py — do not hand-edit.\n"
    "// Source of truth: naoshi-prototype.jsx. Re-run the generator after any\n"
    "// prompt change; SCHEMA_VERSION is what makes a stored result traceable\n"
    "// back to the prompt that produced it.\n"
    f"export const SCHEMA_VERSION = {json.dumps(schema)};\n"
    f"export const SYSTEM_PROMPT = {json.dumps(prompt)};\n",
    encoding="utf-8",
)

# A prompt that arrives empty or truncated would fail silently at runtime as
# "the model just isn't very good today", which is the worst failure mode this
# project has. Assert loudly here instead.
if len(prompt) < 2000:
    sys.exit(f"REFUSING: extracted prompt is only {len(prompt)} chars — expected ~7k. "
             "Check the SYSTEM_PROMPT delimiters in naoshi-prototype.jsx.")
for needed in ("## Output format", '"span"', '"readings"'):
    if needed not in prompt:
        sys.exit(f"REFUSING: extracted prompt is missing {needed!r} — "
                 "the JSON contract the endpoint parses is not in it.")

print(f"wrote {OUT.relative_to(HERE)}")
print(f"  schema {schema} · prompt {len(prompt):,} chars")
print(f"  contract checks passed (output format, span, readings)")
