#!/usr/bin/env python3
"""Drift detector — the signal that says it is time to stop copying and start importing.

WHY THIS EXISTS. Six single-file modules now share code by duplication, because
artifacts cannot import. The stroke engine lives in four of them; the design
tokens in six. Today every copy is identical, so the duplication costs nothing
but disk. The moment one copy is edited and the others are not, it starts
costing correctness — silently, because nothing checks.

That moment is the answer to "when do we stitch this together." Not a date: an
event. This script watches for it.

WHAT IT COMPARES
  · the stroke engine functions (scoreStroke, samplePath, strokeStart,
    tolerancesFor, thinPoints, resample) — whitespace-normalised
  · the design token table `const T`
  · the storage helpers loadJSON / saveJSON
  · the lesson-completion block — LessonComplete() and COMPLETE_CSS, copied
    into grammar, kanji and vocabulary by e0da730 (added 2026-09-19)
  · storage KEYS, which are the real coupling: six modules read and write eight
    shared keys, and a key renamed in one place silently orphans a learner's
    progress everywhere else

Exits nonzero on drift, so it can gate the weekly audit.

NOTE ON SCOPE. `vocabulary-module.jsx` gets its engine generated by
build-shared-stroke-engine.py, so it cannot drift by hand. The kana and kanji
modules carry hand-maintained copies and can. That asymmetry is the point: one
of four is solved.
"""
import re, sys, pathlib, hashlib

HERE = pathlib.Path(__file__).parent
MODULES = ["tsumiki-prototype.jsx", "grammar-module.jsx", "kanji-module.jsx",
           "hiragana-module.jsx", "katakana-module.jsx", "vocabulary-module.jsx"]
SRC = {m: (HERE / m).read_text(encoding="utf-8") for m in MODULES if (HERE / m).exists()}

ENGINE_FNS = ["strokeStart", "resample", "samplePath", "scoreStroke",
              "tolerancesFor", "thinPoints"]

def norm(t):
    """Normalise away formatting so only SEMANTIC drift is reported.

    ⚠️ The first version of this collapsed whitespace runs but left spaces
    around operators, so `floor * 1.6` and `floor*1.6` hashed differently and
    the detector reported three engine functions as drifted when they were
    byte-for-byte equivalent code in two house styles. A drift alarm that fires
    on formatting is worse than none: it trains you to ignore it.

    Strip comments, then remove whitespace adjacent to any non-identifier
    character — which kills operator and bracket spacing without ever fusing
    two identifiers together.
    """
    t = re.sub(r"//[^\n]*", " ", t)
    t = re.sub(r"/\*.*?\*/", " ", t, flags=re.S)
    t = re.sub(r"\s+", " ", t)
    t = re.sub(r"\s*([^\w\s])\s*", r"\1", t)
    t = re.sub(r",(?=[}\])])", "", t)      # trailing commas in literals
    return t.strip()

def fn_body(s, name):
    i = s.find("function " + name)
    if i < 0: return None
    j = s.index("{", i); d, k = 1, j + 1
    while d:
        if s[k] == "{": d += 1
        elif s[k] == "}": d -= 1
        k += 1
    return norm(s[i:k])

def const_block(s, name):
    m = re.search(r"const " + name + r"\s*=\s*\{", s)
    if not m: return None
    d, k = 1, m.end()
    while d:
        if s[k] == "{": d += 1
        elif s[k] == "}": d -= 1
        k += 1
    return norm(s[m.start():k])

def line_block(s, opener, is_end):
    """Extract a top-level block BY LINE: from the line starting with `opener`
    to the first following line for which `is_end(stripped_line)` is true.

    ⚠️ WHY NOT fn_body() / const_block(). Both brace-match, and both are fooled
    by the lesson-completion block. Found by the 2026-09-19 audit:

      · `function LessonComplete({ mark = "済", ... }) {` opens its first brace
        on the DESTRUCTURED PARAMETER LIST. fn_body() closes on the end of the
        parameters and returns a 107-character signature — which is identical
        in every module by construction, so the comparison would have passed
        forever while the 2,700-byte body drifted freely underneath it.
      · COMPLETE_CSS is a template literal containing `${...}`. A brace matcher
        started on it walks off the end of the file.

    Both blocks are house-formatted at top level and end on a bare `}` or a
    bare `` `; `` on its own line, so a line scan is simpler AND harder to fool
    than a matcher that has to understand strings, template literals and JSX.
    """
    out, collecting = [], False
    for ln in s.split("\n"):
        if not collecting and ln.startswith(opener):
            collecting = True
        if collecting:
            out.append(ln.rstrip())
            if len(out) > 1 and is_end(ln.strip()):
                return norm("\n".join(out))
    return None

# Differences confirmed BY HAND to be formatting-only. A drift detector needs
# somewhere to record "a human looked at this and it is fine", or every benign
# style difference re-alarms forever and the tool gets ignored. Each entry says
# what was compared and why it is benign — never just a hash.
BENIGN = {
    "`resample()`": "kana modules brace the single-statement for-loop body; "
                    "kanji/vocabulary do not. Verified character-by-character: "
                    "the only difference is one `{`/`}` pair. Same behaviour.",
}

problems = []
lines = ["# Module drift check", ""]

def compare(label, values, expect_at_least=None):
    """values: {module: normalised_text or None}

    `expect_at_least` turns "I could not find this anywhere" into a FAILURE
    rather than a shrug. Without it, a block that gets renamed — or an extractor
    that silently stops matching — reports "nothing to compare" and the run
    still exits 0. That is the check-that-cannot-fail shape this project keeps
    getting caught by, and it is cheap to close: if a block is known to live in
    N modules, say so, and let the tool notice when it does not.
    """
    present = {m: v for m, v in values.items() if v}
    if expect_at_least is not None and len(present) < expect_at_least:
        problems.append(f"{label} — found in {len(present)} module(s), expected {expect_at_least}")
        lines.append(f"- ❌ **{label}** — **found in {len(present)} module(s), expected "
                     f"at least {expect_at_least}**: {', '.join(sorted(present)) or 'none'}")
        lines.append("    - Either the block was removed/renamed, or the extractor has "
                     "stopped matching it. Both are real; neither is a pass.")
        return
    if len(present) < 2:
        lines.append(f"- {label}: only in {list(present) or 'none'} — nothing to compare")
        return
    groups = {}
    for m, v in present.items():
        groups.setdefault(hashlib.md5(v.encode()).hexdigest()[:8], []).append(m)
    if len(groups) == 1:
        lines.append(f"- ✅ **{label}** — identical across {len(present)} modules")
    elif label in BENIGN:
        lines.append(f"- ⚪ **{label}** — {len(groups)} textual variants, "
                     f"**confirmed formatting-only**")
        lines.append(f"    - {BENIGN[label]}")
    else:
        problems.append(label)
        lines.append(f"- ❌ **{label}** — **{len(groups)} DIFFERENT VERSIONS**")
        for h, ms in sorted(groups.items(), key=lambda kv: -len(kv[1])):
            lines.append(f"    - `{h}` — {', '.join(ms)}")

lines.append("## Stroke engine")
lines.append("")
for fn in ENGINE_FNS:
    compare(f"`{fn}()`", {m: fn_body(s, fn) for m, s in SRC.items()})

lines += ["", "## Shared scaffolding", ""]
# Design tokens diverge additively (the vocabulary module added okBg). Report
# the per-key picture rather than a blunt pass/fail, and only treat a key that
# holds DIFFERENT VALUES in different modules as real drift.
tok = {}
for m, s in SRC.items():
    b = const_block(s, "T")
    if b:
        tok[m] = dict(re.findall(r'(\w+):\s*"([^"]*)"', b))
allk = sorted({k for d in tok.values() for k in d})
conflict = {k: {m: d[k] for m, d in tok.items() if k in d}
            for k in allk
            if len({d[k] for d in tok.values() if k in d}) > 1}
lines.append("")
lines.append(f"- design tokens: {len(allk)} keys across {len(tok)} modules; "
             f"**{len(conflict)} hold conflicting values**")
if conflict:
    problems.append("design tokens (conflicting values)")
    for k, vs in conflict.items():
        lines.append(f"    - ❌ `{k}` — " + "; ".join(f"{m.split('-')[0]}=`{v}`" for m, v in vs.items()))
else:
    lines.append("    - ✅ no key holds two different values — divergence is additive only")
compare("`loadJSON()`", {m: fn_body(s, "loadJSON") for m, s in SRC.items()})
compare("`saveJSON()`", {m: fn_body(s, "saveJSON") for m, s in SRC.items()})

# ---- the lesson-completion block ----
# Added 2026-09-19 by the weekly audit. e0da730 copied LessonComplete() and its
# COMPLETE_CSS into grammar, kanji and vocabulary and its commit message said
# "drift check clean" — which was true and meant nothing, because this script
# did not compare either block. The copies were identical when checked by hand;
# the gap was that nothing would have noticed if they stopped being.
#
# SCOPE is deliberately the three ROOT modules, not their tsumiki-app/src/modules/
# counterparts: this tool has only ever watched the six single-file modules, and
# the app copies arrive by splice rather than by hand (the division of labour
# recorded 2026-09-05). Three is the number to expect here; if it ever reads two,
# something was deleted or renamed and the line below says so instead of passing.
lines += ["", "## Lesson-completion block", "",
          "Copied into grammar, kanji and vocabulary rather than imported — the same",
          "duplication as the stroke engine, and the same failure mode if one is edited.", ""]
compare("`LessonComplete()`",
        {m: line_block(s, "function LessonComplete(", lambda l: l == "}") for m, s in SRC.items()},
        expect_at_least=3)
compare("`COMPLETE_CSS`",
        {m: line_block(s, "const COMPLETE_CSS", lambda l: l.endswith("`;")) for m, s in SRC.items()},
        expect_at_least=3)

# ---- storage keys: the coupling that actually breaks learners ----
lines += ["", "## Storage keys", "",
          "A key renamed in one module silently orphans that learner's progress in",
          "every other module that reads it. These are the real seams.", "",
          "| Key | Modules |", "|---|---|"]
keys = {}
for m, s in SRC.items():
    for k in set(re.findall(r'"([a-z0-9-]+-v\d)"', s)):
        keys.setdefault(k, []).append(m)
# Sort by module count descending, then by key name — the name is the tiebreak so
# the table is BYTE-STABLE between runs. Without it, ties fell out in whatever order
# set() iteration and dict insertion happened to produce, so re-running the audit
# reshuffled rows and made the report's diffs noisier than the changes they carried.
for k, ms in sorted(keys.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    mark = " ⚠️ shared" if len(ms) > 1 else ""
    lines.append(f"| `{k}` | {', '.join(sorted(ms))}{mark} |")

shared = sum(1 for ms in keys.values() if len(ms) > 1)
lines += ["", f"{shared} of {len(keys)} keys are shared across modules.", ""]


# ---- the kana sprite exists in two committed places ----
# audio/ is what the single-file artifacts and standalone builds fetch;
# tsumiki-app/public/audio/ is what the Vite app serves. Same bytes today. If the
# sprite is ever rebuilt and only one copy updated, testers and the reviewer hear
# different audio — the exact silent-divergence class this tool exists for.
import hashlib as _h
pairs = [("audio/kana-sprite.mp3", "tsumiki-app/public/audio/kana-sprite.mp3"),
         ("audio/kana-sprite.json", "tsumiki-app/public/audio/kana-sprite.json")]
lines += ["", "## Kana audio sprite", ""]
for a, b in pairs:
    pa, pb = HERE / a, HERE / b
    if not pa.exists() or not pb.exists():
        lines.append(f"- {a}: one copy missing — {pa.exists()} / {pb.exists()}")
        continue
    ha = _h.md5(pa.read_bytes()).hexdigest()[:8]
    hb = _h.md5(pb.read_bytes()).hexdigest()[:8]
    if ha == hb:
        lines.append(f"- ✅ `{pa.name}` identical in both locations (`{ha}`)")
    else:
        problems.append(f"kana sprite {pa.name} differs between copies")
        lines.append(f"- ❌ **`{pa.name}` DIFFERS** — audio/ `{ha}` vs tsumiki-app/public/audio/ `{hb}`")
lines.append("")
lines.append("If these diverge, re-run `Audio/build-kana-sprite.py` and copy the result to")
lines.append("both locations, rather than editing either by hand.")

# ---- verdict ----
lines += ["## Verdict", ""]
if problems:
    lines += [f"**DRIFT DETECTED in {len(problems)} shared block(s):** "
              + "; ".join(problems) + ".", "",
              "The copies have diverged. Whatever was fixed in one module is now",
              "absent from the others, and no test covers the gap. This is the",
              "event that says the modules should share code for real rather than",
              "by duplication — see `stitching-decision-v1.md`."]
else:
    lines += ["**No drift.** Every shared block is byte-identical across every module",
              "that carries it. The duplication is currently costing disk space and",
              "nothing else, which is why porting is not yet urgent on these grounds.",
              "",
              "Re-run after any edit to the stroke engine, the design tokens, or a",
              "storage key. The first failure here is the trigger."]

report = "\n".join(lines) + "\n"
(HERE / "module-drift-report.md").write_text(report, encoding="utf-8")
print(report)
sys.exit(1 if problems else 0)
