/* ============================================================================
   engagement-module.jsx  —  v3
   Naoshi — daily quote card, weekly rhythm target, quest chains.

   WHOLE-FILE DROP-IN. No required props. Default export.
   Data: quote-bank-v1.js (generated by build-quote-bank.py).

   ── v3 changes (Lloyd, Session 21) ───────────────────────────────────────

   • THE CARD IS NOT A REWARD. It shows on entering the app, every session,
     unconditionally. Never earned, never withheld, never a payout. v2 had it
     backwards — a card you must unlock is a card most learners never read.

   • THE CARD DOES NOT TELL YOU WHAT THE PROVERB MEANS. It offers one possible
     reading and asks you to check the Japanese yourself. Tap any word for its
     reading and gloss. This is what removes the reviewer from the loop: an
     invitation cannot be wrong the way an assertion can.

   • QUEST REWARD IS KOBAN. Chain completion pays into the shared wallet
     (`achievement-points-v1`). A room item on completion is deferred to the
     room/shop pass, per reward-system-design-v1.md §5.

   • EARLY-FINISH BONUS. Clear the three tasks before the window closes and a
     fourth appears, paying more. This is the "unwieldy for hardcore users"
     valve Lloyd asked for — it is only reachable by moving faster than the
     window, so it cannot inflate a typical learner's balance at all.

   • ACTIVE DAYS NOW REQUIRE ACTIVITY. See §5 — this was the real bug.
   ========================================================================== */

import React, { useState, useEffect, useMemo, useCallback, useRef } from "react";
import QUOTES from "./quote-bank-v1.js";

/* ---------------------------------------------------------------------------
   1. STORAGE — window.storage, matching the other five modules.
   -------------------------------------------------------------------------*/

const KEY = "engagement-v1";
const WALLET_KEY = "achievement-points-v1"; // shared with vocabulary + grammar

async function loadJSON(key, fallback) {
  try { const r = await window.storage.get(key); return r ? JSON.parse(r.value) : fallback; }
  catch { return fallback; }
}
async function saveJSON(key, v) {
  try { await window.storage.set(key, JSON.stringify(v)); }
  catch (e) { console.error("save failed: " + key, e); }
}

const BLANK = {
  activeDays: [],  // days with REAL ACTIVITY, not days the app was opened
  weekStart: null, // first day of the current 7-day window; set by ACTIVITY
  chain: null,     // { startedOn, tasks[], claimed, bonus, bonusClaimed }
  recent: [],      // recently shown quote ids
  lastSeen: null,  // last day the card rotated
};

/* ---------------------------------------------------------------------------
   2. KOBAN — the only wallet writes in this file.
   Sized against reward-system-design-v1.md: ~343/stage after the Sept 1 rate
   cut (211 vocabulary + 132 daily challenge), room capstone 300–400.
   A typical learner clears ~2 chains/week -> ~64/stage, about +19%.
   The bonus is deliberately NOT reachable by a typical learner: it requires
   finishing three tasks inside a window built for three days.
   -------------------------------------------------------------------------*/

const KOBAN = { chain: 8, bonus: 12 };

/* ---------------------------------------------------------------------------
   3. DATE HELPERS — LOCAL dates, never UTC.
   (The grammar daily challenge resets midnight Tokyo; that difference is
   deliberate. A global PAYMENT wants one clock, a personal rhythm wants yours.)
   -------------------------------------------------------------------------*/

const dayKey = (d = new Date()) => {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
};

const WEEK_LEN = 7;

/* THE WEEK IS THE LEARNER'S, NOT THE CALENDAR'S (Lloyd, Session 23).
   v3 used the calendar week with a Monday start, which had two problems.

   The small one: 月火水木金土日 puts 日 last, and a Japanese calendar puts it
   first. Fixed for good below by deriving each label from the date it sits on,
   so the row can never disagree with the dates it is showing.

   The real one: a fixed week hands out partial windows. Start on a Saturday and
   "any three days" means three days out of two — the target is unreachable
   before the learner has done anything wrong, on their first day. That is the
   same cliff a daily streak has, which is the thing this feature was chosen
   INSTEAD OF (see the tracker row: daily streaks punish normal life and produce
   quit-on-break). So the window is seven days anchored on the day they start,
   and every learner gets seven. */
const windowDayKeys = (startKey) =>
  Array.from({ length: WEEK_LEN }, (_, i) => {
    // Noon, not midnight: adding days across a DST boundary from 00:00 can land
    // on the same date twice, which would silently give someone a six-day week.
    const d = new Date(`${startKey}T12:00:00`);
    d.setDate(d.getDate() + i);
    return dayKey(d);
  });

const daysBetween = (a, b) =>
  Math.round((new Date(`${b}T00:00:00`) - new Date(`${a}T00:00:00`)) / 86400000);

// getDay() order — 日 first, as a Japanese calendar prints it.
const WEEKDAY_LABELS = ["日", "月", "火", "水", "木", "金", "土"];
const weekdayLabel = (key) => WEEKDAY_LABELS[new Date(`${key}T12:00:00`).getDay()];

/** Is a window open, and is today inside it? */
const windowLive = (startKey, today) => {
  if (!startKey) return false;
  const gap = daysBetween(startKey, today);
  return gap >= 0 && gap < WEEK_LEN;
};

/* Upgrading state written before weekStart existed. Anchoring to today would
   throw away days the learner had already earned and show them 0 of 3 for no
   reason they could see, so the window is anchored to the EARLIEST of their
   recent active days — the reading most favourable to them that is still true. */
const inferWeekStart = (activeDays, today) => {
  const recent = (activeDays || [])
    .filter((k) => { const g = daysBetween(k, today); return g >= 0 && g < WEEK_LEN; })
    .sort();
  return recent.length ? recent[0] : null;
};

/* ---------------------------------------------------------------------------
   4. QUEST GENERATION
   Quests WRAP work the scheduler already wants done. Review outranks new
   material whenever anything is due — that is what stops this layer from
   competing with the retention ladder in vocab-retention-model-v1.md.
   -------------------------------------------------------------------------*/

const DEFAULT_UNLOCKED = { hiragana: true, katakana: false, kanji: false, vocab: false, grammar: false, checker: false };

const TASK_LIBRARY = [
  { id: "hira_set",  requires: "hiragana", kind: "set",    label: "Finish one hiragana set" },
  { id: "kata_set",  requires: "katakana", kind: "set",    label: "Finish one katakana set" },
  { id: "kanji_rev", requires: "kanji",    kind: "review", label: "Clear your kanji reviews",  dueFrom: "kanji" },
  { id: "kanji_set", requires: "kanji",    kind: "set",    label: "Meet one new kanji set" },
  { id: "vocab_rev", requires: "vocab",    kind: "review", label: "Clear your word reviews",   dueFrom: "vocab" },
  { id: "vocab_set", requires: "vocab",    kind: "set",    label: "Meet one new set of words" },
  { id: "gram_rev",  requires: "grammar",  kind: "review", label: "Take the review challenge", dueFrom: "grammar" },
  { id: "check_one", requires: "checker",  kind: "write",  label: "Write and check one sentence" },
];

/** The early-finish bonus. One task, always production — the app's core act. */
const BONUS_TASK = { id: "bonus_write", requires: "checker", kind: "write", label: "Bonus — write two more sentences and check them", target: 2 };

const CHAIN_WINDOW_DAYS = 3;

function deriveQuests(unlockedIn, dueIn, seedKey) {
  const unlocked = { ...DEFAULT_UNLOCKED, ...(unlockedIn || {}) };
  const due = dueIn || {};
  const available = TASK_LIBRARY.filter((t) => unlocked[t.requires]);
  if (!available.length) return [];

  const dueTasks = available.filter((t) => t.dueFrom && (due[t.dueFrom] || 0) > 0);
  const rest = available.filter((t) => !dueTasks.includes(t));

  let h = 0;
  for (let i = 0; i < seedKey.length; i++) h = (h * 33 + seedKey.charCodeAt(i)) >>> 0;
  const rot = (a) => (a.length ? a.map((_, i) => a[(i + (h % a.length)) % a.length]) : a);

  const ordered = [...rot(dueTasks), ...rot(rest)];
  const chosen = [];
  const seen = new Set();
  for (const t of ordered) {
    if (chosen.length >= 3) break;
    if (seen.has(t.requires) && ordered.length >= 5) continue;
    seen.add(t.requires);
    chosen.push(t);
  }
  while (chosen.length < Math.min(3, ordered.length)) {
    const n = ordered.find((t) => !chosen.includes(t));
    if (!n) break;
    chosen.push(n);
  }
  return chosen.map((t, i) => ({
    taskId: t.id, label: t.label, target: 1, done: 0,
    kind: t.kind, module: t.requires, order: i, bonus: false,
  }));
}

/* ---------------------------------------------------------------------------
   5. STATE

   ⚠️ WHAT "TRACKING PROGRESS" MEANS HERE — read before wiring.

   This module tracks TWO things and infers nothing:
     • which local days had real study activity   (activeDays)
     • how far the current chain has got          (chain.tasks[].done)

   Both come from ONE source: `reportActivity(module, kind)`. Nothing else
   writes them. In particular, OPENING THE APP DOES NOT MARK A DAY ACTIVE —
   v2 marked the day on mount, which rewarded launching the app rather than
   studying, and would have shown "3 of 3" to someone who opened it three
   times and did nothing. The rhythm target has to mean study or it means
   nothing.

   It deliberately does NOT own module progress. Unlock state and due counts
   are READ from the modules that own them, passed in as props. There is one
   store per concern; this module is not a second copy of the truth.

   UNTIL `reportActivity` IS CALLED FROM THE FIVE MODULES, THIS TRACKS NOTHING.
   The call sites needed, one line each at the point the module already saves
   its own progress:
     hiragana / katakana lesson complete -> reportActivity("hiragana"|"katakana", "set")
     kanji set complete                  -> reportActivity("kanji", "set")
     kanji review cleared                -> reportActivity("kanji", "review")
     vocabulary set complete             -> reportActivity("vocab", "set")
     vocabulary review cleared           -> reportActivity("vocab", "review")
     grammar review challenge claimed    -> reportActivity("grammar", "review")
     checker returns a graded sentence   -> reportActivity("checker", "write")
   -------------------------------------------------------------------------*/

const WEEKLY_TARGET = 3;
const RECENT_WINDOW = 12;

function pickQuote(dateKey, recentIds = []) {
  const pool = QUOTES.filter((q) => !recentIds.includes(q.id));
  const usable = pool.length ? pool : QUOTES;
  if (!usable.length) return null;
  let h = 0;
  for (let i = 0; i < dateKey.length; i++) h = (h * 31 + dateKey.charCodeAt(i)) >>> 0;
  return usable[h % usable.length];
}

function useEngagement(unlocked, due, simulatedDate) {
  const today = simulatedDate || dayKey();
  const [state, setState] = useState(BLANK);
  const [wallet, setWallet] = useState(0);
  const [ready, setReady] = useState(false);
  const [flash, setFlash] = useState(null); // "+8 小判 — path completed"

  useEffect(() => {
    let alive = true;
    (async () => {
      const [s, w] = await Promise.all([loadJSON(KEY, BLANK), loadJSON(WALLET_KEY, 0)]);
      if (!alive) return;
      const merged = { ...BLANK, ...s };
      // State written before the rolling window existed carries active days and
      // no anchor. Infer one rather than resetting their count to zero.
      if (!merged.weekStart) merged.weekStart = inferWeekStart(merged.activeDays, dayKey());
      setState(merged); setWallet(w || 0); setReady(true);
    })();
    return () => { alive = false; };
  }, []);

  const save = useCallback((next) => {
    setState((prev) => {
      const merged = typeof next === "function" ? next(prev) : { ...prev, ...next };
      saveJSON(KEY, merged);
      return merged;
    });
  }, []);

  /** Wallet write. Balance is NOT rendered here — §1: it lives in the room/shop. */
  const pay = useCallback((amount, reason) => {
    setWallet((w) => {
      const next = (w || 0) + amount;
      saveJSON(WALLET_KEY, next);
      return next;
    });
    setFlash(`+${amount} 小判 — ${reason}`);
  }, []);

  // Rotate the card once per local day. This does NOT mark the day active.
  useEffect(() => {
    if (!ready || state.lastSeen === today) return;
    save((prev) => {
      const q = pickQuote(today, prev.recent);
      const recent = q ? [q.id, ...prev.recent.filter((i) => i !== q.id)].slice(0, RECENT_WINDOW) : prev.recent;
      return { ...prev, recent, lastSeen: today };
    });
  }, [ready, today, state.lastSeen, save]);

  // Start / expire chains.
  useEffect(() => {
    if (!ready) return;
    const c = state.chain;
    const expired = c && daysBetween(c.startedOn, today) >= CHAIN_WINDOW_DAYS &&
                    c.tasks.some((t) => t.done < t.target);
    const settled = c && c.claimed && (!c.bonus || c.bonusClaimed);
    const nextDay = settled && daysBetween(c.startedOn, today) >= 1;

    if (!c || expired || nextDay) {
      const tasks = deriveQuests(unlocked, due, today + (c?.startedOn || ""));
      if (!tasks.length) return;
      save({ chain: { startedOn: today, tasks, claimed: false, bonus: false, bonusClaimed: false } });
    }
  }, [ready, state.chain, today, unlocked, due, save]);

  const quote = useMemo(
    () => QUOTES.find((q) => q.id === state.recent[0]) || pickQuote(today, []),
    [state.recent, today]
  );

  // Before the first day of work there is no anchor, so the row shows the seven
  // days that WOULD follow if they started now. Provisional and unsaved: it
  // moves with the date until something actually anchors it, which is the honest
  // way to show a window that has not begun.
  const weekStart = windowLive(state.weekStart, today) ? state.weekStart : today;

  const weekDays = useMemo(
    () => windowDayKeys(weekStart).map((k) => ({
      key: k, active: state.activeDays.includes(k), isToday: k === today, future: k > today,
    })),
    [state.activeDays, today, weekStart]
  );

  const weekCount = weekDays.filter((d) => d.active).length;

  /**
   * THE integration point. The ONLY thing that marks a day active or advances
   * a chain. Call it where each module already persists its own progress.
   */
  const reportActivity = useCallback((module, kind, amount = 1) => {
    save((prev) => {
      const activeDays = prev.activeDays.includes(today)
        ? prev.activeDays
        : [...prev.activeDays, today].slice(-120);

      // A finished window is not extended, it is replaced — and the new one
      // opens HERE, on a day with real work in it, not on the day the app was
      // opened. Anchoring on arrival would let someone burn five of their seven
      // days by looking at the app and closing it, which is the failure §5 is
      // about and the reason a rolling window is worth having at all.
      const weekStart = windowLive(prev.weekStart, today) ? prev.weekStart : today;

      if (!prev.chain) return { ...prev, activeDays, weekStart };

      let credited = false;
      const tasks = prev.chain.tasks.map((t) => {
        if (credited || t.done >= t.target) return t;
        if (t.module === module && (!kind || t.kind === kind)) {
          credited = true;
          return { ...t, done: Math.min(t.target, t.done + amount) };
        }
        return t;
      });
      return { ...prev, activeDays, weekStart, chain: { ...prev.chain, tasks } };
    });
  }, [save, today]);

  const claim = useCallback(() => {
    save((prev) => {
      if (!prev.chain || prev.chain.claimed) return prev;
      // Early finish = all three done before the window's last day.
      const early = daysBetween(prev.chain.startedOn, today) < CHAIN_WINDOW_DAYS - 1;
      const tasks = early
        ? [...prev.chain.tasks, {
            taskId: BONUS_TASK.id, label: BONUS_TASK.label, target: BONUS_TASK.target,
            done: 0, kind: BONUS_TASK.kind, module: BONUS_TASK.requires,
            order: prev.chain.tasks.length, bonus: true,
          }]
        : prev.chain.tasks;
      pay(KOBAN.chain, "path completed");
      return { ...prev, chain: { ...prev.chain, tasks, claimed: true, bonus: early } };
    });
  }, [save, today, pay]);

  const claimBonus = useCallback(() => {
    save((prev) => {
      if (!prev.chain?.bonus || prev.chain.bonusClaimed) return prev;
      pay(KOBAN.bonus, "finished early");
      return { ...prev, chain: { ...prev.chain, bonusClaimed: true } };
    });
  }, [save, pay]);

  const reset = useCallback(() => save({ ...BLANK }), [save]);

  return {
    ...state, ready, today, wallet, quote, weekDays, weekCount, flash, setFlash,
    reportActivity, claim, claimBonus, reset,
  };
}

/* ---------------------------------------------------------------------------
   6. UI
   -------------------------------------------------------------------------*/

/** Tappable token. The whole point: the learner checks the Japanese themselves. */
function Token({ tok, open, onToggle }) {
  const interactive = Boolean(tok.g);
  if (!interactive) return <span className="text-stone-500">{tok.t}</span>;
  return (
    <button
      onClick={onToggle}
      className={`relative rounded px-0.5 transition-colors ${
        open ? "bg-amber-100 text-stone-900" : "text-stone-800 hover:bg-stone-100"
      }`}
      style={{ textUnderlineOffset: 6 }}
    >
      {tok.r ? (
        <ruby>{tok.t}<rt className="text-[0.45em] font-normal text-stone-400">{tok.r}</rt></ruby>
      ) : tok.t}
    </button>
  );
}

function QuoteCard({ quote }) {
  const [openIdx, setOpenIdx] = useState(null);
  useEffect(() => setOpenIdx(null), [quote?.id]);
  if (!quote) return null;
  const open = openIdx == null ? null : quote.tokens[openIdx];

  return (
    <div className="rounded-xl border border-stone-200 bg-gradient-to-b from-amber-50/40 to-white p-5">
      <p className="mb-3 text-[11px] uppercase tracking-widest text-stone-400">Today</p>

      <div className="text-2xl leading-loose" lang="ja">
        {quote.tokens.map((t, i) => (
          <Token key={i} tok={t} open={openIdx === i}
            onToggle={() => setOpenIdx(openIdx === i ? null : i)} />
        ))}
      </div>

      {open ? (
        <div className="mt-3 rounded-lg border border-amber-200 bg-amber-50 p-3">
          <p className="text-sm font-medium text-stone-800">
            {open.t}{open.r ? ` — ${open.r}` : ""}
          </p>
          <p className="mt-0.5 text-sm text-stone-600">{open.g}</p>
          {open.ledger && open.ledger !== open.g && (
            <p className="mt-1 text-xs text-stone-500">also in your words: “{open.ledger}”</p>
          )}
        </div>
      ) : (
        <p className="mt-3 text-xs text-stone-400">Tap any word for its reading.</p>
      )}

      <div className="my-4 h-px bg-stone-200" />

      {/* ⚠️ THE THREE LABELS ARE A SEQUENCE, NOT A LIST (Lloyd, Session 23).
          They walk from what the words certainly say, to what they might mean,
          to the learner's own reading — and the last step is the one the card
          exists for. The previous version put the invitation in 11px grey at
          the bottom, which is where a disclaimer goes, not a question. An
          invitation that looks like small print gets read as small print.

          This is also what keeps the card off the reviewer's desk: an
          invitation cannot be wrong the way an assertion can, so nothing here
          needs a native-speaker ruling. Do not "improve" these into a stated
          meaning — that would put every card in the review queue. */}
      <p className="text-xs uppercase tracking-wider text-stone-400">Literally</p>
      <p className="mt-1 text-sm italic text-stone-600">{quote.literal}</p>

      <p className="mt-4 text-xs uppercase tracking-wider text-stone-400">It might mean</p>
      <p className="mt-1 text-sm leading-relaxed text-stone-700">{quote.one_reading}</p>

      <p className="mt-4 rounded-lg bg-stone-100 px-3 py-2 text-sm text-stone-700">
        {quote.invite}
      </p>

      <p className="mt-4 text-sm leading-relaxed text-stone-800">
        But what do <span className="font-semibold italic">you</span> think it is
        trying to say?
      </p>
      <p className="mt-1 text-xs text-stone-500">
        There is no answer waiting behind this. Yours may be the better one.
      </p>
    </div>
  );
}

function WeeklyTarget({ weekDays, count }) {
  const met = count >= WEEKLY_TARGET;
  const R = 26, C = 2 * Math.PI * R;
  return (
    <div className="flex items-center gap-4 rounded-xl border border-stone-200 bg-white p-4">
      <div className="relative shrink-0">
        <svg width="64" height="64" viewBox="0 0 64 64" className="-rotate-90">
          <circle cx="32" cy="32" r={R} fill="none" stroke="#e7e5e4" strokeWidth="5" />
          <circle cx="32" cy="32" r={R} fill="none" stroke={met ? "#9a3412" : "#78716c"}
            strokeWidth="5" strokeLinecap="round" strokeDasharray={C}
            strokeDashoffset={C * (1 - Math.min(1, count / WEEKLY_TARGET))}
            className="transition-all duration-700" />
        </svg>
        <div className="absolute inset-0 flex items-center justify-center">
          <span className={`text-lg font-semibold ${met ? "text-orange-800" : "text-stone-700"}`}>{count}</span>
        </div>
      </div>
      <div className="min-w-0 flex-1">
        <p className="text-sm font-medium text-stone-800">
          {met ? "This week's rhythm is kept." : `${count} of ${WEEKLY_TARGET} days this week`}
        </p>
        <p className="mt-0.5 text-xs text-stone-500">
          {met ? "Anything further is yours to enjoy." : "Any three days. They don't need to be in a row."}
        </p>
        <div className="mt-2 flex gap-1.5">
          {weekDays.map((d) => (
            <div key={d.key} className="flex flex-col items-center gap-1">
              <div className={[
                "h-6 w-6 rounded-md border transition-colors",
                d.active ? "border-orange-800 bg-orange-800"
                  : d.isToday ? "border-dashed border-stone-400 bg-white"
                  : d.future ? "border-stone-200 bg-stone-50" : "border-stone-200 bg-stone-100",
              ].join(" ")} />
              <span className="text-[10px] text-stone-400">{weekdayLabel(d.key)}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

function QuestChain({ chain, today, onClaim, onClaimBonus, onSimulate, devTools }) {
  if (!chain) {
    return (
      <div className="rounded-xl border border-dashed border-stone-300 bg-stone-50 p-4 text-sm text-stone-500">
        No path yet — unlock a module to begin one.
      </div>
    );
  }
  const core = chain.tasks.filter((t) => !t.bonus);
  const bonus = chain.tasks.find((t) => t.bonus);
  const coreDone = core.every((t) => t.done >= t.target);
  const bonusDone = bonus && bonus.done >= bonus.target;
  const daysLeft = CHAIN_WINDOW_DAYS - daysBetween(chain.startedOn, today);

  const Row = ({ t }) => {
    const done = t.done >= t.target;
    return (
      <li className="flex items-center gap-3">
        <div className={[
          "flex h-5 w-5 shrink-0 items-center justify-center rounded-full border text-[11px]",
          done ? (t.bonus ? "border-amber-600 bg-amber-600 text-white" : "border-orange-800 bg-orange-800 text-white")
               : "border-stone-300 bg-white text-transparent",
        ].join(" ")}>✓</div>
        <span className={`flex-1 text-sm ${done ? "text-stone-400 line-through" : t.bonus ? "text-amber-800" : "text-stone-700"}`}>
          {t.label}{t.target > 1 ? ` (${t.done}/${t.target})` : ""}
        </span>
        {devTools && !done && (
          <button onClick={() => onSimulate(t.module, t.kind)}
            className="rounded border border-stone-200 px-2 py-0.5 text-[11px] text-stone-500 hover:bg-stone-50">mark</button>
        )}
      </li>
    );
  };

  return (
    <div className="rounded-xl border border-stone-200 bg-white p-4">
      <div className="mb-3 flex items-baseline justify-between gap-3">
        <h3 className="text-sm font-medium text-stone-800">A short path</h3>
        <span className="text-xs text-stone-400">
          {coreDone ? "Complete" : daysLeft > 1 ? `${daysLeft} days left` : "Last day"}
        </span>
      </div>

      <ul className="space-y-2">{core.map((t) => <Row key={t.taskId} t={t} />)}</ul>

      {coreDone && !chain.claimed && (
        <button onClick={onClaim}
          className="mt-4 w-full rounded-lg bg-orange-800 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-orange-900">
          Collect
        </button>
      )}

      {bonus && (
        <div className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3">
          <p className="mb-2 text-[11px] font-medium uppercase tracking-wide text-amber-800">
            Finished early — one more if you want it
          </p>
          <ul><Row t={bonus} /></ul>
          {bonusDone && !chain.bonusClaimed && (
            <button onClick={onClaimBonus}
              className="mt-3 w-full rounded-lg bg-amber-600 px-4 py-2 text-sm font-medium text-white hover:bg-amber-700">
              Collect
            </button>
          )}
        </div>
      )}

      {chain.claimed && (!chain.bonus || chain.bonusClaimed) && (
        <p className="mt-3 rounded-lg bg-stone-50 px-3 py-2 text-xs text-stone-500">
          A new path begins tomorrow.
        </p>
      )}
    </div>
  );
}

/* ---------------------------------------------------------------------------
   7. ROOT
   -------------------------------------------------------------------------*/

export default function EngagementModule({
  unlocked = { hiragana: true, katakana: true, kanji: true, vocab: true, grammar: true, checker: true },
  due = { kanji: 6, vocab: 0, grammar: 0 },
  devTools = true,
  onApi = null,
}) {
  const [simDate, setSimDate] = useState(null);
  const eng = useEngagement(unlocked, due, simDate);
  const apiRef = useRef(null);
  apiRef.current = eng.reportActivity;

  // ————— the integration seam (Session 23) —————
  // §5 lists the seven call sites reportActivity needs, all of them inside the
  // five learning modules. The host app has a signal those modules do not: it
  // already snapshots a module's own progress store on the way in and compares
  // on the way out, and writes "last worked on" only if the store CHANGED. That
  // is evidence of study rather than of arrival — the same distinction §5
  // insists on, arrived at independently — so it can drive this too, with no
  // edits inside any module.
  //
  // Handing the api out rather than reaching in: this file must stay loadable
  // as a standalone artifact, so it cannot import anything from naoshi-app/.
  useEffect(() => {
    if (onApi) onApi({ reportActivity: eng.reportActivity });
  }, [onApi, eng.reportActivity]);

  useEffect(() => {
    if (!eng.flash) return;
    const t = setTimeout(() => eng.setFlash(null), 3200);
    return () => clearTimeout(t);
  }, [eng.flash]);

  const shiftDay = (n) => {
    const base = new Date(`${simDate || eng.today}T12:00:00`);
    base.setDate(base.getDate() + n);
    setSimDate(dayKey(base));
  };

  return (
    <div className="mx-auto max-w-lg space-y-4 bg-stone-100 p-4 font-sans">
      {/* No balance in the header — §1: the wallet is checked in the room/shop. */}
      <QuoteCard quote={eng.quote} />

      {eng.flash && (
        <div className="rounded-lg border border-amber-300 bg-amber-50 px-3 py-2 text-sm text-amber-900">
          {eng.flash}
        </div>
      )}

      <WeeklyTarget weekDays={eng.weekDays} count={eng.weekCount} />

      <QuestChain chain={eng.chain} today={eng.today} onClaim={eng.claim}
        onClaimBonus={eng.claimBonus} onSimulate={(m, k) => apiRef.current(m, k)}
        devTools={devTools} />

      {devTools && (
        <div className="rounded-lg border border-stone-300 bg-white p-3">
          <p className="mb-2 text-[11px] font-medium uppercase tracking-wide text-stone-500">Test controls</p>
          <div className="flex flex-wrap items-center gap-2 text-xs">
            <button onClick={() => shiftDay(1)} className="rounded border border-stone-300 px-2 py-1 text-stone-700">+1 day</button>
            <button onClick={() => shiftDay(4)} className="rounded border border-stone-300 px-2 py-1 text-stone-700">+4 days</button>
            <button onClick={() => setSimDate(null)} className="rounded border border-stone-300 px-2 py-1 text-stone-700">real date</button>
            <button onClick={eng.reset} className="rounded border border-stone-300 px-2 py-1 text-stone-700">reset</button>
            <span className="ml-auto text-stone-500">
              {simDate || eng.today} · wallet {eng.wallet} · {QUOTES.length} cards
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
