// ————— Accounts —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// Sign-in exists for one reason: progress currently lives in one browser on one
// device, and a learner who clears their browser loses everything. Save/Restore
// was the cheap insurance; this is the real one.
//
// ⚠️ THE WHOLE DESIGN IS SHAPED BY WHAT MUST NOT HAPPEN. Introducing accounts is
// the single most likely way to reproduce the twelve days of silent grammar-loss
// this app already shipped, at a larger scale — a sign-in that quietly replaces
// this device's progress with an empty account looks exactly like success. So:
//
//   · nothing local is written until the merge has been settled
//   · a genuine disagreement is a QUESTION, with no default and no timer
//   · the side that loses a question is preserved either way — the account's
//     copy by the database's archive trigger, the device's by writing a file
//     before it is overwritten
//
// The rule itself lives in sync.js and is tested by test-progress-sync.py.
// Everything here is presentation of that rule.

import { useState, useEffect, useCallback } from "react";
import { T } from "./tokens.js";
import { accountsConfigured, getClient, redirectTo } from "./supabase.js";
import {
  readLocal, writeLocal, mergeProgress, resolveConflicts,
  fetchRemote, pushRemote, preserveLocalToFile,
} from "./sync.js";

// Storage keys are not learner-facing language. Names, never counts — the
// standing rule is that the UI states capability and never workload.
const KEY_LABELS = {
  "hiragana-progress-v2": "Hiragana practice",
  "katakana-progress-v1": "Katakana practice",
  "kanji-progress-v1": "Kanji practice",
  "known-kanji-v1": "Kanji you have met",
  "known-words-v1": "Words you have met",
  "n5-progress-v1": "Grammar lessons",
  "learner-depth-v1": "How deep grammar explanations go",
  "achievement-points-v1": "Koban",
  "engagement-v1": "Daily rhythm and quests",
  "stroke-data-v1": "Handwriting calibration",
  "kanji-mode": "Kanji reading mode",
};
const label = (k) => KEY_LABELS[k] || k;

const box = {
  background: T.sheet, border: `1px solid ${T.hairline}`, borderRadius: 10,
  padding: "16px 16px 18px", fontFamily: T.uiFont, color: T.ink,
};
const primary = {
  background: T.ink, color: T.paper, border: "none", borderRadius: 8,
  padding: "10px 16px", cursor: "pointer", font: `600 14px ${T.uiFont}`,
};
const ghost = {
  background: "none", color: T.ink, border: `1px solid ${T.hairline}`,
  borderRadius: 8, padding: "10px 16px", cursor: "pointer",
  font: `14px ${T.uiFont}`,
};

export default function Account({ open, setOpen }) {
  const [client, setClient] = useState(null);
  const [session, setSession] = useState(null);
  const [email, setEmail] = useState("");
  const [phase, setPhase] = useState("idle");   // idle | sending | sent | syncing | conflict | done
  const [note, setNote] = useState(null);
  const [error, setError] = useState(null);
  const [plan, setPlan] = useState(null);
  const [sides, setSides] = useState(null);     // { local, remote } held for a pending question

  // ————— an auth callback that came back as an error —————
  // Supabase returns failures in the URL FRAGMENT, not as a status code:
  //   #error=access_denied&error_code=otp_expired&error_description=…
  // Nothing reads that by default, so an expired or already-used link lands the
  // learner on a normal-looking home screen with no session and no explanation —
  // which is indistinguishable from "the email never arrived". Surface it, and
  // open the dialog, because the person holding a dead link is mid-task.
  useEffect(() => {
    if (typeof window === "undefined") return;
    const h = new URLSearchParams(window.location.hash.replace(/^#/, ""));
    const desc = h.get("error_description");
    if (!desc) return;
    setError(desc.replace(/\+/g, " ") +
      ". Sign-in links can only be used once, and they expire — ask for a new one.");
    setOpen(true);
    // Clear the fragment so a reload does not re-raise a stale failure.
    window.history.replaceState(null, "", window.location.pathname + window.location.search);
  }, [setOpen]);

  // ————— sign-in state —————
  useEffect(() => {
    if (!accountsConfigured()) return undefined;
    let alive = true;
    let sub = null;
    (async () => {
      try {
        const c = await getClient();
        if (!alive || !c) return;
        setClient(c);
        const { data } = await c.auth.getSession();
        if (!alive) return;
        setSession(data.session ?? null);
        sub = c.auth.onAuthStateChange((_evt, s) => setSession(s ?? null)).data.subscription;
      } catch (e) {
        if (alive) setError("Could not reach the account service. " + (e?.message || ""));
      }
    })();
    return () => { alive = false; sub?.unsubscribe(); };
  }, []);

  // ————— the merge, run once per sign-in —————
  const runSync = useCallback(async (c, user) => {
    setPhase("syncing"); setError(null); setNote(null);
    try {
      const local = readLocal();
      const remoteRow = await fetchRemote(c, user.id);
      const remote = remoteRow.data || {};
      const p = mergeProgress(local, remote);

      if (p.status === "clean") {
        // Nothing to ask about: every key was on one side only, or the two
        // sides agreed. Writing local first and pushing second means a failed
        // upload leaves the learner with MORE progress than they started with,
        // never less.
        writeLocal(p.merged);
        await pushRemote(c, user.id, p.merged);
        setPhase("done");
        setNote(p.pulled.length
          ? `Signed in. ${p.pulled.length === 1 ? "One thing" : p.pulled.length + " things"} came back from your account — reload to see it.`
          : "Signed in. This device's progress is now saved to your account.");
      } else {
        setPlan(p);
        setSides({ local, remote });
        setPhase("conflict");
        setOpen(true);   // a question must not sit behind a closed menu
      }
    } catch (e) {
      setPhase("done");
      setError("Signed in, but syncing failed: " + (e?.message || String(e)) +
               ". Nothing on this device was changed.");
    }
  }, [setOpen]);

  useEffect(() => {
    if (!client || !session?.user) return;
    if (phase === "syncing" || phase === "conflict" || phase === "done") return;
    runSync(client, session.user);
  }, [client, session, phase, runSync]);

  // ————— settling a question —————
  const choose = async (side) => {
    setPhase("syncing");
    try {
      // The account's copy is preserved by the archive trigger no matter which
      // way this goes. The DEVICE's copy has no such net, so it gets one — a
      // file, written before anything is overwritten.
      if (side === "remote") preserveLocalToFile();
      const settled = resolveConflicts(plan, sides.local, sides.remote, side);
      writeLocal(settled);
      await pushRemote(client, session.user.id, settled);
      setPhase("done");
      setNote(side === "remote"
        ? "Your account's version is now on this device. This device's previous version was saved to a file first, in your downloads."
        : "This device's version is now on your account. The version it replaced is kept in your account's history.");
    } catch (e) {
      setPhase("done");
      setError("That did not go through: " + (e?.message || String(e)) +
               ". Nothing was overwritten.");
    }
  };

  const sendLink = async (e) => {
    e.preventDefault();
    if (!client || !email.trim()) return;
    setPhase("sending"); setError(null);
    const { error: err } = await client.auth.signInWithOtp({
      email: email.trim(),
      options: { emailRedirectTo: redirectTo() },
    });
    if (err) { setPhase("idle"); setError(err.message); return; }
    setPhase("sent");
  };

  const signOut = async () => {
    // Sign-out does NOT clear local progress. The learner keeps studying on this
    // device exactly as they did before they had an account; the next sign-in
    // merges rather than replaces. Clearing here would turn "sign out" into
    // "delete my work", which is not what the words mean.
    await client?.auth.signOut();
    setSession(null); setPhase("idle"); setNote(null); setPlan(null); setSides(null);
  };

  if (!open) return null;

  const close = () => { if (phase !== "conflict") setOpen(false); };

  return (
    <>
      <div onClick={close} aria-hidden="true" style={{
        position: "fixed", inset: 0, zIndex: 30, background: "rgba(34,37,43,0.44)",
      }} />
      <div role="dialog" aria-modal="true" aria-label="Account" style={{
        position: "fixed", zIndex: 31, left: "50%", top: "50%",
        transform: "translate(-50%,-50%)", width: "min(92vw, 420px)",
        maxHeight: "86vh", overflowY: "auto", ...box,
      }}>
        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
          <h2 style={{ font: `600 17px ${T.uiFont}`, margin: 0 }}>Account</h2>
          {phase !== "conflict" && (
            <button onClick={close} aria-label="Close" style={{
              background: "none", border: "none", cursor: "pointer",
              padding: 8, font: `16px ${T.uiFont}`, color: T.sub,
            }}>✕</button>
          )}
        </div>

        {!accountsConfigured() && (
          <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.sub }}>
            Accounts are not switched on in this build. Your progress is saved in
            this browser, and Save still writes it to a file you can keep.
          </p>
        )}

        {accountsConfigured() && !session && phase !== "sent" && (
          <>
            <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.sub }}>
              Sign in and your progress follows you to any device. Right now it
              lives only in this browser — clearing it would clear your work.
            </p>
            <form onSubmit={sendLink} style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}>
              <input
                type="email" required value={email} autoComplete="email"
                onChange={(ev) => setEmail(ev.target.value)}
                placeholder="you@example.com"
                style={{
                  flex: "1 1 200px", minWidth: 0, padding: "10px 12px",
                  border: `1px solid ${T.hairline}`, borderRadius: 8,
                  font: `14px ${T.uiFont}`, color: T.ink, background: T.paper,
                }}
              />
              <button type="submit" disabled={phase === "sending"} style={primary}>
                {phase === "sending" ? "Sending…" : "Email me a link"}
              </button>
            </form>
            <p style={{ font: `12px/1.6 ${T.uiFont}`, color: T.sub, marginTop: 10 }}>
              No password. We email a link that signs you in on this device.
            </p>
          </>
        )}

        {phase === "sent" && !session && (
          <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
            Check <strong>{email}</strong>. The link signs you in on this device —
            open it in this browser rather than another one.
          </p>
        )}

        {session && phase !== "conflict" && (
          <>
            <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
              Signed in as <strong>{session.user.email}</strong>.
            </p>
            {phase === "syncing" && (
              <p style={{ font: `13px ${T.uiFont}`, color: T.sub }}>Syncing…</p>
            )}
            {note && (
              <p role="status" style={{
                font: `13px/1.6 ${T.uiFont}`, color: T.note,
                background: T.noteBg, borderRadius: 8, padding: "10px 12px",
              }}>{note}</p>
            )}
            <div style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}>
              <button onClick={() => window.location.reload()} style={ghost}>Reload</button>
              <button onClick={signOut} style={ghost}>Sign out</button>
            </div>
            <p style={{ font: `12px/1.6 ${T.uiFont}`, color: T.sub, marginTop: 10 }}>
              Signing out leaves this device's progress exactly where it is.
            </p>
          </>
        )}

        {phase === "conflict" && plan && (
          <>
            <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
              This device and your account both have progress, and they do not
              match. Nothing has been changed yet.
            </p>
            <ul style={{ font: `14px/1.7 ${T.uiFont}`, color: T.ink, paddingLeft: 20, margin: "10px 0" }}>
              {plan.conflicts.map((k) => <li key={k}>{label(k)}</li>)}
            </ul>
            {(plan.pushed.length > 0 || plan.pulled.length > 0) && (
              <p style={{ font: `13px/1.6 ${T.uiFont}`, color: T.sub }}>
                Everything else is kept from both sides either way — only the
                items above have to be decided.
              </p>
            )}
            <div style={{ display: "flex", flexDirection: "column", gap: 8, marginTop: 14 }}>
              <button onClick={() => choose("local")} style={primary}>
                Keep what is on this device
              </button>
              <button onClick={() => choose("remote")} style={ghost}>
                Keep what is in my account
              </button>
            </div>
            <p style={{ font: `12px/1.6 ${T.uiFont}`, color: T.sub, marginTop: 12 }}>
              Whichever you choose, the other version is kept — your account
              keeps its own history, and this device's version is written to a
              file before anything is replaced.
            </p>
          </>
        )}

        {error && (
          <p role="alert" style={{
            font: `13px/1.6 ${T.uiFont}`, color: T.shu, marginTop: 12,
          }}>{error}</p>
        )}
      </div>
    </>
  );
}
