// ————— Account, settings, stats and reset —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// Sign-in exists for one reason: progress currently lives in one browser on one
// device, and a learner who clears their browser loses everything. Save/Restore
// was the cheap insurance; this is the real one.
//
// ⚠️ THE WHOLE DESIGN IS SHAPED BY WHAT MUST NOT HAPPEN. Introducing accounts is
// the single most likely way to reproduce the twelve days of silent grammar-loss
// this app already shipped, at a larger scale — a sign-in that quietly replaces
// this device's progress with an empty account looks exactly like success. So:
//
//   · nothing local is written until the merge has been settled
//   · a genuine disagreement is a QUESTION, with no default and no timer
//   · the account's copy of a losing side is preserved automatically, by the
//     database's archive trigger. The DEVICE's copy is not — saving it is a
//     button the learner presses, offered beside the choice that would
//     overwrite it (Session 23: nothing downloads without being asked for)
//
// The rule itself lives in sync.js and is tested by test-progress-sync.py.
// Everything here is presentation of that rule, plus the settings and stats a
// person expects to find behind the word "Account".

import { useState, useEffect, useCallback, useRef } from "react";
import { T } from "./tokens.js";
import { accountsConfigured, getClient, redirectTo } from "./supabase.js";
import {
  readLocal, writeLocal, mergeProgress, resolveConflicts,
  fetchRemote, pushRemote, preserveLocalToFile,
} from "./sync.js";
import {
  SECTIONS, SETTINGS, readSectionStats, readWallet, resetSections,
  daysSinceLastWorked, DORMANT_DAYS,
} from "./stats.js";
import { storage, downloadProgress, importProgress } from "./storage.js";

// Storage keys are not learner-facing language. Names, never counts.
const KEY_LABELS = {
  "hiragana-progress-v2": "Hiragana practice",
  "katakana-progress-v1": "Katakana practice",
  "kanji-progress-v1": "Kanji practice",
  "known-kanji-v1": "Kanji you have met",
  "known-words-v1": "Words you have met",
  "n5-progress-v1": "Grammar lessons",
  "learner-depth-v1": "How deep grammar explanations go",
  "achievement-points-v1": "Koban",
  "engagement-v1": "Daily rhythm and quests",
  "stroke-data-v1": "Handwriting calibration",
  "kanji-mode": "Kanji reading mode",
  "module-recency-v1": "Which section you used last",
};
const label = (k) => KEY_LABELS[k] || k;

const box = {
  background: T.sheet, border: `1px solid ${T.hairline}`, borderRadius: 10,
  padding: "16px 16px 18px", fontFamily: T.uiFont, color: T.ink,
};
const primary = {
  background: T.ink, color: T.paper, border: "none", borderRadius: 8,
  padding: "10px 16px", cursor: "pointer", font: `600 14px ${T.uiFont}`,
};
const ghost = {
  background: "none", color: T.ink, border: `1px solid ${T.hairline}`,
  borderRadius: 8, padding: "10px 16px", cursor: "pointer",
  font: `14px ${T.uiFont}`,
};
const danger = {
  ...primary, background: T.shu,
};
const quiet = { font: `12px/1.6 ${T.uiFont}`, color: T.sub };

export default function Account({ open, setOpen }) {
  const [tab, setTab] = useState("account");
  const [client, setClient] = useState(null);
  const [session, setSession] = useState(null);
  const [email, setEmail] = useState("");
  const [phase, setPhase] = useState("idle");   // idle | sending | sent | syncing | conflict | done
  const [note, setNote] = useState(null);
  const [error, setError] = useState(null);
  const [plan, setPlan] = useState(null);
  const [sides, setSides] = useState(null);

  const [stats, setStats] = useState([]);
  const [wallet, setWallet] = useState(0);
  const [dormantDays, setDormantDays] = useState(null);
  const [settings, setSettings] = useState({});
  const [picked, setPicked] = useState([]);     // sections selected for reset
  const [confirming, setConfirming] = useState(false);
  const [resetMsg, setResetMsg] = useState(null);
  const [savedCopy, setSavedCopy] = useState(null);

  // ————— an auth callback that came back as an error —————
  // Supabase returns failures in the URL FRAGMENT, not as a status code:
  //   #error=access_denied&error_code=otp_expired&error_description=…
  // Nothing reads that by default, so an expired or already-used link lands the
  // learner on a normal-looking home screen with no session and no explanation —
  // which is indistinguishable from "the email never arrived".
  useEffect(() => {
    if (typeof window === "undefined") return;
    const h = new URLSearchParams(window.location.hash.replace(/^#/, ""));
    const desc = h.get("error_description");
    if (!desc) return;
    setError(desc.replace(/\+/g, " ") +
      ". Sign-in links can only be used once, and they expire — ask for a new one.");
    setOpen(true);
    window.history.replaceState(null, "", window.location.pathname + window.location.search);
  }, [setOpen]);

  // ————— sign-in state —————
  useEffect(() => {
    if (!accountsConfigured()) return undefined;
    let alive = true;
    let sub = null;
    (async () => {
      try {
        const c = await getClient();
        if (!alive || !c) return;
        setClient(c);
        const { data } = await c.auth.getSession();
        if (!alive) return;
        setSession(data.session ?? null);
        sub = c.auth.onAuthStateChange((_evt, s) => setSession(s ?? null)).data.subscription;
      } catch (e) {
        if (alive) setError("Could not reach the account service. " + (e?.message || ""));
      }
    })();
    return () => { alive = false; sub?.unsubscribe(); };
  }, []);

  // ————— the merge, run once per sign-in —————
  const runSync = useCallback(async (c, user) => {
    setPhase("syncing"); setError(null); setNote(null);
    try {
      const local = readLocal();
      const remoteRow = await fetchRemote(c, user.id);
      const remote = remoteRow.data || {};
      const p = mergeProgress(local, remote);

      if (p.status === "clean") {
        // Writing local first and pushing second means a failed upload leaves
        // the learner with MORE progress than they started with, never less.
        writeLocal(p.merged);
        await pushRemote(c, user.id, p.merged);
        setPhase("done");
        setNote(p.pulled.length
          ? `Signed in. ${p.pulled.length === 1 ? "One thing" : p.pulled.length + " things"} came back from your account — reload to see it.`
          : "Signed in. This device's progress is now saved to your account.");
      } else {
        setPlan(p);
        setSides({ local, remote });
        setPhase("conflict");
        setOpen(true);   // a question must not sit behind a closed menu
      }
    } catch (e) {
      setPhase("done");
      setError("Signed in, but syncing failed: " + (e?.message || String(e)) +
               ". Nothing on this device was changed.");
    }
  }, [setOpen]);

  // ⚠️ THE GUARD IS A REF, NOT `phase`. `phase` is state, so two invocations of
  // this effect in the same tick both read "idle" and both start a sync — which
  // is what happened on the first real sign-in, Sep 6 2026, visible in the API
  // log as the whole cycle twice. StrictMode makes it visible; the race is real
  // without it, because setPhase() does not take effect until the next render.
  //
  // IT WAS HARMLESS ONLY BECAUSE THAT ACCOUNT WAS EMPTY. With progress on both
  // sides it corrupts the one rule this file exists to enforce: run A reads an
  // empty remote, merges, and pushes; run B then reads the remote A just wrote,
  // finds it identical to local, and reports "clean" — so a genuine conflict is
  // silently settled instead of asked about.
  const syncedFor = useRef(null);

  useEffect(() => {
    if (!client || !session?.user) return;
    if (syncedFor.current === session.user.id) return;
    syncedFor.current = session.user.id;
    runSync(client, session.user);
  }, [client, session, runSync]);

  // ————— stats, wallet, settings: refreshed whenever the panel opens —————
  const refresh = useCallback(async () => {
    const [s, w, d] = await Promise.all([
      readSectionStats(), readWallet(), daysSinceLastWorked(),
    ]);
    setStats(s); setWallet(w); setDormantDays(d);
    const cur = {};
    for (const st of SETTINGS) {
      const r = await storage.get(st.key);
      cur[st.key] = r?.value ?? st.fallback;
    }
    setSettings(cur);
  }, []);

  useEffect(() => { if (open) refresh(); }, [open, refresh]);

  const changeSetting = async (key, value) => {
    setSettings((s) => ({ ...s, [key]: value }));
    try { await storage.set(key, value); } catch (e) { console.error(e); }
  };

  // ————— settling a conflict —————
  const choose = async (side) => {
    setPhase("syncing");
    try {
      // The account's copy is preserved by the archive trigger either way. The
      // DEVICE's copy has no such net, so it gets one before being overwritten.
      const settled = resolveConflicts(plan, sides.local, sides.remote, side);
      writeLocal(settled);
      await pushRemote(client, session.user.id, settled);
      setPhase("done");
      setNote(side === "remote"
        ? "Your account's version is now on this device."
        : "This device's version is now on your account. The version it replaced is kept in your account's history.");
    } catch (e) {
      setPhase("done");
      setError("That did not go through: " + (e?.message || String(e)) +
               ". Nothing was overwritten.");
    }
  };

  const sendLink = async (e) => {
    e.preventDefault();
    if (!client || !email.trim()) return;
    setPhase("sending"); setError(null);
    const { error: err } = await client.auth.signInWithOtp({
      email: email.trim(),
      options: { emailRedirectTo: redirectTo() },
    });
    if (err) { setPhase("idle"); setError(err.message); return; }
    setPhase("sent");
  };

  const signOut = async () => {
    // Sign-out does NOT clear local progress. The learner keeps studying on this
    // device exactly as before; the next sign-in merges rather than replaces.
    await client?.auth.signOut();
    syncedFor.current = null;
    setSession(null); setPhase("idle"); setNote(null); setPlan(null); setSides(null);
  };

  const restore = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const r = new FileReader();
    r.onload = () => { setResetMsg(importProgress(String(r.result)).message); refresh(); };
    r.readAsText(file);
    e.target.value = "";
  };

  // ————— reset —————
  const doReset = async () => {
    setConfirming(false);
    setSavedCopy(null);
    const res = await resetSections(picked);   // no automatic download
    if (!res.ok) { setResetMsg(res.message); return; }

    // ⚠️ CLEAR THE ACCOUNT TOO, OR THE RESET UNDOES ITSELF. sync.js treats an
    // empty value as absent and lets a real value win, which is correct when a
    // fresh device meets an established account and exactly wrong here: clear
    // only the browser and the next sign-in pulls it all back, reporting
    // success. See the long note in stats.js.
    let pushed = false;
    if (client && session?.user) {
      try { await pushRemote(client, session.user.id, readLocal()); pushed = true; }
      catch (e) { setError("Cleared on this device, but the account could not be updated: " +
                           (e?.message || String(e)) + " — sign in again to retry."); }
    }
    setPicked([]);
    await refresh();
    setResetMsg(
      `Cleared ${res.sections.join(" and ")}` +
      (pushed ? ", on this device and in your account." :
        session ? "." :
        ". You are not signed in, so this cleared this device only — if you sign in later, progress saved to your account will come back.") +
      " Reload to see it."
    );
  };

  if (!open) return null;

  const close = () => { if (phase !== "conflict") setOpen(false); };
  const tabBtn = (id, text) => (
    <button onClick={() => setTab(id)} style={{
      background: "none", border: "none", cursor: "pointer", padding: "8px 2px",
      marginRight: 18, font: `${tab === id ? 600 : 400} 14px ${T.uiFont}`,
      color: tab === id ? T.ink : T.sub,
      borderBottom: `2px solid ${tab === id ? T.ink : "transparent"}`,
    }}>{text}</button>
  );

  return (
    <>
      <div onClick={close} aria-hidden="true" style={{
        position: "fixed", inset: 0, zIndex: 30, background: "rgba(34,37,43,0.44)",
      }} />
      <div role="dialog" aria-modal="true" aria-label="Account" style={{
        position: "fixed", zIndex: 31, left: "50%", top: "50%",
        transform: "translate(-50%,-50%)", width: "min(92vw, 460px)",
        maxHeight: "86vh", overflowY: "auto", ...box,
      }}>
        <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}>
          <h2 style={{ font: `600 17px ${T.uiFont}`, margin: 0 }}>Account</h2>
          {phase !== "conflict" && (
            <button onClick={close} aria-label="Close" style={{
              background: "none", border: "none", cursor: "pointer",
              padding: 8, font: `16px ${T.uiFont}`, color: T.sub,
            }}>✕</button>
          )}
        </div>

        {/* A conflict takes the whole panel. It is the only thing in this file
            that must be answered before anything else can be done. */}
        {phase === "conflict" && plan ? (
          <>
            <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
              This device and your account both have progress, and they do not
              match. Nothing has been changed yet.
            </p>
            <ul style={{ font: `14px/1.7 ${T.uiFont}`, color: T.ink, paddingLeft: 20, margin: "10px 0" }}>
              {plan.conflicts.map((k) => <li key={k}>{label(k)}</li>)}
            </ul>
            {(plan.pushed.length > 0 || plan.pulled.length > 0) && (
              <p style={{ font: `13px/1.6 ${T.uiFont}`, color: T.sub }}>
                Everything else is kept from both sides either way — only the
                items above have to be decided.
              </p>
            )}
            <div style={{ display: "flex", flexDirection: "column", gap: 8, marginTop: 14 }}>
              <button onClick={() => choose("local")} style={primary}>
                Keep what is on this device
              </button>
              <button onClick={() => choose("remote")} style={ghost}>
                Keep what is in my account
              </button>
              {/* Offered BEFORE the choice, not fired after it. The asymmetry
                  below is real and is stated rather than papered over. */}
              <button onClick={() => {
                const ok = preserveLocalToFile();
                setSavedCopy(ok ? "Saved. The file is in your downloads." :
                                  "The browser would not save the file.");
              }} style={{ ...ghost, borderStyle: "dashed" }}>
                Save this device's version to a file first
              </button>
            </div>
            {savedCopy && (
              <p role="status" style={{ ...quiet, color: T.ok, marginTop: 8 }}>{savedCopy}</p>
            )}
            <p style={{ ...quiet, marginTop: 12 }}>
              Your account keeps its own history either way, so choosing this
              device is always reversible. Choosing your account replaces what is
              here — save a copy first if you are not sure.
            </p>
          </>
        ) : (
          <>
            <div style={{ borderBottom: `1px solid ${T.hairline}`, margin: "6px 0 14px" }}>
              {tabBtn("account", "Account")}
              {tabBtn("stats", "Progress")}
            </div>

            {tab === "account" && (
              <>
                {!accountsConfigured() && (
                  <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.sub }}>
                    Accounts are not switched on in this build. Your progress is
                    saved in this browser, and Save still writes it to a file you
                    can keep.
                  </p>
                )}

                {accountsConfigured() && !session && phase !== "sent" && (
                  <>
                    <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.sub, marginTop: 0 }}>
                      Sign in and your progress follows you to any device. Right
                      now it lives only in this browser — clearing it would clear
                      your work.
                    </p>
                    <form onSubmit={sendLink} style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}>
                      <input
                        type="email" required value={email} autoComplete="email"
                        onChange={(ev) => setEmail(ev.target.value)}
                        placeholder="you@example.com"
                        style={{
                          flex: "1 1 200px", minWidth: 0, padding: "10px 12px",
                          border: `1px solid ${T.hairline}`, borderRadius: 8,
                          font: `14px ${T.uiFont}`, color: T.ink, background: T.paper,
                        }}
                      />
                      <button type="submit" disabled={phase === "sending"} style={primary}>
                        {phase === "sending" ? "Sending…" : "Email me a link"}
                      </button>
                    </form>
                    <p style={{ ...quiet, marginTop: 10 }}>
                      No password. We email a link that signs you in on this device.
                    </p>
                  </>
                )}

                {phase === "sent" && !session && (
                  <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.ink, marginTop: 8 }}>
                    Check <strong>{email}</strong>. The link signs you in on this
                    device — open it in this browser rather than another one.
                  </p>
                )}

                {session && (
                  <dl style={{ margin: "0 0 14px", font: `14px/1.7 ${T.uiFont}` }}>
                    <div style={{ display: "flex", gap: 10 }}>
                      <dt style={{ color: T.sub, minWidth: 96 }}>Signed in as</dt>
                      <dd style={{ margin: 0, wordBreak: "break-all" }}>{session.user.email}</dd>
                    </div>
                    <div style={{ display: "flex", gap: 10, marginTop: 4 }}>
                      <dt style={{ color: T.sub, minWidth: 96 }}>Progress</dt>
                      <dd style={{ margin: 0, color: phase === "syncing" ? T.sub : T.ok }}>
                        {phase === "syncing" ? "Syncing…" : "Saved to your account"}
                      </dd>
                    </div>
                  </dl>
                )}

                {note && (
                  <p role="status" style={{
                    font: `13px/1.6 ${T.uiFont}`, color: T.note,
                    background: T.noteBg, borderRadius: 8, padding: "10px 12px",
                  }}>{note}</p>
                )}

                {/* ————— Settings ————— */}
                {/* Both of these were only reachable from inside the grammar
                    module, which is a strange place for a preference to live. */}
                <h3 style={{ font: `600 13px ${T.uiFont}`, letterSpacing: ".4px",
                             color: T.sub, margin: "18px 0 8px" }}>SETTINGS</h3>
                {SETTINGS.map((s) => (
                  <div key={s.key} style={{ marginBottom: 12 }}>
                    <label htmlFor={`set-${s.key}`}
                           style={{ display: "block", font: `14px ${T.uiFont}`, marginBottom: 5 }}>
                      {s.label}
                    </label>
                    <select id={`set-${s.key}`} value={settings[s.key] ?? s.fallback}
                            onChange={(e) => changeSetting(s.key, e.target.value)}
                            style={{
                              width: "100%", padding: "9px 10px", borderRadius: 8,
                              border: `1px solid ${T.hairline}`, background: T.paper,
                              font: `14px ${T.uiFont}`, color: T.ink,
                            }}>
                      {s.options.map((o) => (
                        <option key={o.value} value={o.value}>{o.label}</option>
                      ))}
                    </select>
                  </div>
                ))}
                <p style={quiet}>
                  A change here applies the next time you open that section.
                </p>

                <h3 style={{ font: `600 13px ${T.uiFont}`, letterSpacing: ".4px",
                             color: T.sub, margin: "18px 0 8px" }}>YOUR DATA</h3>
                <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                  <button onClick={downloadProgress} style={ghost}>Save to a file</button>
                  <label style={{ ...ghost, display: "inline-block" }}>
                    Restore from a file
                    <input type="file" accept="application/json" onChange={restore}
                           style={{ display: "none" }} />
                  </label>
                  {session && <button onClick={signOut} style={ghost}>Sign out</button>}
                </div>
                {session && (
                  <p style={{ ...quiet, marginTop: 10 }}>
                    Signing out leaves this device's progress exactly where it is.
                  </p>
                )}
              </>
            )}

            {tab === "stats" && (
              <>
                {dormantDays != null && dormantDays >= DORMANT_DAYS && (
                  <p role="status" style={{
                    font: `13px/1.6 ${T.uiFont}`, color: T.note, background: T.noteBg,
                    borderRadius: 8, padding: "10px 12px", marginTop: 0,
                  }}>
                    It has been about {Math.floor(dormantDays / 7)} weeks since you
                    last studied. Everything is exactly where you left it — but if
                    you would rather begin a section again from the start, you can
                    clear it below. Nothing here expires on its own.
                  </p>
                )}

                <div style={{ display: "flex", alignItems: "baseline",
                              justifyContent: "space-between", marginBottom: 10 }}>
                  <h3 style={{ font: `600 13px ${T.uiFont}`, letterSpacing: ".4px",
                               color: T.sub, margin: 0 }}>WHAT YOU CAN DO</h3>
                  <span style={{ font: `13px ${T.uiFont}`, color: T.note }}>
                    <span style={{ fontFamily: T.jpFont }}>小判</span> {wallet}
                  </span>
                </div>

                <ul style={{ listStyle: "none", padding: 0, margin: "0 0 6px" }}>
                  {stats.map((s) => (
                    <li key={s.id} style={{
                      display: "flex", alignItems: "baseline", justifyContent: "space-between",
                      padding: "9px 0", borderBottom: `1px solid ${T.hairline}`,
                    }}>
                      <span style={{ font: `14px ${T.uiFont}` }}>
                        {s.label}{" "}
                        <span style={{ font: `13px ${T.jpFont}`, color: T.sub }}>{s.jp}</span>
                      </span>
                      <span style={{ font: `13px ${T.uiFont}`, color: s.started ? T.ink : T.sub }}>
                        {s.started ? s.unit(s.count) : "not started"}
                      </span>
                    </li>
                  ))}
                </ul>

                <h3 style={{ font: `600 13px ${T.uiFont}`, letterSpacing: ".4px",
                             color: T.sub, margin: "18px 0 8px" }}>START A SECTION AGAIN</h3>
                <p style={{ ...quiet, marginTop: 0 }}>
                  Choose what to clear. Nothing is downloaded automatically — if
                  you want to be able to undo this, save a copy first.
                </p>
                <div style={{ margin: "10px 0" }}>
                  {stats.map((s) => (
                    <label key={s.id} style={{
                      display: "flex", alignItems: "center", gap: 9, padding: "6px 0",
                      font: `14px ${T.uiFont}`, color: s.started ? T.ink : T.sub,
                      cursor: s.started ? "pointer" : "default",
                    }}>
                      <input
                        type="checkbox" disabled={!s.started}
                        checked={picked.includes(s.id)}
                        onChange={(e) => setPicked((p) =>
                          e.target.checked ? [...p, s.id] : p.filter((x) => x !== s.id))}
                      />
                      {s.label}
                      {!s.started && <span style={quiet}>— nothing to clear</span>}
                    </label>
                  ))}
                </div>

                {!confirming ? (
                  <button onClick={() => setConfirming(true)} disabled={!picked.length}
                          style={{ ...ghost, opacity: picked.length ? 1 : 0.5,
                                   color: picked.length ? T.shu : T.sub,
                                   borderColor: picked.length ? T.shu : T.hairline }}>
                    Clear selected…
                  </button>
                ) : (
                  <div style={{ border: `1px solid ${T.shu}55`, borderRadius: 8, padding: 12 }}>
                    <p style={{ font: `14px/1.6 ${T.uiFont}`, margin: "0 0 10px" }}>
                      Clear <strong>{stats.filter((s) => picked.includes(s.id))
                        .map((s) => s.label).join(" and ")}</strong>? This cannot be
                      undone unless you save a copy first.
                      {!session && " You are not signed in, so this clears this device only."}
                    </p>
                    <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
                      <button onClick={() => {
                        const ok = preserveLocalToFile();
                        setSavedCopy(ok ? "Saved. The file is in your downloads." :
                                          "The browser would not save the file.");
                      }} style={{ ...ghost, borderStyle: "dashed" }}>
                        Save a copy first
                      </button>
                      <button onClick={doReset} style={danger}>Yes, clear it</button>
                      <button onClick={() => setConfirming(false)} style={ghost}>Cancel</button>
                    </div>
                    {savedCopy && (
                      <p role="status" style={{ ...quiet, color: T.ok, marginTop: 8 }}>{savedCopy}</p>
                    )}
                  </div>
                )}

                {resetMsg && (
                  <p role="status" style={{
                    font: `13px/1.6 ${T.uiFont}`, color: T.note, background: T.noteBg,
                    borderRadius: 8, padding: "10px 12px", marginTop: 12,
                  }}>{resetMsg}</p>
                )}
              </>
            )}
          </>
        )}

        {error && (
          <p role="alert" style={{
            font: `13px/1.6 ${T.uiFont}`, color: T.shu, marginTop: 12,
          }}>{error}</p>
        )}
      </div>
    </>
  );
}
