// ————— The engagement panel on Home —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// Three jobs, none of which belong in the authoring module:
//   1. carry the scoped stylesheet that stands in for the Tailwind the module
//      is written in (see build-vite-app.py's engagement section for why)
//   2. tell it which modules the learner has actually unlocked
//   3. forward the host app's study signal into reportActivity
//
// Lazy, so a learner who never scrolls past the hero card does not pay for the
// quote bank — it is the largest thing on Home by some margin.

import { useState, useEffect, useCallback, lazy, Suspense } from "react";
import { ENGAGEMENT_CSS } from "./engagementStyles.js";
import { onStudy } from "./activity.js";

const EngagementModule = lazy(() => import("../modules/Engagement.jsx"));

export default function EngagementPanel({ startedMap }) {
  const [api, setApi] = useState(null);

  // A stable identity: the module calls this from an effect keyed on it, so a
  // new function every render would loop.
  const onApi = useCallback((a) => setApi(a), []);

  useEffect(() => {
    if (!api?.reportActivity) return undefined;
    return onStudy((moduleId) => api.reportActivity(moduleId));
  }, [api]);

  // WHICH DOORS ARE OPEN. The module treats `unlocked` as read-only truth owned
  // by someone else — §5, "one store per concern" — and Home has already read
  // exactly this. Passing it means the quest chain cannot offer a katakana task
  // to somebody who has not opened katakana.
  //
  // The checker is deliberately absent from `startedMap` (it stores no
  // progress), so it is unlocked once anything else has begun: it is the one
  // door that does not need a prerequisite, and gating it on itself would mean
  // it never appeared in a chain at all.
  const anyStarted = Object.values(startedMap || {}).some(Boolean);
  const unlocked = {
    hiragana: Boolean(startedMap?.hiragana),
    katakana: Boolean(startedMap?.katakana),
    kanji: Boolean(startedMap?.kanji),
    vocab: Boolean(startedMap?.vocabulary),
    grammar: Boolean(startedMap?.grammar),
    checker: anyStarted,
  };

  // ⚠️ EXPLICIT ZEROES, NOT THE DEFAULT. engagement-module.jsx defaults `due` to
  // { kanji: 6, … } — a demo value that makes the chain open with "clear your
  // kanji reviews" whether or not any review is due. Nothing in the app computes
  // real due counts outside the modules that own them yet, so the honest input
  // is zero: the chain then builds from "meet one new set" tasks, which are
  // always true statements. Wire real counts here when a module exposes them;
  // do not restore the default by omitting the prop.
  const due = { kanji: 0, vocab: 0, grammar: 0 };

  // Nothing to offer anyone who has not started anything — deriveQuests returns
  // an empty chain and the card would be a heading with no content under it.
  if (!anyStarted) return null;

  return (
    <div className="eng-scope" style={{ marginBottom: 22 }}>
      <style>{ENGAGEMENT_CSS}</style>
      <Suspense fallback={null}>
        <EngagementModule unlocked={unlocked} due={due} devTools={false} onApi={onApi} />
      </Suspense>
    </div>
  );
}
