// GENERATED by build-vite-app.py — the loadJSON/saveJSON pair every module
// carried its own identical copy of.
export async function loadJSON(key, fallback) {
  try { const r = await window.storage.get(key); return r ? JSON.parse(r.value) : fallback; }
  catch { return fallback; }
}
export async function saveJSON(key, v) {
  try { await window.storage.set(key, JSON.stringify(v)); }
  catch (e) { console.error("save failed: " + key, e); }
}
