// ————— Sections, stats, settings and reset —————
// HAND-MAINTAINED. Not generated by build-vite-app.py.
//
// One place that knows which storage keys belong to which section of the app.
// Before this, that mapping was implicit in five different modules and in
// App.jsx's PROGRESS_KEYS, which is how a key goes missing from an export for
// twelve days without anyone noticing.

import { storage, KEYS, downloadProgress } from "./storage.js";

// ⚠️ COUNTS ARE STATED AS CAPABILITY, NEVER AS WORKLOAD. The standing rule is
// that no lesson counts appear in the UI, because they read as a backlog and
// discourage. "31 kanji you can read" and "31 of 240 lessons done" are the same
// arithmetic and opposite messages: one says what you can do now, the other
// says how far you still have to walk. Every `unit` below is written in the
// first voice, and that is the reason these numbers are allowed to exist at all.
//
// `count` is deliberately the number of THINGS THE LEARNER HAS MET, not of
// lessons completed. Completion is defined differently inside each module and
// reverse-engineering five private schemas here would produce a number that
// drifts silently the first time any module changes. Entries-touched is
// something every store agrees on.
export const SECTIONS = [
  { id: "hiragana", label: "Hiragana", jp: "ひらがな",
    keys: ["hiragana-progress-v2"], countFrom: "hiragana-progress-v2",
    unit: (n) => `${n} kana practised` },
  { id: "katakana", label: "Katakana", jp: "カタカナ",
    keys: ["katakana-progress-v1"], countFrom: "katakana-progress-v1",
    unit: (n) => `${n} kana practised` },
  { id: "grammar", label: "Grammar", jp: "ぶんぽう",
    // learner-depth-v1 is a SETTING, not progress — see SETTINGS below. It is
    // deliberately absent from `keys`, so resetting grammar does not silently
    // change how explanations are written for someone.
    keys: ["n5-progress-v1"], countFrom: "n5-progress-v1",
    unit: (n) => `${n} grammar points met` },
  { id: "kanji", label: "Kanji", jp: "漢字",
    keys: ["kanji-progress-v1", "known-kanji-v1"], countFrom: "known-kanji-v1",
    unit: (n) => `${n} kanji you can read` },
  { id: "vocabulary", label: "Vocabulary", jp: "ことば",
    keys: ["known-words-v1"], countFrom: "known-words-v1",
    unit: (n) => `${n} words you have met` },
  // The checker's first store (Session 24). Two things make it belong here and
  // neither is bookkeeping:
  //
  // 1. RESET. A learner must be able to delete their own record of their own
  //    mistakes, and being unable to would be worse here than for any other key
  //    in the app. A section is how reset reaches a key.
  // 2. THE COUNT COMES OUT RIGHT FOR FREE. countProgress() skips keys beginning
  //    with "_", and the store's only non-pattern bucket is "_checks" — so this
  //    counts DISTINCT PATTERNS MET without knowing anything about the shape.
  //
  // The unit is capability voice, per the rule at the top of this file: these
  // are things that have been EXPLAINED to the learner, not a tally of their
  // failures. "N corrections" would be the same arithmetic and the opposite
  // message, which is the whole reason that rule exists.
  { id: "checker", label: "Checker", jp: "直し",
    keys: ["checker-history-v1"], countFrom: "checker-history-v1",
    unit: (n) => `${n} patterns you have met` },
];

// Real settings, discovered by reading the modules rather than the specs: both
// are written by the grammar module and until now could only be changed from
// inside it, which is a strange place for a preference to live.
export const SETTINGS = [
  { key: "kanji-mode", label: "Japanese is shown as",
    options: [{ value: "kanji", label: "Kanji" }, { value: "kana", label: "Kana only" }],
    fallback: "kanji" },
  { key: "learner-depth-v1", label: "Grammar explanations",
    options: [{ value: "full", label: "Full" }, { value: "spine", label: "Just the essentials" }],
    fallback: "full" },
];

const WALLET_KEY = "achievement-points-v1";
const RECENCY_KEY = "module-recency-v1";

// Shape-agnostic on purpose: an array counts by length, an object by entries,
// anything else by nothing. A module changing its schema should make this
// number wrong-ish, never make the screen throw.
export function countProgress(raw) {
  if (raw == null) return 0;
  let v;
  try { v = JSON.parse(raw); } catch { return 0; }
  if (Array.isArray(v)) return v.length;
  if (v && typeof v === "object") {
    return Object.keys(v).filter((k) => !k.startsWith("_")).length;
  }
  return 0;
}

export async function readSectionStats() {
  const out = [];
  for (const s of SECTIONS) {
    const r = await storage.get(s.countFrom);
    const n = countProgress(r?.value);
    out.push({ ...s, count: n, started: n > 0 });
  }
  return out;
}

export async function readWallet() {
  const r = await storage.get(WALLET_KEY);
  const n = Number(r?.value);
  return Number.isFinite(n) ? n : 0;
}

// ————— Recency —————
// App.jsx already knows when real work happened — commitIfWorked() compares a
// module's own progress store across a visit. This records WHEN, per section,
// so Home can order the sections a learner is actually using.
export async function markWorked(sectionId) {
  if (!SECTIONS.some((s) => s.id === sectionId)) return;
  let map = {};
  try {
    const r = await storage.get(RECENCY_KEY);
    map = r ? JSON.parse(r.value) : {};
    if (!map || typeof map !== "object" || Array.isArray(map)) map = {};
  } catch { map = {}; }
  map[sectionId] = new Date().toISOString();
  try { await storage.set(RECENCY_KEY, JSON.stringify(map)); } catch (e) {
    console.error("recency save failed", e);
  }
}

export async function readRecency() {
  try {
    const r = await storage.get(RECENCY_KEY);
    const map = r ? JSON.parse(r.value) : {};
    return map && typeof map === "object" && !Array.isArray(map) ? map : {};
  } catch { return {}; }
}

// Most recent first; sections never worked are absent rather than last.
export function orderByRecency(sectionIds, recency) {
  return [...sectionIds].sort((a, b) => {
    const ta = recency[a] || "", tb = recency[b] || "";
    return tb.localeCompare(ta);
  });
}

// ————— Dormancy —————
export const DORMANT_DAYS = 21;

/** Days since the learner last did anything, or null if they never have. */
export async function daysSinceLastWorked() {
  const recency = await readRecency();
  const stamps = Object.values(recency).filter(Boolean).sort();
  if (!stamps.length) return null;
  const last = new Date(stamps[stamps.length - 1]);
  if (Number.isNaN(last.getTime())) return null;
  return Math.floor((Date.now() - last.getTime()) / 86400000);
}

// ————— Reset —————
//
// ⚠️ RESETTING WHILE SIGNED IN MUST ALSO CLEAR THE ACCOUNT, OR IT UNDOES ITSELF.
// The merge rule in sync.js treats an empty value as absent, so an empty side
// yields to a real one — which is right when a fresh device meets an established
// account, and exactly wrong here. Clear only the browser and the next sign-in
// looks like "this device has nothing, the account has kanji progress", pulls it
// back, and reports success. The learner resets, sees it work, and finds it
// undone tomorrow with no error anywhere.
//
// So the caller MUST push after resetting when a session exists. When there is
// no session, the UI has to say plainly that this clears one device only —
// nothing here can make that not be true, and hiding it would be the same bug
// wearing a nicer face.
//
// Values are written as empty placeholders rather than removed, because that is
// what the modules themselves write for "nothing yet", and it keeps the key in
// the export where a missing key has historically meant silent data loss.
const EMPTY_FOR = (key) =>
  (key === "known-kanji-v1" || key === "known-words-v1") ? "[]" : "{}";

// ⚠️ backupFirst DEFAULTS TO FALSE. It used to default to true and fire a
// download on every reset. Lloyd removed that (Session 23): a file landing in
// someone's Downloads without being asked for is intrusive, and an app that does
// it routinely trains people to ignore it — which is the opposite of what a
// backup is for. The UI now offers the save as a button beside the confirm, and
// the confirmation text says plainly that clearing cannot be undone without one.
// ⚠️ THE ONLY RESET ANY UI SHOULD CALL. resetSections() clears the browser;
// this clears the browser AND the account, which the long note above says is
// not optional. It exists as a function rather than as a block inside a
// component because the reset moved out of Account and into Progress
// (Session 24), and the two copies that would otherwise have existed are
// exactly how the account half gets left behind in one of them.
//
// Returns what happened rather than a sentence, so the caller can word it — but
// `signedIn` and `pushed` are both reported, because "cleared" means something
// different depending on them and a UI that cannot tell will say the wrong one.
export async function resetEverywhere(sectionIds) {
  const res = await resetSections(sectionIds);
  if (!res.ok) return { ...res, signedIn: false, pushed: false };

  let signedIn = false, pushed = false, error = null;
  try {
    const { accountsConfigured, getClient } = await import("./supabase.js");
    if (accountsConfigured()) {
      const client = await getClient();
      const { data } = await client.auth.getSession();
      const user = data?.session?.user;
      if (user) {
        signedIn = true;
        const { pushRemote, readLocal } = await import("./sync.js");
        await pushRemote(client, user.id, readLocal());
        pushed = true;
      }
    }
  } catch (e) {
    // Cleared locally either way. Saying so is the whole point: a silent
    // failure here is the landmine the note above describes.
    error = e?.message || String(e);
  }
  return { ...res, signedIn, pushed, error };
}

export async function resetSections(sectionIds, { backupFirst = false } = {}) {
  const ids = new Set(sectionIds);
  const chosen = SECTIONS.filter((s) => ids.has(s.id));
  if (!chosen.length) return { ok: false, message: "Nothing was selected." };

  // Only when the caller asked for it. For a signed-out learner this file is
  // the ONLY recovery there is, which is why the UI offers it prominently
  // rather than quietly doing it for them.
  let backedUp = false;
  if (backupFirst) {
    try { downloadProgress(); backedUp = true; } catch { backedUp = false; }
  }

  const cleared = [];
  for (const s of chosen) {
    for (const k of s.keys) {
      if (!KEYS.includes(k)) continue;   // never invent a key here
      try { await storage.set(k, EMPTY_FOR(k)); cleared.push(k); } catch (e) {
        console.error("reset failed for " + k, e);
      }
    }
  }
  return {
    ok: true,
    cleared,
    backedUp,
    sections: chosen.map((s) => s.label),
  };
}
