// ————— Progress sync —————
// HAND-MAINTAINED. Not generated by build-vite-app.py — do not add a
// "GENERATED" header and do not expect a rebuild to recreate it.
//
// This file answers one question: when a learner signs in, and this browser and
// their account BOTH hold progress, what happens?
//
// ⚠️ WHY IT IS WRITTEN DOWN RATHER THAN IMPLIED. The app has already shipped
// silent progress loss once — `n5-progress-v1` and `learner-depth-v1` were
// missing from the export list for twelve days, so Restore reported "Restored 7
// saved items" over a restore that had dropped the largest module in the app.
// Introducing accounts is the same bug with a bigger blast radius: a sign-in
// that quietly replaces local state with an empty account, or an empty account
// with local state, looks exactly like success. So the rule below is explicit,
// tested (test-progress-sync.py), and refuses to guess.
//
// ————— THE RULE —————
//
// Progress is compared PER KEY, never as one document. A learner who did kanji
// on their phone and grammar on their laptop has two partial states and no
// conflict at all — merging per key gives them both, and asking them to choose
// would make them destroy one half of their own work.
//
//   1. Key present on one side only        -> take it. Nothing can be lost.
//   2. Key present on both, same content   -> nothing to do.
//   3. Key present on both, different      -> CONFLICT. Do not pick. Ask.
//
// "Same content" is canonical-JSON equality, not string equality: two devices
// can hold identical state serialised in a different key order, and reporting
// that as a conflict would train the learner to dismiss the question.
//
// "Present" means present AND non-empty. A module that has been opened but not
// used writes "{}", and treating that as a rival to real progress would raise a
// conflict over nothing. Note that "0" is NOT empty — a spent koban wallet is a
// real value that a learner earned their way down to.
//
//   4. On a conflict the app asks, with no default and no timer, and names the
//      items that differ.
//
// WHAT HAPPENS TO THE SIDE THAT LOSES — and note the asymmetry, because it is
// the thing to keep in mind before touching this:
//        · the ACCOUNT's version is kept automatically, by the database, which
//          archives every document it replaces (see the archive trigger in
//          supabase/migrations/20260906000000_progress_sync.sql). Nothing the
//          client does can skip it.
//        · the DEVICE's version has no such net. It used to be downloaded
//          automatically before an overwrite; Lloyd removed that (Session 23)
//          on the grounds that a file appearing in someone's Downloads without
//          being asked for is intrusive, and he is right that it is. The save
//          is now a button the learner presses, offered right next to the
//          choice that would overwrite it.
//
// ⚠️ SO THE GUARANTEE IS NOW ASYMMETRIC, AND ANY COPY SAYING OTHERWISE IS
// STALE. Choosing "keep my account" without pressing Save first really does
// discard this device's differing keys, and no wording should imply otherwise.
// The UI says so plainly instead of promising a rescue that no longer happens.
//
// Full write-up, including what was considered and rejected:
// auth-progress-sync-design-v1.md

// ——— PURE MERGE CORE (extracted verbatim at run time by test-progress-sync.py) ———

// A value is "empty" when a module has written a placeholder rather than
// progress. Deliberately a short, literal list: anything cleverer starts
// discarding real state. "0" is absent from it on purpose.
const EMPTY_VALUES = new Set(["", "{}", "[]", "null", "undefined"]);

function isEmptyValue(v) {
  if (v === null || v === undefined) return true;
  return EMPTY_VALUES.has(String(v).trim());
}

// Canonical form for COMPARISON ONLY. The value written to storage is always
// the original string — canonicalising on the way in would rewrite module data
// this file has no business understanding.
function canon(v) {
  try {
    const sort = (x) => {
      if (Array.isArray(x)) return x.map(sort);
      if (x && typeof x === "object") {
        return Object.keys(x).sort().reduce((o, k) => { o[k] = sort(x[k]); return o; }, {});
      }
      return x;
    };
    return JSON.stringify(sort(JSON.parse(v)));
  } catch {
    return String(v);
  }
}

// local, remote: plain maps of key -> string. Returns a plan, not a decision:
// `merged` holds every key that could be settled without asking, and
// `conflicts` lists the keys that could not. A caller that ignores `conflicts`
// and applies `merged` will UNDER-write rather than over-write, which is the
// safe direction to be wrong in.
function mergeProgress(local, remote) {
  const keys = new Set([...Object.keys(local || {}), ...Object.keys(remote || {})]);
  const merged = {};
  const pushed = [];   // this device had it, the account did not
  const pulled = [];   // the account had it, this device did not
  const same = [];
  const conflicts = [];

  for (const k of [...keys].sort()) {
    const l = local ? local[k] : undefined;
    const r = remote ? remote[k] : undefined;
    const lEmpty = isEmptyValue(l);
    const rEmpty = isEmptyValue(r);

    if (lEmpty && rEmpty) continue;                        // nothing either side
    if (rEmpty) { merged[k] = l; pushed.push(k); continue; }
    if (lEmpty) { merged[k] = r; pulled.push(k); continue; }
    if (canon(l) === canon(r)) { merged[k] = l; same.push(k); continue; }
    conflicts.push(k);
  }

  return {
    merged, pushed, pulled, same, conflicts,
    status: conflicts.length ? "conflict" : "clean",
  };
}

// Settle the keys mergeProgress refused to settle. `side` is "local" or
// "remote" and must be an explicit choice made by the learner — there is no
// default value for this argument on purpose.
function resolveConflicts(plan, local, remote, side) {
  if (side !== "local" && side !== "remote") {
    throw new Error('resolveConflicts: side must be "local" or "remote"');
  }
  const out = { ...plan.merged };
  for (const k of plan.conflicts) out[k] = side === "local" ? local[k] : remote[k];
  return out;
}

// ——— END PURE MERGE CORE ———

import { KEYS, exportProgress, importProgress, downloadProgress } from "./storage.js";

// What this browser holds, in the shape mergeProgress wants. exportProgress()
// already filters to KEYS, so a key no module owns can never reach the server.
export function readLocal() {
  return exportProgress().data;
}

// Write a settled map back to the browser. Routed through importProgress so it
// inherits the same KEYS filter as a Restore-from-file, rather than becoming a
// second, subtly different write path.
export function writeLocal(map) {
  return importProgress(JSON.stringify({
    format: "naoshi-progress", version: 1, data: map,
  }));
}

export { mergeProgress, resolveConflicts, isEmptyValue, canon };

// ————— The server side —————
// The row is `data jsonb` holding exactly this map. The server never parses a
// module's value, so it cannot drop a field it does not recognise.

export async function fetchRemote(client, userId) {
  const { data, error } = await client
    .from("naoshi_progress")
    .select("data, version, updated_at")
    .eq("user_id", userId)
    .maybeSingle();
  if (error) throw error;
  return data || { data: {}, version: 0, updated_at: null };
}

export async function pushRemote(client, userId, map) {
  // Only keys the app owns. A stray localStorage entry from another tool on the
  // same origin must not be uploaded to a learner's account.
  const clean = {};
  for (const k of KEYS) if (map[k] !== undefined && map[k] !== null) clean[k] = String(map[k]);
  const { error } = await client
    .from("naoshi_progress")
    .upsert({ user_id: userId, data: clean }, { onConflict: "user_id" });
  if (error) throw error;
  return clean;
}

// Offered as a button, not fired automatically — see the note at the top of this
// file. Returns false if the browser refused the download, so a caller can say
// so rather than claiming a save that did not happen.
export function preserveLocalToFile() {
  try { downloadProgress(); return true; } catch { return false; }
}
