// GENERATED by build-vite-app.py — the union of every module's design tokens.
// They were identical apart from additions. A key holding two different values
// fails the build rather than silently picking one.
export const T = {
  ai: "#3D5A80",
  hairline: "#E4E2DB",
  ink: "#22252B",
  jpFont: '"Hiragino Mincho ProN","Yu Mincho","Noto Serif JP",serif',
  midori: "#3E7C4F",
  note: "#907119",
  noteBg: "#FAF3E0",
  ok: "#3E7C4F",
  okBg: "#EDF5EE",
  paper: "#F7F6F2",
  sheet: "#FFFFFF",
  shu: "#C7351B",
  sub: "#6E7178",
  uiFont: '-apple-system,BlinkMacSystemFont,"Segoe UI","Hiragino Sans","Noto Sans JP",sans-serif',
};
