// GENERATED by build-vite-app.py — do not hand-edit.
import { useState, useEffect, useRef, lazy, Suspense } from "react";
import { downloadProgress, importProgress, storage } from "./lib/storage.js";
import Account from "./lib/account.jsx";
import EngagementPanel from "./lib/engagementPanel.jsx";
import { reportStudy } from "./lib/activity.js";
import { markWorked, readRecency, orderByRecency, readWallet,
         daysSinceLastWorked, DORMANT_DAYS } from "./lib/stats.js";
import { T, ACCENT } from "./lib/tokens.js";
const HiraganaModule = lazy(() => import("./modules/Hiragana.jsx"));
const KatakanaModule = lazy(() => import("./modules/Katakana.jsx"));
const GrammarPractice = lazy(() => import("./modules/Grammar.jsx"));
const KanjiModule = lazy(() => import("./modules/Kanji.jsx"));
const VocabularyModule = lazy(() => import("./modules/Vocabulary.jsx"));
const CheckerModule = lazy(() => import("./modules/Checker.jsx"));

const MODULES = [
  { id: "hiragana", label: "Hiragana", jp: "ひらがな", accent: ACCENT.hiragana, Comp: HiraganaModule },
  { id: "katakana", label: "Katakana", jp: "カタカナ", accent: ACCENT.katakana, Comp: KatakanaModule },
  { id: "grammar", label: "Grammar", jp: "ぶんぽう", accent: ACCENT.grammar, Comp: GrammarPractice },
  { id: "kanji", label: "Kanji", jp: "漢字", accent: ACCENT.kanji, Comp: KanjiModule },
  { id: "vocabulary", label: "Vocabulary", jp: "ことば", accent: ACCENT.vocabulary, Comp: VocabularyModule },
  { id: "checker", label: "Checker", jp: "直し", accent: ACCENT.checker, Comp: CheckerModule }
];

// ————— Home (Session 13) —————
// The app used to open straight into a module with nothing explaining what
// the five doors are for. Home answers three questions, in order: where was
// I (the continue card), where should a newcomer go first (hiragana — it
// gates everything), and what is everything else for — one honest line each,
// stating capability, never workload: no counts anywhere, per the standing
// rule. Mobile-first: one column, whole cards tappable, thumb-size targets.
const HOME_WHY = {
  hiragana: "The script that holds every sentence together. Everything else here assumes it — this is where Japanese starts.",
  katakana: "The second script: loanwords, menus, signs. Runs alongside hiragana, at whatever pace suits you.",
  grammar: "The heart of the app — lessons and graded writing practice, from your first sentence upward.",
  kanji: "Characters in an order that pays for itself: each one unlocks words you already use.",
  vocabulary: "The words you have met, coming back just before you would forget them.",
  checker: "Write anything in Japanese and find out what is wrong, what merely sounds off, and why.",
};
// Shown INSTEAD of HOME_WHY when the learner has started nothing. Not a lock —
// the door stays open either way; this just tells the right person it is theirs.
const HOME_INVITE = {
  checker: "Do you have Japanese experience? Try out the checker! Write a sentence and find out what is wrong, what merely sounds off, and why.",
};
const PROGRESS_KEYS = {
  hiragana: "hiragana-progress-v2", katakana: "katakana-progress-v1",
  grammar: "n5-progress-v1", kanji: "kanji-progress-v1", vocabulary: "known-words-v1",
};

// Read through `storage`, NOT localStorage directly (Session 21). The old
// version called localStorage.getItem here while every module went through the
// storage adapter — which falls back to an in-memory map in a private window or
// wherever site data is blocked. In that case the modules held real progress
// and Home reported none, showing "START HERE" to someone mid-course. One store
// per concern: if the modules read it through the adapter, so does Home.
async function readStarted() {
  const out = {};
  for (const [id, key] of Object.entries(PROGRESS_KEYS)) {
    const r = await storage.get(key);
    const v = r?.value;
    out[id] = v != null && v !== "{}" && v !== "[]";
  }
  return out;
}

// The next unfinished task of the current quest chain, if one exists.
// Written by the engagement module (engagement-v1). Absent until that module is
// wired in and reportActivity() has call sites — Home falls back to the
// continue card, so this is dark rather than broken until then.
async function readNextTask() {
  try {
    const r = await storage.get("engagement-v1");
    const chain = r ? JSON.parse(r.value)?.chain : null;
    const t = chain?.tasks?.find((x) => x.done < x.target);
    if (!t) return null;
    return MODULES.some((m) => m.id === t.module) ? t : null;
  } catch (e) { return null; }
}

function Home({ startedMap, lastMod, nextTask, go, recency, wallet, dormantDays, openAccount }) {
  const fresh = !MODULES.some((m) => startedMap[m.id]);
  const started = (id) => Boolean(startedMap[id]);

  // Hero priority: what to DO now > where you were > where to begin.
  // Session 21 — Home answered "where can I go" six times over and "what should
  // I do" not at all, so every session opened with a decision. A module name is
  // not an action: "Continue › Kanji" still leaves the choosing to the learner.
  // Started sections, most recently worked first. A section with progress but
  // no recency stamp (it was studied before this was recorded) sorts last
  // rather than vanishing — absent evidence is not evidence of absence.
  const startedIds = MODULES.filter((m) => started(m.id)).map((m) => m.id);
  const shownModules = fresh
    ? MODULES
    : orderByRecency(startedIds, recency || {}).map((id) => MODULES.find((m) => m.id === id));

  const taskMod = nextTask ? MODULES.find((m) => m.id === nextTask.module) : null;
  const hero = taskMod || lastMod || MODULES[0];
  const heroLabel = taskMod ? "NEXT ON YOUR PATH"
    : lastMod ? "PICK UP WHERE YOU LEFT OFF" : "NEW HERE? START WITH";
  const heroCta = taskMod ? "Go ›" : lastMod ? "Continue ›" : "Start here ›";
  const cardBase = {
    display: "block", width: "100%", textAlign: "left", cursor: "pointer",
    background: T.sheet, border: `1px solid ${T.hairline}`, borderRadius: 10,
    padding: "14px 16px", fontFamily: T.uiFont, color: T.ink,
  };
  const chip = (text, color) => (
    <span style={{
      font: `600 10px ${T.uiFont}`, letterSpacing: ".5px", color: T.paper,
      background: color, borderRadius: 999, padding: "3px 9px", marginLeft: 8,
      verticalAlign: "middle",
    }}>{text}</span>
  );
  return (
    <div style={{ padding: "18px 16px 36px" }}>
      <button onClick={() => go(hero.id)} style={{
        ...cardBase, border: `2px solid ${T.ink}`, padding: "18px 18px 16px", marginBottom: 22,
      }}>
        <div style={{ font: `600 11px ${T.uiFont}`, letterSpacing: ".7px", color: T.sub }}>
          {heroLabel}
        </div>
        {taskMod ? (
          // The action is the headline; the module name demotes to a subtitle.
          <>
            <div style={{ font: `600 22px/1.4 ${T.uiFont}`, marginTop: 8 }}>
              {nextTask.label}
            </div>
            <p style={{ font: `13px ${T.uiFont}`, color: T.sub, margin: "8px 0 12px" }}>
              in {hero.label} <span style={{ fontFamily: T.jpFont }}>{hero.jp}</span>
            </p>
          </>
        ) : (
          <>
            <div style={{ marginTop: 8, display: "flex", alignItems: "baseline", gap: 10, flexWrap: "wrap" }}>
              <span style={{ font: `600 24px ${T.uiFont}` }}>{hero.label}</span>
              <span style={{ font: `20px ${T.jpFont}`, color: T.sub }}>{hero.jp}</span>
            </div>
            <p style={{ font: `14px/1.6 ${T.uiFont}`, color: T.sub, margin: "8px 0 12px" }}>
              {HOME_WHY[hero.id]}
            </p>
          </>
        )}
        <div style={{ font: `600 15px ${T.uiFont}` }}>{heroCta}</div>
      </button>

      {started("grammar") && (
        // Session 14: the daily review challenge gets a front-door card once
        // grammar has begun — before that it would only point at an empty
        // pool. The flag routes the grammar module straight to the challenge.
        <button
          onClick={() => { try { localStorage.setItem("naoshi-open-challenge", "1"); } catch (e) {} go("grammar"); }}
          style={{ ...cardBase, border: `1px solid ${T.shu}55`, marginBottom: 22 }}
        >
          <div style={{ display: "flex", alignItems: "center", flexWrap: "wrap" }}>
            <span style={{ font: `600 16px ${T.uiFont}` }}>Review challenge</span>
            <span style={{ font: `15px ${T.jpFont}`, color: T.shu, marginLeft: 8 }}>腕試し</span>
          </div>
          <p style={{ font: `13px/1.6 ${T.uiFont}`, color: T.sub, margin: "6px 0 0" }}>
            Draw a grammar point you've learned and write with it. A fresh challenge every day — the day turns at midnight, Tokyo time.
          </p>
        </button>
      )}

      {/* ⚠️ A REMINDER, NOT A DEADLINE. Nothing in this app expires, and the
          note says so in as many words — the point is to tell someone who has
          been away for a month that starting a section again is allowed, not
          to imply that their progress has gone stale. Three weeks is the bar
          (DORMANT_DAYS); it is a long enough gap that "where was I" is a real
          question and short enough to catch someone before they give up. */}
      {dormantDays != null && dormantDays >= DORMANT_DAYS && (
        <button onClick={openAccount} style={{
          ...cardBase, border: `1px solid ${T.note}55`, background: T.noteBg,
          marginBottom: 22,
        }}>
          <div style={{ font: `600 14px ${T.uiFont}`, color: T.note }}>
            Welcome back
          </div>
          <p style={{ font: `13px/1.6 ${T.uiFont}`, color: T.ink, margin: "6px 0 0" }}>
            It has been a while. Everything is exactly where you left it — and if
            you would rather start a section again from the beginning, you can
            clear just that one. Nothing here expires on its own.
          </p>
        </button>
      )}

      {/* The daily card, the weekly rhythm and the current quest chain.
          Renders nothing until something has been started — see
          lib/engagementPanel.jsx. It sits BELOW the hero and above the doors
          because the hero answers "what now" and this answers "how am I
          going"; a learner who has an answer to the first does not need to
          scroll past the second to act on it. */}
      <EngagementPanel startedMap={startedMap} />

      {/* ————— Where you have been, most recent first (Session 23) —————
          Lloyd: once someone has started something, the front door should be
          THEIR sections in the order they last used them, not the same six
          doors in the same order forever. A learner three weeks into kanji does
          not need Hiragana offered first every single time.

          Everything else stays one tap away in the drawer, and the line below
          says so — a shorter front door is only an improvement if the rest of
          the app is still visibly reachable. Someone who has started nothing
          still gets the full list, because for them the six doors ARE the
          information. */}
      <div style={{ font: `600 11px ${T.uiFont}`, letterSpacing: ".7px", color: T.sub, marginBottom: 10 }}>
        {fresh ? "EVERYWHERE YOU CAN GO" : "WHERE YOU LEFT OFF"}
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
        {shownModules.map((m) => (
          // The accent rule sits on the card too, not only inside the section,
          // so the mapping is learned on the way in rather than discovered after.
          <button key={m.id} onClick={() => go(m.id)}
                  style={{ ...cardBase, borderTop: `4px solid ${m.accent}` }}>
            <div style={{ display: "flex", alignItems: "center", flexWrap: "wrap" }}>
              <span style={{ font: `600 16px ${T.uiFont}` }}>{m.label}</span>
              <span style={{ font: `15px ${T.jpFont}`, color: T.sub, marginLeft: 8 }}>{m.jp}</span>
              {m.id === "hiragana" && fresh && chip("START HERE", T.ok)}
              {m.id === "checker" && fresh && chip("ALREADY STUDIED?", T.note)}
              {lastMod?.id === m.id && chip("LAST WORKED ON", T.ink)}
              {lastMod?.id !== m.id && started(m.id) && chip("IN PROGRESS", T.sub)}
            </div>
            <p style={{ font: `13px/1.6 ${T.uiFont}`, color: T.sub, margin: "6px 0 0" }}>
              {/* Session 21 (Lloyd): a day-one learner sees the Checker as a
                  peer of Hiragana and bounces off a tool built for people who
                  can already write — a bad first impression, and a real API
                  cost per call. The answer is an invitation, not a lock:
                  someone arriving with existing Japanese is exactly who the
                  Checker is for, and this is how they find out. */}
              {m.id === "checker" && fresh ? HOME_INVITE.checker : HOME_WHY[m.id]}
            </p>
          </button>
        ))}
      </div>

      {!fresh && (
        <p style={{ font: `13px/1.6 ${T.uiFont}`, color: T.sub, margin: "16px 2px 0" }}>
          Want to try something new? Everything else is in the menu — the
          <span aria-hidden="true"> ☰ </span> at the top left.
        </p>
      )}
    </div>
  );
}

// ————— Side menu (Session 16) —————
// The tab bar was five buttons wide and already wrapped onto a second row on a
// phone, pushing content down before the learner had read anything. A sixth
// door would have made it three rows. A drawer costs one tap to open and in
// exchange gives every module a full-width target with its Japanese name
// beside it — the shape the app is actually used in, which is one-handed.
//
// Deliberately not a <dialog>: Safari's support for inert backdrops is still
// uneven and this needs no form semantics. Scrim + role="dialog" + Escape is
// the boring version that behaves the same everywhere.
function Drawer({ open, close, active, go, onAccount }) {
  const panelRef = useRef(null);

  // Escape closes, and the background does not scroll underneath an open
  // drawer — on a phone that scroll-through is the difference between a menu
  // and a bug.
  useEffect(() => {
    if (!open) return undefined;
    const onKey = (e) => { if (e.key === "Escape") close(); };
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    document.addEventListener("keydown", onKey);
    // Move focus into the panel so a keyboard or screen-reader user lands
    // inside the menu they just opened rather than behind it.
    panelRef.current?.focus();
    return () => {
      document.body.style.overflow = prev;
      document.removeEventListener("keydown", onKey);
    };
  }, [open, close]);

  if (!open) return null;

  const row = (selected) => ({
    display: "flex", alignItems: "baseline", gap: 10, width: "100%",
    background: selected ? T.paper : "none",
    border: "none", borderLeft: `3px solid ${selected ? T.ink : "transparent"}`,
    cursor: "pointer", textAlign: "left", padding: "14px 18px",
    font: `${selected ? 600 : 400} 16px ${T.uiFont}`,
    color: selected ? T.ink : T.sub,
  });

  return (
    <>
      <div onClick={close} aria-hidden="true" style={{
        position: "fixed", inset: 0, zIndex: 20,
        background: "rgba(34,37,43,0.44)",
      }} />
      <nav ref={panelRef} tabIndex={-1} role="dialog" aria-modal="true"
           aria-label="Modules" style={{
        position: "fixed", top: 0, left: 0, bottom: 0, zIndex: 21,
        width: "min(82vw, 300px)", background: T.sheet,
        borderRight: `1px solid ${T.hairline}`,
        display: "flex", flexDirection: "column", outline: "none",
        boxShadow: "0 0 40px rgba(34,37,43,0.18)",
      }}>
        <div style={{
          display: "flex", alignItems: "center", justifyContent: "space-between",
          padding: "14px 12px 14px 18px", borderBottom: `1px solid ${T.hairline}`,
        }}>
          <span style={{ font: `600 19px ${T.jpFont}`, color: T.ink }}>直</span>
          <button onClick={close} aria-label="Close menu" style={{
            background: "none", border: "none", cursor: "pointer",
            padding: 10, font: `18px ${T.uiFont}`, color: T.sub, lineHeight: 1,
          }}>✕</button>
        </div>

        <div style={{ flex: 1, overflowY: "auto", padding: "6px 0" }}>
          <button onClick={() => go("home")} style={row(active === "home")}>
            Home
          </button>
          {MODULES.map((m) => (
            <button key={m.id} onClick={() => go(m.id)} style={row(active === m.id)}>
              {m.label}
              <span style={{ font: `14px ${T.jpFont}`, color: T.sub }}>{m.jp}</span>
            </button>
          ))}
        </div>

        {/* Below the rule, not among the destinations: the drawer list answers
            "where can I go", and an account is not a place. Kept out of the
            header for the reason the drawer exists at all — the header already
            carries Save and Restore and wraps to two rows on a phone. */}
        <div style={{ borderTop: `1px solid ${T.hairline}`, padding: "6px 0" }}>
          <button onClick={onAccount} style={{ ...row(false), borderLeftColor: "transparent" }}>
            Account
          </button>
        </div>
      </nav>
    </>
  );
}

export default function App() {
  // Land on Home. It remembers where they were (naoshi-last-module) and
  // offers it as the continue card, rather than teleporting them there —
  // Session 13: the doors deserve a hallway.
  const [active, setActive] = useState("home");
  const [msg, setMsg] = useState(null);
  const [menuOpen, setMenuOpen] = useState(false);
  const [startedMap, setStartedMap] = useState({});
  const [lastWorked, setLastWorked] = useState(null);
  const [nextTask, setNextTask] = useState(null);
  const [accountOpen, setAccountOpen] = useState(false);
  const [recency, setRecency] = useState({});
  const [wallet, setWallet] = useState(0);
  const [dormantDays, setDormantDays] = useState(null);

  // Home's data is read through the storage adapter, so it must be async and
  // must refresh whenever we come back to Home — a lesson finished inside a
  // module changes both the chips and the hero.
  useEffect(() => {
    if (active !== "home") return undefined;
    let alive = true;
    (async () => {
      const [s, t, last, rec, w, dorm] = await Promise.all([
        readStarted(), readNextTask(), storage.get("naoshi-last-module"),
        readRecency(), readWallet(), daysSinceLastWorked(),
      ]);
      if (!alive) return;
      setStartedMap(s);
      setNextTask(t);
      setLastWorked(last?.value ?? null);
      setRecency(rec);
      setWallet(w);
      setDormantDays(dorm);
    })();
    return () => { alive = false; };
  }, [active]);
  const current = MODULES.find((m) => m.id === active) || MODULES[0];
  const menuBtnRef = useRef(null);

  const closeMenu = () => {
    setMenuOpen(false);
    // Focus goes back to the control that opened the drawer, so keyboard
    // users are not dropped at the top of the document.
    menuBtnRef.current?.focus();
  };

  // ————— "Last worked on", by evidence (Session 21) —————
  // This used to be written the instant you navigated: tapping into Kanji and
  // backing straight out made it your continue card indefinitely. Opening is
  // not doing. Now we snapshot the module's own progress store on the way in
  // and compare on the way out — the flag is only written if the store actually
  // changed. No module edits needed: each one already persists its own state,
  // and that write IS the evidence.
  const snapRef = useRef({ id: null, value: null });

  const snapshot = async (id) => {
    const key = PROGRESS_KEYS[id];
    if (!key) { snapRef.current = { id: null, value: null }; return; }
    const r = await storage.get(key);
    snapRef.current = { id, value: r?.value ?? null };
  };

  const commitIfWorked = async () => {
    const { id, value } = snapRef.current;
    if (!id) return;
    const key = PROGRESS_KEYS[id];
    const r = await storage.get(key);
    if ((r?.value ?? null) !== value) {
      await storage.set("naoshi-last-module", id);
      setLastWorked(id);
      // Same evidence, recorded per section so Home can order by what is
      // actually being used, and so a three-week gap can be noticed.
      await markWorked(id);
      setWallet(await readWallet());
      // Session 23: the same evidence, published for the engagement layer. It
      // is deliberately inside this branch — the whole point of commitIfWorked
      // is that the store CHANGED, and marking a day active on navigation is
      // the exact draft that engagement-module.jsx §5 threw out.
      reportStudy(id);
    }
    snapRef.current = { id: null, value: null };
  };

  const go = (id) => {
    commitIfWorked();
    setActive(id);
    setMenuOpen(false);
    if (id !== "home") snapshot(id);
  };

  // A learner who closes the tab mid-lesson still worked. Commit on hide too.
  useEffect(() => {
    const onHide = () => { if (document.visibilityState === "hidden") commitIfWorked(); };
    document.addEventListener("visibilitychange", onHide);
    return () => document.removeEventListener("visibilitychange", onHide);
  }, []);

  const restore = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    const r = new FileReader();
    r.onload = () => setMsg(importProgress(String(r.result)).message);
    r.readAsText(file);
    e.target.value = "";
  };

  const btn = {
    background: "none", border: "none", cursor: "pointer",
    padding: "8px 10px", borderRadius: 8,
  };

  return (
    <div style={{ background: T.paper, minHeight: "100vh", fontFamily: T.uiFont }}>
      <header style={{
        background: T.sheet,
        // A BAR UNDER THE STICKY HEADER, not a frame around the viewport: a
        // four-sided border costs real width on a phone and this carries the
        // same signal for none. Home keeps the plain hairline — it is not a
        // section and should not claim one's colour.
        borderBottom: active === "home"
          ? `1px solid ${T.hairline}`
          : `3px solid ${current.accent}`,
        position: "sticky", top: 0, zIndex: 10,
      }}>
        <div style={{
          maxWidth: 900, margin: "0 auto", padding: "8px 12px",
          display: "flex", alignItems: "center", gap: 4,
        }}>
          <button ref={menuBtnRef} onClick={() => setMenuOpen(true)}
                  aria-label="Menu" aria-expanded={menuOpen} aria-haspopup="dialog"
                  style={{
            ...btn, padding: 10, display: "flex", flexDirection: "column",
            gap: 4, width: 44, alignItems: "stretch",
          }}>
            {[0, 1, 2].map((i) => (
              <span key={i} style={{
                display: "block", height: 2, background: T.ink, borderRadius: 2,
              }} />
            ))}
          </button>
          <button onClick={() => go("home")} aria-label="Home" style={{
            background: "none", border: "none", cursor: "pointer", padding: "4px 8px",
            font: `600 17px ${T.jpFont}`, color: T.ink, borderRadius: 8,
          }}>直</button>
          <span style={{
            font: `14px ${T.uiFont}`, color: T.sub, marginLeft: 2,
          }}>{active === "home" ? "" : current.label}</span>
          <span style={{ flex: 1 }} />
          {/* ⚠️ THIS REVERSES A RECORDED DECISION, deliberately and on Lloyd's
              instruction (Session 23). reward-system-design-v1.md §1 and the
              engagement module both say the balance is NOT shown in the header
              and is checked in the room/shop. That was written when the room
              existed as a plan; with no room yet, koban were being earned and
              were literally unseeable, which is worse than the problem the rule
              was avoiding. Revisit when the room ships — the original reasoning
              is sound once there is somewhere to spend them. */}
          {wallet > 0 && (
            <span title="Koban you have earned" style={{
              font: `13px ${T.uiFont}`, color: T.note, marginRight: 4,
              whiteSpace: "nowrap",
            }}>
              <span style={{ fontFamily: T.jpFont }}>小判</span> {wallet}
            </span>
          )}
          <button onClick={downloadProgress} title="Save your progress to a file" style={{
            ...btn, border: `1px solid ${T.hairline}`, padding: "6px 12px",
            font: `13px ${T.uiFont}`, color: T.sub,
          }}>Save</button>
          <label style={{
            border: `1px solid ${T.hairline}`, borderRadius: 8, padding: "6px 12px",
            cursor: "pointer", font: `13px ${T.uiFont}`, color: T.sub,
          }}>
            Restore
            <input type="file" accept="application/json" onChange={restore}
                   style={{ display: "none" }} />
          </label>
        </div>
        {msg && (
          <div role="status" style={{
            maxWidth: 900, margin: "0 auto", padding: "0 16px 10px",
            font: `13px ${T.uiFont}`, color: T.note,
          }}>{msg}</div>
        )}
      </header>

      <Drawer open={menuOpen} close={closeMenu} active={active} go={go}
              onAccount={() => { setMenuOpen(false); setAccountOpen(true); }} />

      {/* Mounted unconditionally and self-gating: it renders nothing until
          opened, and it opens ITSELF if a sign-in turns up a progress
          conflict that needs answering. A question about which copy of a
          learner’s work survives must not sit behind a closed menu. */}
      <Account open={accountOpen} setOpen={setAccountOpen} />

      <main style={{ maxWidth: 900, margin: "0 auto" }}>
        {active === "home" ? (
          <Home startedMap={startedMap} nextTask={nextTask} go={go}
                recency={recency} wallet={wallet} dormantDays={dormantDays}
                openAccount={() => setAccountOpen(true)}
                lastMod={MODULES.find((m) => m.id === lastWorked) || null} />
        ) : (
          <Suspense fallback={
            <p style={{ padding: "40px 18px", color: T.sub, font: `14px ${T.uiFont}` }}>Loading…</p>
          }>
            <current.Comp />
          </Suspense>
        )}
      </main>
    </div>
  );
}
